// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const { ObjectId } = require('bson');
// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const setupDb = require('../../tests/setup-db');

// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const { up, down } = require('./20230731181035-fix-schedules-well-refs.js');

let db;
let mongod;
let client;
let projects;
let schedules;
let wells;

const dbProjects = [
	{
		// original project
		_id: new ObjectId('64c414c8bf1b9f62126fe78e'),
		wells: [
			new ObjectId('5e272d38b78910dd2a1bd6a8'),
			new ObjectId('5e272d38b78910dd2a1bd6b5'),
			new ObjectId('5e272d39b78910dd2a1bd7d5'),
			// new ObjectId('64c41508bf1b9f5ada6fe8e8'), // well was removed from the original project
			new ObjectId('64c41508bf1b9f6cbe6fe8e9'), // chosen id for this well was modified on the original project
			new ObjectId('64c41508bf1b9f6e0c6fe8ea'),
			new ObjectId('64c41508bf1b9f5a696fe8eb'),
			new ObjectId('64c41508bf1b9f08406fe8ec'),
			new ObjectId('64c41508bf1b9f37876fe8ed'),
			new ObjectId('64c41508bf1b9f45fe6fe8ee'),
			new ObjectId('64c41508bf1b9f83ab6fe8ef'),
			new ObjectId('64c41508bf1b9fb9e16fe8f0'),
			new ObjectId('64c41508bf1b9fe2fa6fe8f1'),
		],
		scenarios: [],
		tags: [],
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		name: 'Test',
		createdAt: new Date('2023-07-01T19:19:37.583+0000'),
		updatedAt: new Date('2023-07-01T19:20:40.076+0000'),
		__v: 0,
	},
	{
		// copied project before the release date
		// schedule well ids should be kept the same
		_id: new ObjectId('64c41552bf1b9f4ce06fece1'),
		wells: [
			new ObjectId('5e272d38b78910dd2a1bd6a8'),
			new ObjectId('5e272d38b78910dd2a1bd6b5'),
			new ObjectId('5e272d39b78910dd2a1bd7d5'),
			new ObjectId('64c41552bf1b9f824f6fecf5'),
			new ObjectId('64c41552bf1b9f72d36fecf6'),
			new ObjectId('64c41552bf1b9f595b6fecf7'),
			new ObjectId('64c41552bf1b9f4d9c6fecf4'),
			new ObjectId('64c41552bf1b9f22896fecf1'),
			new ObjectId('64c41552bf1b9f056f6fecf2'),
			new ObjectId('64c41552bf1b9f6d076fecf3'),
			new ObjectId('64c41552bf1b9f53ea6fecf8'),
			new ObjectId('64c41552bf1b9f13306fecf9'),
			new ObjectId('64c41552bf1b9f1fb86fecfa'),
		],
		scenarios: [],
		tags: [],
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		name: 'Test 1 - Copy - Before release',
		createdAt: new Date('2023-07-01T19:21:55.295+0000'),
		updatedAt: new Date('2023-07-01T20:53:09.673+0000'),
		__v: 0,
		copiedFrom: new ObjectId('64c414c8bf1b9f62126fe78e'),
	},
	{
		// copied project between the release date and the bugfix date
		_id: new ObjectId('64c41552bf1b9f4ce06fece2'),
		wells: [
			new ObjectId('5e272d38b78910dd2a1bd6a8'),
			new ObjectId('5e272d38b78910dd2a1bd6b5'),
			new ObjectId('5e272d39b78910dd2a1bd7d5'),
			new ObjectId('64c41552bf1b9f824f6fecf5'),
			new ObjectId('64c41552bf1b9f72d36fecf6'),
			new ObjectId('64c41552bf1b9f595b6fecf7'),
			new ObjectId('64c41552bf1b9f4d9c6fecf4'),
			new ObjectId('64c41552bf1b9f22896fecf1'),
			new ObjectId('64c41552bf1b9f056f6fecf2'),
			new ObjectId('64c41552bf1b9f6d076fecf3'),
			new ObjectId('64c41552bf1b9f53ea6fecf8'),
			new ObjectId('64c41552bf1b9f13306fecf9'),
			new ObjectId('64c41552bf1b9f1fb86fecfa'),
		],
		scenarios: [],
		tags: [],
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		name: 'Test 2 - Copy',
		createdAt: new Date('2023-07-28T19:21:55.295+0000'),
		updatedAt: new Date('2023-07-28T20:53:09.673+0000'),
		__v: 0,
		copiedFrom: new ObjectId('64c414c8bf1b9f62126fe78e'),
	},
	{
		// copied project but copiedFrom was deleted => no changes
		_id: new ObjectId('64c41552bf1b9f4ce06fece3'),
		wells: [new ObjectId('64c41552bf1b9f13306fecf9'), new ObjectId('64c41552bf1b9f1fb86fecfa')],
		scenarios: [],
		tags: [],
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		name: 'Test 2 - Copy from was deleted',
		createdAt: new Date('2023-07-28T19:21:55.295+0000'),
		updatedAt: new Date('2023-07-28T20:53:09.673+0000'),
		__v: 0,
		copiedFrom: new ObjectId('64c414c8bf1b9f62126fe78f'),
	},
];

const dbSchedules = [
	{
		_id: new ObjectId('64c41552bf1b9fbcf16fed00'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece1'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('64c41552bf1b9f595b6fecf7'),
				status: 'producing',
			},
			{
				well: new ObjectId('64c41552bf1b9f53ea6fecf8'),
				status: 'producing',
			},
			{
				well: new ObjectId('64c41552bf1b9f13306fecf9'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f1fb86fecfa'),
				status: 'producing',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-01T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-01T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		_id: new ObjectId('64c41552bf1b9fd2af6fed00'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test - 1',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6a8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6b5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d39b78910dd2a1bd7d5'),
				status: 'not_started',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-28T19:21:54.865+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.865+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		_id: new ObjectId('64c41552bf1b9fbcf16fed01'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6a8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6b5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d39b78910dd2a1bd7d5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f08406fe8ec'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f37876fe8ed'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f45fe6fe8ee'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f5a696fe8eb'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f5ada6fe8e8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f6cbe6fe8e9'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f6e0c6fe8ea'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9f83ab6fe8ef'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9fb9e16fe8f0'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9fe2fa6fe8f1'),
				status: 'not_started',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-28T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		// schedule inside a project that copiedFrom was deleted => no changes
		_id: new ObjectId('64c41552bf1b9fbcf16fed02'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece1'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('64c41508bf1b9fb9e16fe8f0'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9fe2fa6fe8f1'),
				status: 'producing',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-01T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-01T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
];

const fixedSchedules = [
	{
		_id: new ObjectId('64c41552bf1b9fbcf16fed00'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece1'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('64c41552bf1b9f595b6fecf7'),
				status: 'producing',
			},
			{
				well: new ObjectId('64c41552bf1b9f53ea6fecf8'),
				status: 'producing',
			},
			{
				well: new ObjectId('64c41552bf1b9f13306fecf9'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f1fb86fecfa'),
				status: 'producing',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-01T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-01T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		_id: new ObjectId('64c41552bf1b9fd2af6fed00'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test - 1',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6a8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6b5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d39b78910dd2a1bd7d5'),
				status: 'not_started',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-28T19:21:54.865+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.865+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		_id: new ObjectId('64c41552bf1b9fbcf16fed01'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6a8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d38b78910dd2a1bd6b5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('5e272d39b78910dd2a1bd7d5'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f22896fecf1'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f056f6fecf2'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f6d076fecf3'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f4d9c6fecf4'),
				status: 'not_started',
			},
			{
				// this well was removed from the original project
				// for now we will keep it as it is
				// correct value: 64c41552bf1b9f824f6fecf5

				well: new ObjectId('64c41508bf1b9f5ada6fe8e8'),
				status: 'not_started',
			},
			{
				// chosenID for this well was modified on the original project
				// then it's not able to map correctly
				// correct value: 64c41552bf1b9f72d36fecf6
				well: new ObjectId('64c41508bf1b9f6cbe6fe8e9'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f595b6fecf7'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f53ea6fecf8'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f13306fecf9'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41552bf1b9f1fb86fecfa'),
				status: 'not_started',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-28T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
	{
		_id: new ObjectId('64c41552bf1b9fbcf16fed02'),
		modified: true,
		constructed: false,
		tags: [],
		method: 'auto',
		name: 'test',
		project: new ObjectId('64c41552bf1b9f4ce06fece1'),
		createdBy: new ObjectId('62686a77383b530012a0f42e'),
		inputData: [
			{
				well: new ObjectId('64c41508bf1b9fb9e16fe8f0'),
				status: 'not_started',
			},
			{
				well: new ObjectId('64c41508bf1b9fe2fa6fe8f1'),
				status: 'producing',
			},
		],
		qualifiers: [],
		createdAt: new Date('2023-07-01T19:21:54.812+0000'),
		updatedAt: new Date('2023-07-01T19:21:54.812+0000'),
		__v: 0,
		setting: new ObjectId('64c41552bf1b9f49386fed08'),
	},
];

const dbWells = [
	{
		_id: new ObjectId('5e272d38b78910dd2a1bd6a8'),
		chosenID: 'postman-test',
		dataSource: 'other',
		project: null,
		abstract: '194',
		api14: '42477310250001',
		basin: 'GULF COAST CENTRAL',
		chosenKeyID: 'chosenID',
		county: 'WASHINGTON (TX)',
		createdAt: new Date('2020-01-21T16:56:24.865+0000'),
		current_operator_alias: 'ENERVEST',
		dataPool: 'external',
		elevation: 434.67,
		elevation_type: 'KB EST',
		field: 'GIDDINGS',
		first_fluid_volume: null,
		first_prod_date: '2022-12-16T00:00:00.000+0000',
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		first_prop_weight: null,
		geohash: '9zpgxczbzury',
		ground_elevation: 416.67,
		has_daily: false,
		has_monthly: false,
		hole_direction: 'H',
		inptID: 'INPT.4NiF1fniYl',
		lateral_length: null,
		lease_name: 'SWM COOP UNIT WELL',
		location: {
			type: 'Point',
			coordinates: [-90, 40],
		},
		measured_depth: null,
		mostRecentImport: new ObjectId('5f1b6511a5e1e208ccb34baa'),
		perf_lateral_length: 3000,
		play: 'EAGLEBINE',
		primary_product: 'gas',
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		state: 'TX',
		status: 'EXPIRED PERMIT',
		surfaceLatitude: 40,
		surfaceLongitude: -90,
		survey: 'PHELPS, M',
		toeLatitude: 30.1419674,
		toeLocation: {
			type: 'Point',
			coordinates: [-96.7049507, 30.1419674],
		},
		toeLongitude: -96.7049507,
		total_fluid_per_perforated_interval: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		total_proppant_per_perforated_interval: null,
		true_vertical_depth: null,
		well_name: 'TEST 1',
		well_number: '1H',
		well_type: 'OIL & GAS',
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		first_fluid_per_perforated_interval: null,
		first_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		mostRecentImportDesc: 'External API Import - 02/20/2023 05:30:53 PM',
		mostRecentImportType: 'api',
		mostRecentImportDate: '2023-02-20T17:30:53.917+0000',
		api10: '4247731025',
		api12: '424773102500',
		country: 'US',
		current_operator: 'ENERVEST',
		district: '03',
		target_formation: 'AUSTIN CHALK, GAS,AUSTIN CHALK-3',
		updatedAt: new Date('2023-06-15T17:49:36.950+0000'),
		section: null,
		undiscounted_roi: null,
		schemaVersion: 1,
		copied: false,
		last_prod_date_monthly: null,
		last_prod_date_daily: null,
		custom_string_11: 'abcasd124512515',
		custom_string_4: '',
		custom_string_0: '1000',
		aries_id: 'angeltest',
		phdwin_id: 'asdf',
		custom_number_9: 55,
		custom_number_19: 0,
		custom_date_6: '2022-11-11T06:00:00.000+0000',
		custom_number_7: 155555555513245550000000,
		custom_string_19: 'Pad 1',
		rig: 'testRig1',
	},
	{
		_id: new ObjectId('5e272d38b78910dd2a1bd6b5'),
		chosenID: 'postman-test',
		dataSource: 'internal',
		project: null,
		abstract: '70',
		api14: '42477309570000',
		basin: 'GULF COAST CENTRAL',
		chosenKeyID: 'ARIES ID',
		completion_end_date: '2007-06-30T00:00:00.000+0000',
		county: 'WASHINGTON (TX)',
		createdAt: new Date('2020-01-21T16:56:24.872+0000'),
		current_operator_alias: 'SANTANA EXPLORATION',
		dataPool: 'external',
		elevation: 278,
		elevation_type: 'KB',
		field: 'WILDCAT',
		first_fluid_volume: null,
		first_prod_date: '2022-12-15T03:00:00.000+0000',
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		first_prop_weight: null,
		footage_in_landing_zone: 1306.28,
		formation_thickness_mean: 323.92,
		geohash: '9v7kpbf43msv',
		ground_elevation: 241,
		has_daily: false,
		has_monthly: false,
		hole_direction: 'H',
		inptID: 'INPT.OR9rgMbDGw',
		landing_zone: 'Austin Chalk',
		lateral_length: 2712.93,
		lease_name: 'DUTY',
		location: {
			type: 'Point',
			coordinates: [-96.3363044, 30.2389115],
		},
		measured_depth: null,
		mostRecentImport: new ObjectId('5f1b6511a5e1e208ccb34baa'),
		percent_in_zone: 59.93,
		perf_lateral_length: null,
		play: 'EAGLEBINE',
		primary_product: 'OIL',
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		spud_date: '2005-12-03T00:00:00.000+0000',
		state: 'TX',
		status: 'SHUT-IN',
		surfaceLatitude: 30.2389115,
		surfaceLongitude: -96.3363044,
		survey: 'KUYKENDALL, A',
		toeLatitude: 30.2453923,
		toeLocation: {
			type: 'Point',
			coordinates: [-96.3405579, 30.2453923],
		},
		toeLongitude: -96.3405579,
		toe_in_landing_zone: 'Y',
		total_fluid_per_perforated_interval: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		total_proppant_per_perforated_interval: null,
		true_vertical_depth: 14360,
		well_name: 'TEST 2',
		well_number: '2H',
		well_type: 'OIL',
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		first_fluid_per_perforated_interval: null,
		first_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		mostRecentImportDesc: 'dperez alvarez20200724t184729',
		mostRecentImportType: 'api',
		mostRecentImportDate: '2020-07-24T22:47:45.941+0000',
		api10: '4247730957',
		api12: '424773095700',
		country: 'US',
		current_operator: 'SANTANA ENERGY SERVICES, LLC',
		distance_from_base_of_zone: 7.053,
		distance_from_top_of_zone: 316.868,
		district: '03',
		target_formation: 'AUSTIN CHALK-3',
		updatedAt: new Date('2023-06-15T17:49:36.950+0000'),
		section: null,
		undiscounted_roi: null,
		schemaVersion: 1,
		copied: false,
		last_prod_date_monthly: null,
		last_prod_date_daily: null,
		custom_string_15: 'Design 1',
		custom_string_19: 'Pad 1',
		aries_id: 'angeltest',
		month_produced: 0,
		cum_oil: 0.0,
		cum_gas: 0.0,
		cum_water: 0.0,
		cum_boe: 0.0,
		cum_gor: null,
		cum_mmcfge: 0.0,
		cum_oil_per_perforated_interval: null,
		cum_gas_per_perforated_interval: null,
		cum_water_per_perforated_interval: null,
		cum_boe_per_perforated_interval: null,
		cum_mmcfge_per_perforated_interval: null,
		first_6_oil: 0.0,
		first_6_gas: 0.0,
		first_6_water: 0.0,
		first_6_boe: 0.0,
		first_6_gor: null,
		first_6_mmcfge: 0.0,
		first_6_oil_per_perforated_interval: null,
		first_6_gas_per_perforated_interval: null,
		first_6_water_per_perforated_interval: null,
		first_6_boe_per_perforated_interval: null,
		first_6_mmcfge_per_perforated_interval: null,
		first_12_oil: 0.0,
		first_12_gas: 0.0,
		first_12_water: 0.0,
		first_12_boe: 0.0,
		first_12_gor: null,
		first_12_mmcfge: 0.0,
		first_12_oil_per_perforated_interval: null,
		first_12_gas_per_perforated_interval: null,
		first_12_water_per_perforated_interval: null,
		first_12_boe_per_perforated_interval: null,
		first_12_mmcfge_per_perforated_interval: null,
		last_12_oil: 0.0,
		last_12_gas: 0.0,
		last_12_water: 0.0,
		last_12_boe: 0.0,
		last_12_gor: null,
		last_12_mmcfge: 0.0,
		last_12_oil_per_perforated_interval: null,
		last_12_gas_per_perforated_interval: null,
		last_12_water_per_perforated_interval: null,
		last_12_boe_per_perforated_interval: null,
		last_12_mmcfge_per_perforated_interval: null,
		last_month_oil: 0.0,
		last_month_gas: 0.0,
		last_month_water: 0.0,
		last_month_boe: 0.0,
		last_month_gor: null,
		last_month_mmcfge: 0.0,
		last_month_oil_per_perforated_interval: null,
		last_month_gas_per_perforated_interval: null,
		last_month_water_per_perforated_interval: null,
		last_month_boe_per_perforated_interval: null,
		last_month_mmcfge_per_perforated_interval: null,
	},
	{
		_id: new ObjectId('5e272d39b78910dd2a1bd7d5'),
		chosenID: '42507000000000',
		dataSource: 'other',
		project: null,
		abstract: '3',
		api14: '42507000000000',
		chosenKeyID: 'API14',
		county: 'ZAVALA (TX)',
		createdAt: new Date('2020-01-21T16:56:25.022+0000'),
		current_operator_alias: 'CML EXPLORATION, LLC',
		dataPool: 'external',
		field: 'PEARSALL',
		first_fluid_volume: null,
		first_prod_date: '2022-12-15T03:00:00.000+0000',
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		first_prop_weight: null,
		ground_elevation: 936,
		has_daily: false,
		has_monthly: false,
		hole_direction: 'U',
		inptID: 'INPT.JNE6xtYFJd',
		lateral_length: null,
		lease_name: 'THOMPSON UNIT',
		location: {
			type: 'Point',
			coordinates: [100, 80],
		},
		measured_depth: 4470,
		mostRecentImport: new ObjectId('5e45ca59039b1dc2965de18d'),
		perf_lateral_length: 11000,
		primary_product: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		state: 'TX',
		status: 'INACTIVE',
		surfaceLatitude: 80,
		surfaceLongitude: 100,
		survey: 'AGUIERRE, N',
		toeLocation: {},
		total_fluid_per_perforated_interval: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		total_proppant_per_perforated_interval: null,
		true_vertical_depth: null,
		well_name: 'THOMPSON UNIT',
		well_number: '1',
		well_type: 'OIL',
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		first_fluid_per_perforated_interval: null,
		first_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		section: null,
		undiscounted_roi: null,
		schemaVersion: 1,
		copied: false,
		updatedAt: new Date('2023-06-30T01:06:14.813+0000'),
		last_prod_date_monthly: null,
		last_prod_date_daily: null,
		custom_string_11: '1002',
		custom_string_0: '1002',
		custom_string_15: 'Design 1',
		geohash: 'ynpp5e9cbbuk',
		custom_string_19: 'Pad 2',
		api10: '4247730123',
	},
	{
		_id: new ObjectId('64c41508bf1b9f08406fe8ec'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-5',
		pad_name: 'Well NEW projec tlevel-pad-5',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTZpgoduBJ0u',
		chosenID: 'INPTZpgoduBJ0u',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9f37876fe8ed'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-6',
		pad_name: 'Well NEW projec tlevel-pad-6',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTQt9rtkVuEn',
		chosenID: 'INPTQt9rtkVuEn',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9f45fe6fe8ee'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-7',
		pad_name: 'Well NEW projec tlevel-pad-7',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTOZKLm0i4Yx',
		chosenID: 'INPTOZKLm0i4Yx',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9f5a696fe8eb'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-4',
		pad_name: 'Well NEW projec tlevel-pad-4',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTckoShvGyQ9',
		chosenID: 'INPTckoShvGyQ9',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	// {
	// 	_id: new ObjectId('64c41508bf1b9f5ada6fe8e8'),
	// 	schemaVersion: 1,
	// 	dataPool: 'internal',
	// 	dataSource: 'internal',
	// 	project: new ObjectId('64c414c8bf1b9f62126fe78e'),
	// 	lateral_length: null,
	// 	perf_lateral_length: null,
	// 	primary_product: null,
	// 	true_vertical_depth: null,
	// 	copied: false,
	// 	first_fluid_volume: null,
	// 	first_prop_weight: null,
	// 	measured_depth: null,
	// 	surfaceLatitude: null,
	// 	surfaceLongitude: null,
	// 	first_proppant_per_fluid: null,
	// 	refrac_proppant_per_perforated_interval: null,
	// 	refrac_fluid_per_perforated_interval: null,
	// 	refrac_proppant_per_fluid: null,
	// 	total_fluid_volume: null,
	// 	total_prop_weight: null,
	// 	total_proppant_per_fluid: null,
	// 	first_proppant_per_perforated_interval: null,
	// 	first_fluid_per_perforated_interval: null,
	// 	total_fluid_per_perforated_interval: null,
	// 	total_proppant_per_perforated_interval: null,
	// 	first_prod_date_daily_calc: null,
	// 	first_prod_date_monthly_calc: null,
	// 	well_name: 'Well NEW projec tlevel-1',
	// 	pad_name: 'Well NEW projec tlevel-pad-1',
	// 	refrac_prop_weight: null,
	// 	refrac_fluid_volume: null,
	// 	total_additive_volume: null,
	// 	total_cluster_count: null,
	// 	total_stage_count: null,
	// 	has_daily: false,
	// 	has_monthly: false,
	// 	inptID: 'INPTpDcYxnZ6Ze',
	// 	chosenID: 'INPTpDcYxnZ6Ze',
	// 	chosenKeyID: 'inptID',
	// 	generic: true,
	// 	__v: 0,
	// 	createdAt: new Date('2023-07-28T19:20:40.051+0000'),
	// 	updatedAt: new Date('2023-07-28T19:20:40.051+0000'),
	// },
	{
		_id: new ObjectId('64c41508bf1b9f6cbe6fe8e9'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-2',
		pad_name: 'Well NEW projec tlevel-pad-2',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTig09B1Rsdx',
		chosenID: 'INPTig09B1Rsdx-MODIFIED', // modified chosenID
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9f6e0c6fe8ea'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-3',
		pad_name: 'Well NEW projec tlevel-pad-3',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPT3yWYk4oE3W',
		chosenID: 'INPT3yWYk4oE3W',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9f83ab6fe8ef'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-8',
		pad_name: 'Well NEW projec tlevel-pad-8',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTp8OaoG7D2G',
		chosenID: 'INPTp8OaoG7D2G',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9fb9e16fe8f0'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-9',
		pad_name: 'Well NEW projec tlevel-pad-9',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPThxg0AO77k3',
		chosenID: 'INPThxg0AO77k3',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41508bf1b9fe2fa6fe8f1'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c414c8bf1b9f62126fe78e'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-10',
		pad_name: 'Well NEW projec tlevel-pad-10',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTUWK5elJRxo',
		chosenID: 'INPTUWK5elJRxo',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:20:40.052+0000'),
		updatedAt: new Date('2023-07-28T19:20:40.052+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f056f6fecf2'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-6',
		pad_name: 'Well NEW projec tlevel-pad-6',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTZqc0KkJLbf',
		chosenID: 'INPTQt9rtkVuEn',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f13306fecf9'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-9',
		pad_name: 'Well NEW projec tlevel-pad-9',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPT6IJdFTAxA9',
		chosenID: 'INPThxg0AO77k3',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.358+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.358+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f1fb86fecfa'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-10',
		pad_name: 'Well NEW projec tlevel-pad-10',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTuTXNwwaZJM',
		chosenID: 'INPTUWK5elJRxo',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.358+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.358+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f22896fecf1'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-5',
		pad_name: 'Well NEW projec tlevel-pad-5',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTn7fZkxaqfO',
		chosenID: 'INPTZpgoduBJ0u',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f4d9c6fecf4'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-4',
		pad_name: 'Well NEW projec tlevel-pad-4',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTQezgHWjrmX',
		chosenID: 'INPTckoShvGyQ9',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f53ea6fecf8'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-8',
		pad_name: 'Well NEW projec tlevel-pad-8',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPT8fkHWSZyxJ',
		chosenID: 'INPTp8OaoG7D2G',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.358+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.358+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f595b6fecf7'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-3',
		pad_name: 'Well NEW projec tlevel-pad-3',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTlfInUqr8Vd',
		chosenID: 'INPT3yWYk4oE3W',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.358+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.358+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f6d076fecf3'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-7',
		pad_name: 'Well NEW projec tlevel-pad-7',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTjTITGrjPZW',
		chosenID: 'INPTOZKLm0i4Yx',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f72d36fecf6'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-2',
		pad_name: 'Well NEW projec tlevel-pad-2',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPTv3xaoIHFwS',
		chosenID: 'INPTig09B1Rsdx',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
	{
		_id: new ObjectId('64c41552bf1b9f824f6fecf5'),
		schemaVersion: 1,
		dataPool: 'internal',
		dataSource: 'internal',
		project: new ObjectId('64c41552bf1b9f4ce06fece2'),
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
		well_name: 'Well NEW projec tlevel-1',
		pad_name: 'Well NEW projec tlevel-pad-1',
		refrac_prop_weight: null,
		refrac_fluid_volume: null,
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		has_daily: false,
		has_monthly: false,
		inptID: 'INPT5TKgzGWI2W',
		chosenID: 'INPTpDcYxnZ6Ze',
		chosenKeyID: 'inptID',
		generic: true,
		__v: 0,
		createdAt: new Date('2023-07-28T19:21:54.357+0000'),
		updatedAt: new Date('2023-07-28T19:21:54.357+0000'),
	},
];

afterEach(async () => {
	await mongod.stop();
	await client.close();
});

describe('fix-copied-schedules', () => {
	beforeEach(async () => {
		({ db, mongod, client } = await setupDb());

		projects = db.collection('projects');
		schedules = db.collection('schedules');
		wells = db.collection('wells');
	});

	afterEach(async () => {
		await mongod.stop();
		await client.close();
	});

	it('up', async () => {
		await projects.insertMany(dbProjects);
		await schedules.insertMany(dbSchedules);
		await wells.insertMany(dbWells);

		await up({ db });
		await up({ db });

		const scheduleDocs = await schedules.find({}).toArray();
		expect(scheduleDocs).toEqual(fixedSchedules);
	});

	it('down', async () => {
		await projects.insertMany(dbProjects);
		await schedules.insertMany(fixedSchedules);
		await wells.insertMany(dbWells);

		await down({ db });
		await down({ db });

		const scheduleDocs = await schedules.find({}).toArray();
		expect(dbSchedules).toEqual(scheduleDocs);
	});
});
