WELL_HEADER_MAP = {
    'abstract': 'Abstract',
    'acre_spacing': 'Acre Same Zone Spacing',
    'allocation_type': 'Allocation Type',
    'api10': 'API 10',
    'api12': 'API 12',
    'api14': 'API 14',
    'aries_id': 'Aries ID',
    'azimuth': 'Azimuth',
    'basin': 'Basin',
    'block': 'Block',
    'casing_id': 'Casing ID',
    'choke_size': 'Choke Size',
    'chosenID': 'Chosen ID',
    'chosenKeyID': 'Chosen ID Key',
    'completion_design': 'Completion Design',
    'completion_end_date': 'Completion End Date',
    'completion_start_date': 'Completion Start Date',
    'copied': 'Copied Well',
    'country': 'Country',
    'county': 'County/Parish',
    'current_operator': 'Current Operator',
    'current_operator_alias': 'Current Operator Alias',
    'current_operator_code': 'Current Operator Code',
    'current_operator_ticker': 'Current Operator Ticker',
    'dataSource': 'Data Source',
    'dataPool': 'Data Pool',
    'date_rig_release': 'Date Rig Release',
    'distance_from_base_of_zone': 'Distance From Base Of Zone',
    'distance_from_top_of_zone': 'Distance From Top Of Zone',
    'district': 'District',
    'drill_end_date': 'Drill End Date',
    'drill_start_date': 'Drill Start Date',
    'elevation': 'Elevation',
    'elevation_type': 'Elevation Type',
    'field': 'Field',
    'first_additive_volume': 'Additive Vol (1st Job)',
    'first_cluster_count': 'Cluster Count  (1st Job)',
    'first_fluid_per_perforated_interval': 'Total Fluid/Perf LL (1st Job)',
    'first_fluid_volume': 'Total Fluid (1st Job)',
    'first_frac_vendor': 'Frac Vendor (1st Job)',
    'first_max_injection_pressure': 'Max Injection Pressure  (1st Job)',
    'first_max_injection_rate': 'Max Injection Rate  (1st Job)',
    'first_prod_date': 'First Prod Date',
    'first_prod_date_daily_calc': 'First Daily Prod Date Calc',
    'first_prod_date_monthly_calc': 'First Monthly Prod Date Calc',
    'first_prop_weight': 'Total Prop (1st Job)',
    'first_proppant_per_fluid': 'Total Prop/Fluid (1st Job)',
    'first_proppant_per_perforated_interval': 'Total Prop/Perf LL (1st Job)',
    'first_stage_count': 'Stage Count  (1st Job)',
    'first_test_flow_tbg_press': 'First Test Flow TBG Press',
    'first_test_gas_vol': 'First Test Gas Vol',
    'first_test_gor': 'First Test Gor',
    'first_test_oil_vol': 'First Test Oil Vol',
    'first_test_water_vol': 'First Test Water Vol',
    'first_treatment_type': 'Treatment Type (1st Job)',
    'flow_path': 'Flow Path',
    'fluid_type': 'Fluid Type',
    'footage_in_landing_zone': 'Footage In Landing Zone',
    'formation_thickness_mean': 'Formation Thickness Mean',
    'gas_gatherer': 'Gas Gatherer',
    'gas_specific_gravity': 'Gas Specific Gravity',
    'generic': 'Created Well',
    'ground_elevation': 'Ground Elevation',
    'has_daily': 'Has Daily Data',
    'has_monthly': 'Has Monthly Data',
    'hole_direction': 'Hole Direction',
    'hz_well_spacing_any_zone': 'Hz Well Spacing Any Zone',
    'hz_well_spacing_same_zone': 'Hz Well Spacing Same Zone',
    'initial_respress': 'Initial Respress',
    'initial_restemp': 'Initial Restemp',
    'inptID': 'INPT ID',
    'landing_zone': 'Landing Zone',
    'landing_zone_base': 'Landing Zone Base',
    'landing_zone_top': 'Landing Zone Top',
    'lateral_length': 'Lateral Length',
    'lease_name': 'Lease Name',
    'lease_number': 'Lease Number',
    'lower_perforation': 'Lower Perforation',
    'matrix_permeability': 'Matrix Permeability',
    'measured_depth': 'Measured Depth',
    'num_treatment_records': 'Num Treatment Records',
    'oil_api_gravity': 'Oil API Gravity',
    'oil_gatherer': 'Oil Gatherer',
    'oil_specific_gravity': 'Oil Specific Gravity',
    'pad_name': 'Pad Name',
    'parent_child_any_zone': 'Parent Child Any Zone',
    'parent_child_same_zone': 'Parent Child Same Zone',
    'percent_in_zone': 'Percent In Zone',
    'perf_lateral_length': 'Perf Lateral Length',
    'permit_date': 'Permit Date',
    'phdwin_id': 'PhdWin ID',
    'play': 'Play',
    'porosity': 'Porosity',
    'previous_operator': 'Previous Operator',
    'previous_operator_alias': 'Previous Operator Alias',
    'previous_operator_code': 'Previous Operator Code',
    'previous_operator_ticker': 'Previous Operator Ticker',
    'primary_product': 'Primary Product',
    'production_method': 'Production Method',
    'proppant_mesh_size': 'Prop Mesh Size',
    'proppant_type': 'Prop Type',
    'range': 'Range',
    'recovery_method': 'Recovery Method',
    'refrac_additive_volume': 'Additive Vol (Refrac)',
    'refrac_cluster_count': 'Cluster Count (Refrac)',
    'refrac_date': 'Refrac Date',
    'refrac_fluid_per_perforated_interval': 'Total Fluid/Perf LL (Refrac)',
    'refrac_fluid_volume': 'Total Fluid (Refrac)',
    'refrac_frac_vendor': 'Frac Vendor (Refrac)',
    'refrac_max_injection_pressure': 'Max Injection Pressure (Refrac)',
    'refrac_max_injection_rate': 'Max Injection Rate (Refrac)',
    'refrac_prop_weight': 'Total Prop (Refrac)',
    'refrac_proppant_per_fluid': 'Total Prop/Fluid (Refrac)',
    'refrac_proppant_per_perforated_interval': 'Total Prop/Perf LL (Refrac)',
    'refrac_stage_count': 'Stage Count (Refrac)',
    'refrac_treatment_type': 'Treatment Type (Refrac)',
    'rig': 'Rig Name',
    'section': 'Section',
    'sg': 'Sg',
    'so': 'So',
    'spud_date': 'Spud Date',
    'stage_spacing': 'Stage Spacing',
    'state': 'State',
    'status': 'Status',
    'subplay': 'Subplay',
    'surfaceLatitude': 'Surface Latitude',
    'surfaceLongitude': 'Surface Longitude',
    'survey': 'Survey',
    'sw': 'Sw',
    'target_formation': 'Target Formation',
    'thickness': 'Thickness',
    'til': 'TIL',
    'toeLatitude': 'Toe Latitude',
    'toeLongitude': 'Toe Longitude',
    'toe_in_landing_zone': 'Toe In Landing Zone',
    'toe_up': 'Toe Up',
    'total_additive_volume': 'Additive Vol (All Jobs)',
    'total_cluster_count': 'Total Cluster (All Jobs)',
    'total_fluid_per_perforated_interval': 'Total Fluid/Perf LL (All Jobs)',
    'total_fluid_volume': 'Total Fluid (All Jobs)',
    'total_prop_weight': 'Total Prop (All Jobs)',
    'total_proppant_per_fluid': 'Total Prop/Fluid (All Jobs)',
    'total_proppant_per_perforated_interval': 'Total Prop/Perf LL (All Jobs)',
    'total_stage_count': 'Total Stages (All Jobs)',
    'township': 'Township',
    'true_vertical_depth': 'True Vertical Depth',
    'tubing_depth': 'Tubing Depth',
    'tubing_id': 'Tubing ID',
    'type_curve_area': 'Type Curve Area',
    'upper_perforation': 'Upper Perforation',
    'vt_well_spacing_any_zone': 'Vt Well Spacing Any Zone',
    'vt_well_spacing_same_zone': 'Vt Well Spacing Same Zone',
    'well_name': 'Well Name',
    'well_number': 'Well Number',
    'well_type': 'Well Type',
    'mostRecentImportDesc': 'Import Name'
}
