[tool.poetry]
name = "combocurve"
version = "0.1.0"
description = ""
authors = ["Maxum Smith <m.smith@combocurve.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
poethepoet = "^0.13.1"
pytest = "7.4.2"
numpy = "1.24.2"
pandas = "1.3.5"
python-dateutil = "2.8.2"
pymongo = "3.13.0"
xlrd = "1.2.0"
pydantic = "1.10.12"
flask = "2.3.3"
polars = "0.15.18"
requests = "2.31.0"
mongomock = "4.1.2"
launchdarkly-server-sdk = "8.1.4"
scipy = "1.10.0"
mongoengine = "0.27.0"
google-cloud-secret-manager = "2.16.2"
babel = "2.12.1"
pusher = "3.3.2"
pyproj = "3.5.0"
deepdiff = "=5.8.1"
grpc-interceptor = "0.15.1"
pytest-mock-resources = "2.6.12"
pyarrow = "10.0.1"
ortools = "9.4.1874"
python-on-whales = "0.60.1"
pytest-mock = "3.10.0"

[tool.poe.tasks]
test = "pytest"
test-cov = "pytest --cov=."
test-cov-html = "pytest --cov=. --cov-report html"
test-cov-ci = "pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=."
test-unit = "pytest -m unittest"
test-unit-watch = "ptw --runner \"poetry run poe test-unit\""
test-integ = "pytest -m integtest"
test-integ-watch = "ptw --runner \"poetry run poe test-integ\""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
