import { merge } from 'lodash';
import { Types } from 'mongoose';

import {
	filterableReadDbFields,
	getApiDbSort,
	getApiReadDbFilters,
	IApiSort,
	IField,
	IReadFieldOptions,
	readDbField,
	sortableDbFields,
} from '@src/api/v1/fields';
import { IEconRunData, OneLinerData, ReservesCategory } from '@src/models/econ/econ-run-data';
import { IFieldDefinition, NUMBER_FIELD, OBJECT_ID_FIELD, STRING_FIELD } from '@src/helpers/fields';
import { IFilter, ISort } from '@src/helpers/mongo-queries';
import { ApiQueryFilters } from '@src/helpers/fields/field-definition';
import { BaseProjectResolved } from '@src/api/v1/projects/fields';
import { IEconRun } from '@src/models/econ/econ-runs';
import { OpenApiDataType } from '@src/helpers/fields/data-type';

export const READ_RECORD_LIMIT = 200;

export type ApiOneLinerKey = keyof typeof API_ONE_LINER_FIELDS;

type TypeOfOneLinerField<FT> = FT extends OneLinerField<OneLinerData, infer T> ? T : never;

export type ApiOneLiner = {
	[key in ApiOneLinerKey]?: TypeOfOneLinerField<(typeof API_ONE_LINER_FIELDS)[key]>;
};

type OneLinerField<T extends OneLinerData, TField> = IField<T, TField>;

const readFieldOneLiner = <K extends keyof OneLinerData>(
	key: K,
	definition: IFieldDefinition<OneLinerData[K]['value']>,
): OneLinerField<OneLinerData, OneLinerData[K]['value'] | undefined> => {
	return {
		...definition,
		read: (oneLiner) => oneLiner[key]?.value,
	};
};

const API_ONE_LINER_FIELDS = {
	abandonmentDate: readFieldOneLiner('abandonment_date', STRING_FIELD),
	adValoremTax: readFieldOneLiner('ad_valorem_tax', NUMBER_FIELD),
	afterIncomeTaxCashFlow: readFieldOneLiner('after_income_tax_cash_flow', NUMBER_FIELD),
	applyNormalization: readFieldOneLiner('apply_normalization', STRING_FIELD),
	asOfDate: readFieldOneLiner('as_of_date', STRING_FIELD),
	beforeIncomeTaxCashFlow: readFieldOneLiner('before_income_tax_cash_flow', NUMBER_FIELD),
	consecutiveNegativeCashFlowMonthCount: readFieldOneLiner(
		'consecutive_negative_cash_flow_month_count',
		NUMBER_FIELD,
	),
	consecutiveNegativeCashFlowMonths: readFieldOneLiner('consecutive_negative_cash_flow_months', STRING_FIELD),
	depreciation: readFieldOneLiner('depreciation', NUMBER_FIELD),
	discountDate: readFieldOneLiner('discount_date', STRING_FIELD),
	discountTableCashFlow_1: readFieldOneLiner('discount_table_cash_flow_1', NUMBER_FIELD),
	discountTableCashFlow_10: readFieldOneLiner('discount_table_cash_flow_10', NUMBER_FIELD),
	discountTableCashFlow_11: readFieldOneLiner('discount_table_cash_flow_11', NUMBER_FIELD),
	discountTableCashFlow_12: readFieldOneLiner('discount_table_cash_flow_12', NUMBER_FIELD),
	discountTableCashFlow_13: readFieldOneLiner('discount_table_cash_flow_13', NUMBER_FIELD),
	discountTableCashFlow_14: readFieldOneLiner('discount_table_cash_flow_14', NUMBER_FIELD),
	discountTableCashFlow_15: readFieldOneLiner('discount_table_cash_flow_15', NUMBER_FIELD),
	discountTableCashFlow_16: readFieldOneLiner('discount_table_cash_flow_16', NUMBER_FIELD),
	discountTableCashFlow_2: readFieldOneLiner('discount_table_cash_flow_2', NUMBER_FIELD),
	discountTableCashFlow_3: readFieldOneLiner('discount_table_cash_flow_3', NUMBER_FIELD),
	discountTableCashFlow_4: readFieldOneLiner('discount_table_cash_flow_4', NUMBER_FIELD),
	discountTableCashFlow_5: readFieldOneLiner('discount_table_cash_flow_5', NUMBER_FIELD),
	discountTableCashFlow_6: readFieldOneLiner('discount_table_cash_flow_6', NUMBER_FIELD),
	discountTableCashFlow_7: readFieldOneLiner('discount_table_cash_flow_7', NUMBER_FIELD),
	discountTableCashFlow_8: readFieldOneLiner('discount_table_cash_flow_8', NUMBER_FIELD),
	discountTableCashFlow_9: readFieldOneLiner('discount_table_cash_flow_9', NUMBER_FIELD),
	dripCondensateGatheringExpense: readFieldOneLiner('drip_condensate_gathering_expense', NUMBER_FIELD),
	dripCondensateMarketingExpense: readFieldOneLiner('drip_condensate_marketing_expense', NUMBER_FIELD),
	dripCondensateOtherExpense: readFieldOneLiner('drip_condensate_other_expense', NUMBER_FIELD),
	dripCondensatePrice: readFieldOneLiner('drip_condensate_price', NUMBER_FIELD),
	dripCondensateProcessingExpense: readFieldOneLiner('drip_condensate_processing_expense', NUMBER_FIELD),
	dripCondensateRevenue: readFieldOneLiner('drip_condensate_revenue', NUMBER_FIELD),
	dripCondensateSeveranceTax: readFieldOneLiner('drip_condensate_severance_tax', NUMBER_FIELD),
	dripCondensateShrunkEur: readFieldOneLiner('drip_condensate_shrunk_eur', NUMBER_FIELD),
	dripCondensateTransportationExpense: readFieldOneLiner('drip_condensate_transportation_expense', NUMBER_FIELD),
	dripCondensateYield: readFieldOneLiner('drip_condensate_yield', NUMBER_FIELD),
	dripCondensateBoeConversion: readFieldOneLiner('drip_condensate_boe_conversion', NUMBER_FIELD),
	dripCondensateDifferentials1: readFieldOneLiner('drip_condensate_differentials_1', NUMBER_FIELD),
	dripCondensateDifferentials2: readFieldOneLiner('drip_condensate_differentials_2', NUMBER_FIELD),
	dripCondensateRisk: readFieldOneLiner('drip_condensate_risk', NUMBER_FIELD),
	dripCondensateShrunkEurOverPll: readFieldOneLiner('drip_condensate_shrunk_eur_over_pll', NUMBER_FIELD),
	dryGasBoeConversion: readFieldOneLiner('dry_gas_boe_conversion', NUMBER_FIELD),
	econFirstProdDate: readFieldOneLiner('econ_first_production_date', STRING_FIELD),
	federalIncomeTax: readFieldOneLiner('federal_income_tax', NUMBER_FIELD),
	firstConsecutiveNegativeCashFlowMonth: readFieldOneLiner(
		'first_consecutive_negative_cash_flow_month',
		STRING_FIELD,
	),
	firstDiscountCashFlow: readFieldOneLiner('first_discount_cash_flow', NUMBER_FIELD),
	firstDiscountRoi: readFieldOneLiner('first_discount_roi', NUMBER_FIELD),
	firstDiscountNetIncome: readFieldOneLiner('first_discount_net_income', NUMBER_FIELD),
	firstDiscountPayout: readFieldOneLiner('first_discount_payout', STRING_FIELD),
	firstDiscountPayoutDuration: readFieldOneLiner('first_discount_payout_duration', NUMBER_FIELD),
	firstDiscountRoiUndiscountedCapex: readFieldOneLiner('first_discount_roi_undiscounted_capex', NUMBER_FIELD),
	firstDiscountedCapex: readFieldOneLiner('first_discounted_capex', NUMBER_FIELD),
	fiveYearGrossBoeSalesVolume: readFieldOneLiner('five_year_gross_BOE_sales_volume', NUMBER_FIELD),
	fiveYearGrossBoeWellHeadVolume: readFieldOneLiner('five_year_gross_BOE_well_head_volume', NUMBER_FIELD),
	fiveYearGrossDripCondensateSalesVolume: readFieldOneLiner(
		'five_year_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	fiveYearGrossGasSalesVolume: readFieldOneLiner('five_year_gross_gas_sales_volume', NUMBER_FIELD),
	fiveYearGrossGasWellHeadVolume: readFieldOneLiner('five_year_gross_gas_well_head_volume', NUMBER_FIELD),
	fiveYearGrossNglSalesVolume: readFieldOneLiner('five_year_gross_ngl_sales_volume', NUMBER_FIELD),
	fiveYearGrossOilSalesVolume: readFieldOneLiner('five_year_gross_oil_sales_volume', NUMBER_FIELD),
	fiveYearGrossOilWellHeadVolume: readFieldOneLiner('five_year_gross_oil_well_head_volume', NUMBER_FIELD),
	fiveYearGrossWaterWellHeadVolume: readFieldOneLiner('five_year_gross_water_well_head_volume', NUMBER_FIELD),
	fiveYearNetBoeSalesVolume: readFieldOneLiner('five_year_net_BOE_sales_volume', NUMBER_FIELD),
	fiveYearNetDripCondensateSalesVolume: readFieldOneLiner('five_year_net_drip_condensate_sales_volume', NUMBER_FIELD),
	fiveYearNetGasSalesVolume: readFieldOneLiner('five_year_net_gas_sales_volume', NUMBER_FIELD),
	fiveYearNetNglSalesVolume: readFieldOneLiner('five_year_net_ngl_sales_volume', NUMBER_FIELD),
	fiveYearNetOilSalesVolume: readFieldOneLiner('five_year_net_oil_sales_volume', NUMBER_FIELD),
	fiveYearWiBoeSalesVolume: readFieldOneLiner('five_year_wi_BOE_sales_volume', NUMBER_FIELD),
	fiveYearWiDripCondensateSalesVolume: readFieldOneLiner('five_year_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	fiveYearWiGasSalesVolume: readFieldOneLiner('five_year_wi_gas_sales_volume', NUMBER_FIELD),
	fiveYearWiNglSalesVolume: readFieldOneLiner('five_year_wi_ngl_sales_volume', NUMBER_FIELD),
	fiveYearWiOilSalesVolume: readFieldOneLiner('five_year_wi_oil_sales_volume', NUMBER_FIELD),
	forecastName: readFieldOneLiner('forecast_name', STRING_FIELD),
	gasAssignedPSeriesFirstSegmentB: readFieldOneLiner('gas_assigned_p_series_first_segment_b', NUMBER_FIELD),
	gasAssignedPSeriesFirstSegmentD1Nominal: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_d1_nominal',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesFirstSegmentDiEffSec: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesFirstSegmentEndDate: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_end_date',
		STRING_FIELD,
	),
	gasAssignedPSeriesFirstSegmentQEnd: readFieldOneLiner('gas_assigned_p_series_first_segment_q_end', NUMBER_FIELD),
	gasAssignedPSeriesFirstSegmentQStart: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_q_start',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesFirstSegmentSegmentType: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_segment_type',
		STRING_FIELD,
	),
	gasAssignedPSeriesFirstSegmentStartDate: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_start_date',
		STRING_FIELD,
	),
	gasAssignedPSeriesFirstSegmentSwDate: readFieldOneLiner(
		'gas_assigned_p_series_first_segment_sw_date',
		STRING_FIELD,
	),
	gasAssignedPSeriesLastSegmentB: readFieldOneLiner('gas_assigned_p_series_last_segment_b', NUMBER_FIELD),
	gasAssignedPSeriesLastSegmentD1Nominal: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_d1_nominal',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesLastSegmentDiEffSec: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesLastSegmentEndDate: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_end_date',
		STRING_FIELD,
	),
	gasAssignedPSeriesLastSegmentQEnd: readFieldOneLiner('gas_assigned_p_series_last_segment_q_end', NUMBER_FIELD),
	gasAssignedPSeriesLastSegmentQStart: readFieldOneLiner('gas_assigned_p_series_last_segment_q_start', NUMBER_FIELD),
	gasAssignedPSeriesLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	gasAssignedPSeriesLastSegmentSegmentType: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_segment_type',
		STRING_FIELD,
	),
	gasAssignedPSeriesLastSegmentStartDate: readFieldOneLiner(
		'gas_assigned_p_series_last_segment_start_date',
		STRING_FIELD,
	),
	gasAssignedPSeriesLastSegmentSwDate: readFieldOneLiner('gas_assigned_p_series_last_segment_sw_date', STRING_FIELD),
	gasBestFitFirstSegmentB: readFieldOneLiner('gas_best_fit_first_segment_b', NUMBER_FIELD),
	gasBestFitFirstSegmentD1Nominal: readFieldOneLiner('gas_best_fit_first_segment_d1_nominal', NUMBER_FIELD),
	gasBestFitFirstSegmentDiEffSec: readFieldOneLiner('gas_best_fit_first_segment_di_eff_sec', NUMBER_FIELD),
	gasBestFitFirstSegmentEndDate: readFieldOneLiner('gas_best_fit_first_segment_end_date', STRING_FIELD),
	gasBestFitFirstSegmentQEnd: readFieldOneLiner('gas_best_fit_first_segment_q_end', NUMBER_FIELD),
	gasBestFitFirstSegmentQStart: readFieldOneLiner('gas_best_fit_first_segment_q_start', NUMBER_FIELD),
	gasBestFitFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'gas_best_fit_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	gasBestFitFirstSegmentSegmentType: readFieldOneLiner('gas_best_fit_first_segment_segment_type', STRING_FIELD),
	gasBestFitFirstSegmentStartDate: readFieldOneLiner('gas_best_fit_first_segment_start_date', STRING_FIELD),
	gasBestFitFirstSegmentSwDate: readFieldOneLiner('gas_best_fit_first_segment_sw_date', STRING_FIELD),
	gasBestFitLastSegmentB: readFieldOneLiner('gas_best_fit_last_segment_b', NUMBER_FIELD),
	gasBestFitLastSegmentD1Nominal: readFieldOneLiner('gas_best_fit_last_segment_d1_nominal', NUMBER_FIELD),
	gasBestFitLastSegmentDiEffSec: readFieldOneLiner('gas_best_fit_last_segment_di_eff_sec', NUMBER_FIELD),
	gasBestFitLastSegmentEndDate: readFieldOneLiner('gas_best_fit_last_segment_end_date', STRING_FIELD),
	gasBestFitLastSegmentQEnd: readFieldOneLiner('gas_best_fit_last_segment_q_end', NUMBER_FIELD),
	gasBestFitLastSegmentQStart: readFieldOneLiner('gas_best_fit_last_segment_q_start', NUMBER_FIELD),
	gasBestFitLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'gas_best_fit_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	gasBestFitLastSegmentSegmentType: readFieldOneLiner('gas_best_fit_last_segment_segment_type', STRING_FIELD),
	gasBestFitLastSegmentStartDate: readFieldOneLiner('gas_best_fit_last_segment_start_date', STRING_FIELD),
	gasBestFitLastSegmentSwDate: readFieldOneLiner('gas_best_fit_last_segment_sw_date', STRING_FIELD),
	gasBreakeven: readFieldOneLiner('gas_breakeven', NUMBER_FIELD),
	gasFlare: readFieldOneLiner('gas_flare', NUMBER_FIELD),
	gasGatheringExpense: readFieldOneLiner('gas_gathering_expense', NUMBER_FIELD),
	gasLoss: readFieldOneLiner('gas_loss', NUMBER_FIELD),
	gasMarketingExpense: readFieldOneLiner('gas_marketing_expense', NUMBER_FIELD),
	gasOtherExpense: readFieldOneLiner('gas_other_expense', NUMBER_FIELD),
	gasP10FirstSegmentB: readFieldOneLiner('gas_p10_first_segment_b', NUMBER_FIELD),
	gasP10FirstSegmentD1Nominal: readFieldOneLiner('gas_p10_first_segment_d1_nominal', NUMBER_FIELD),
	gasP10FirstSegmentDiEffSec: readFieldOneLiner('gas_p10_first_segment_di_eff_sec', NUMBER_FIELD),
	gasP10FirstSegmentEndDate: readFieldOneLiner('gas_p10_first_segment_end_date', STRING_FIELD),
	gasP10FirstSegmentQEnd: readFieldOneLiner('gas_p10_first_segment_q_end', NUMBER_FIELD),
	gasP10FirstSegmentQStart: readFieldOneLiner('gas_p10_first_segment_q_start', NUMBER_FIELD),
	gasP10FirstSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p10_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP10FirstSegmentSegmentType: readFieldOneLiner('gas_p10_first_segment_segment_type', STRING_FIELD),
	gasP10FirstSegmentStartDate: readFieldOneLiner('gas_p10_first_segment_start_date', STRING_FIELD),
	gasP10FirstSegmentSwDate: readFieldOneLiner('gas_p10_first_segment_sw_date', STRING_FIELD),
	gasP10LastSegmentB: readFieldOneLiner('gas_p10_last_segment_b', NUMBER_FIELD),
	gasP10LastSegmentD1Nominal: readFieldOneLiner('gas_p10_last_segment_d1_nominal', NUMBER_FIELD),
	gasP10LastSegmentDiEffSec: readFieldOneLiner('gas_p10_last_segment_di_eff_sec', NUMBER_FIELD),
	gasP10LastSegmentEndDate: readFieldOneLiner('gas_p10_last_segment_end_date', STRING_FIELD),
	gasP10LastSegmentQEnd: readFieldOneLiner('gas_p10_last_segment_q_end', NUMBER_FIELD),
	gasP10LastSegmentQStart: readFieldOneLiner('gas_p10_last_segment_q_start', NUMBER_FIELD),
	gasP10LastSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p10_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP10LastSegmentSegmentType: readFieldOneLiner('gas_p10_last_segment_segment_type', STRING_FIELD),
	gasP10LastSegmentStartDate: readFieldOneLiner('gas_p10_last_segment_start_date', STRING_FIELD),
	gasP10LastSegmentSwDate: readFieldOneLiner('gas_p10_last_segment_sw_date', STRING_FIELD),
	gasP50FirstSegmentB: readFieldOneLiner('gas_p50_first_segment_b', NUMBER_FIELD),
	gasP50FirstSegmentD1Nominal: readFieldOneLiner('gas_p50_first_segment_d1_nominal', NUMBER_FIELD),
	gasP50FirstSegmentDiEffSec: readFieldOneLiner('gas_p50_first_segment_di_eff_sec', NUMBER_FIELD),
	gasP50FirstSegmentEndDate: readFieldOneLiner('gas_p50_first_segment_end_date', STRING_FIELD),
	gasP50FirstSegmentQEnd: readFieldOneLiner('gas_p50_first_segment_q_end', NUMBER_FIELD),
	gasP50FirstSegmentQStart: readFieldOneLiner('gas_p50_first_segment_q_start', NUMBER_FIELD),
	gasP50FirstSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p50_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP50FirstSegmentSegmentType: readFieldOneLiner('gas_p50_first_segment_segment_type', STRING_FIELD),
	gasP50FirstSegmentStartDate: readFieldOneLiner('gas_p50_first_segment_start_date', STRING_FIELD),
	gasP50FirstSegmentSwDate: readFieldOneLiner('gas_p50_first_segment_sw_date', STRING_FIELD),
	gasP50LastSegmentB: readFieldOneLiner('gas_p50_last_segment_b', NUMBER_FIELD),
	gasP50LastSegmentD1Nominal: readFieldOneLiner('gas_p50_last_segment_d1_nominal', NUMBER_FIELD),
	gasP50LastSegmentDiEffSec: readFieldOneLiner('gas_p50_last_segment_di_eff_sec', NUMBER_FIELD),
	gasP50LastSegmentEndDate: readFieldOneLiner('gas_p50_last_segment_end_date', STRING_FIELD),
	gasP50LastSegmentQEnd: readFieldOneLiner('gas_p50_last_segment_q_end', NUMBER_FIELD),
	gasP50LastSegmentQStart: readFieldOneLiner('gas_p50_last_segment_q_start', NUMBER_FIELD),
	gasP50LastSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p50_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP50LastSegmentSegmentType: readFieldOneLiner('gas_p50_last_segment_segment_type', STRING_FIELD),
	gasP50LastSegmentStartDate: readFieldOneLiner('gas_p50_last_segment_start_date', STRING_FIELD),
	gasP50LastSegmentSwDate: readFieldOneLiner('gas_p50_last_segment_sw_date', STRING_FIELD),
	gasP90FirstSegmentB: readFieldOneLiner('gas_p90_first_segment_b', NUMBER_FIELD),
	gasP90FirstSegmentD1Nominal: readFieldOneLiner('gas_p90_first_segment_d1_nominal', NUMBER_FIELD),
	gasP90FirstSegmentDiEffSec: readFieldOneLiner('gas_p90_first_segment_di_eff_sec', NUMBER_FIELD),
	gasP90FirstSegmentEndDate: readFieldOneLiner('gas_p90_first_segment_end_date', STRING_FIELD),
	gasP90FirstSegmentQEnd: readFieldOneLiner('gas_p90_first_segment_q_end', NUMBER_FIELD),
	gasP90FirstSegmentQStart: readFieldOneLiner('gas_p90_first_segment_q_start', NUMBER_FIELD),
	gasP90FirstSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p90_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP90FirstSegmentSegmentType: readFieldOneLiner('gas_p90_first_segment_segment_type', STRING_FIELD),
	gasP90FirstSegmentStartDate: readFieldOneLiner('gas_p90_first_segment_start_date', STRING_FIELD),
	gasP90FirstSegmentSwDate: readFieldOneLiner('gas_p90_first_segment_sw_date', STRING_FIELD),
	gasP90LastSegmentB: readFieldOneLiner('gas_p90_last_segment_b', NUMBER_FIELD),
	gasP90LastSegmentD1Nominal: readFieldOneLiner('gas_p90_last_segment_d1_nominal', NUMBER_FIELD),
	gasP90LastSegmentDiEffSec: readFieldOneLiner('gas_p90_last_segment_di_eff_sec', NUMBER_FIELD),
	gasP90LastSegmentEndDate: readFieldOneLiner('gas_p90_last_segment_end_date', STRING_FIELD),
	gasP90LastSegmentQEnd: readFieldOneLiner('gas_p90_last_segment_q_end', NUMBER_FIELD),
	gasP90LastSegmentQStart: readFieldOneLiner('gas_p90_last_segment_q_start', NUMBER_FIELD),
	gasP90LastSegmentRealizedDSwEffSec: readFieldOneLiner('gas_p90_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	gasP90LastSegmentSegmentType: readFieldOneLiner('gas_p90_last_segment_segment_type', STRING_FIELD),
	gasP90LastSegmentStartDate: readFieldOneLiner('gas_p90_last_segment_start_date', STRING_FIELD),
	gasP90LastSegmentSwDate: readFieldOneLiner('gas_p90_last_segment_sw_date', STRING_FIELD),
	gasPrice: readFieldOneLiner('gas_price', NUMBER_FIELD),
	gasProcessingExpense: readFieldOneLiner('gas_processing_expense', NUMBER_FIELD),
	gasRevenue: readFieldOneLiner('gas_revenue', NUMBER_FIELD),
	gasSeveranceTax: readFieldOneLiner('gas_severance_tax', NUMBER_FIELD),
	gasShrinkage: readFieldOneLiner('gas_shrinkage', NUMBER_FIELD),
	gasShrunkEur: readFieldOneLiner('gas_shrunk_eur', NUMBER_FIELD),
	gasTransportationExpense: readFieldOneLiner('gas_transportation_expense', NUMBER_FIELD),
	gasWellHeadEur: readFieldOneLiner('gas_well_head_eur', NUMBER_FIELD),
	gasDifferentials1: readFieldOneLiner('gas_differentials_1', NUMBER_FIELD),
	gasDifferentials2: readFieldOneLiner('gas_differentials_2', NUMBER_FIELD),
	gasProductionAsOfDate: readFieldOneLiner('gas_production_as_of_date', NUMBER_FIELD),
	gasRisk: readFieldOneLiner('gas_risk', NUMBER_FIELD),
	gasShrunkEurOverPll: readFieldOneLiner('gas_shrunk_eur_over_pll', NUMBER_FIELD),
	gasTcRisk: readFieldOneLiner('gas_tc_risk', NUMBER_FIELD),
	gasWellHeadEurOverPll: readFieldOneLiner('gas_well_head_eur_over_pll', NUMBER_FIELD),
	grossBoeSalesVolume: readFieldOneLiner('gross_boe_sales_volume', NUMBER_FIELD),
	grossBoeWellHeadVolume: readFieldOneLiner('gross_boe_well_head_volume', NUMBER_FIELD),
	grossDripCondensateSalesVolume: readFieldOneLiner('gross_drip_condensate_sales_volume', NUMBER_FIELD),
	grossGasSalesVolume: readFieldOneLiner('gross_gas_sales_volume', NUMBER_FIELD),
	grossGasWellHeadVolume: readFieldOneLiner('gross_gas_well_head_volume', NUMBER_FIELD),
	grossNglSalesVolume: readFieldOneLiner('gross_ngl_sales_volume', NUMBER_FIELD),
	grossOilSalesVolume: readFieldOneLiner('gross_oil_sales_volume', NUMBER_FIELD),
	grossOilWellHeadVolume: readFieldOneLiner('gross_oil_well_head_volume', NUMBER_FIELD),
	grossWaterWellHeadVolume: readFieldOneLiner('gross_water_well_head_volume', NUMBER_FIELD),
	grossMcfeSalesVolume: readFieldOneLiner('gross_mcfe_sales_volume', NUMBER_FIELD),
	grossMcfeWellHeadVolume: readFieldOneLiner('gross_mcfe_well_head_volume', NUMBER_FIELD),
	inputDripCondensatePrice: readFieldOneLiner('input_drip_condensate_price', NUMBER_FIELD),
	inputGasPrice: readFieldOneLiner('input_gas_price', NUMBER_FIELD),
	inputNglPrice: readFieldOneLiner('input_ngl_price', NUMBER_FIELD),
	inputOilPrice: readFieldOneLiner('input_oil_price', NUMBER_FIELD),
	intangibleAbandonment: readFieldOneLiner('intangible_abandonment', NUMBER_FIELD),
	intangibleAppraisal: readFieldOneLiner('intangible_appraisal', NUMBER_FIELD),
	intangibleArtificialLift: readFieldOneLiner('intangible_artificial_lift', NUMBER_FIELD),
	intangibleCompletion: readFieldOneLiner('intangible_completion', NUMBER_FIELD),
	intangibleDevelopment: readFieldOneLiner('intangible_development', NUMBER_FIELD),
	intangibleDrilling: readFieldOneLiner('intangible_drilling', NUMBER_FIELD),
	intangibleExploration: readFieldOneLiner('intangible_exploration', NUMBER_FIELD),
	intangibleFacilities: readFieldOneLiner('intangible_facilities', NUMBER_FIELD),
	intangibleLeasehold: readFieldOneLiner('intangible_leasehold', NUMBER_FIELD),
	intangibleLegal: readFieldOneLiner('intangible_legal', NUMBER_FIELD),
	intangibleOtherInvestment: readFieldOneLiner('intangible_other_investment', NUMBER_FIELD),
	intangiblePad: readFieldOneLiner('intangible_pad', NUMBER_FIELD),
	intangiblePipelines: readFieldOneLiner('intangible_pipelines', NUMBER_FIELD),
	intangibleSalvage: readFieldOneLiner('intangible_salvage', NUMBER_FIELD),
	intangibleWaterline: readFieldOneLiner('intangible_waterline', NUMBER_FIELD),
	intangibleWorkover: readFieldOneLiner('intangible_workover', NUMBER_FIELD),
	irr: readFieldOneLiner('irr', NUMBER_FIELD),
	lastConsecutiveNegativeCashFlowMonth: readFieldOneLiner('last_consecutive_negative_cash_flow_month', STRING_FIELD),
	lastOneMonthBoeAverage: readFieldOneLiner('last_one_month_boe_average', NUMBER_FIELD),
	lastOneMonthGasAverage: readFieldOneLiner('last_one_month_gas_average', NUMBER_FIELD),
	lastOneMonthMcfeAverage: readFieldOneLiner('last_one_month_mcfe_average', NUMBER_FIELD),
	lastOneMonthOilAverage: readFieldOneLiner('last_one_month_oil_average', NUMBER_FIELD),
	lastOneMonthWaterAverage: readFieldOneLiner('last_one_month_water_average', NUMBER_FIELD),
	lastThreeMonthBoeAverage: readFieldOneLiner('last_three_month_boe_average', NUMBER_FIELD),
	lastThreeMonthGasAverage: readFieldOneLiner('last_three_month_gas_average', NUMBER_FIELD),
	lastThreeMonthMcfeAverage: readFieldOneLiner('last_three_month_mcfe_average', NUMBER_FIELD),
	lastThreeMonthOilAverage: readFieldOneLiner('last_three_month_oil_average', NUMBER_FIELD),
	lastThreeMonthWaterAverage: readFieldOneLiner('last_three_month_water_average', NUMBER_FIELD),
	leaseNri: readFieldOneLiner('lease_nri', NUMBER_FIELD),
	monthlyWellCost: readFieldOneLiner('monthly_well_cost', NUMBER_FIELD),
	netBoeSalesVolume: readFieldOneLiner('net_boe_sales_volume', NUMBER_FIELD),
	netDripCondensateSalesVolume: readFieldOneLiner('net_drip_condensate_sales_volume', NUMBER_FIELD),
	netGasSalesVolume: readFieldOneLiner('net_gas_sales_volume', NUMBER_FIELD),
	netNglSalesVolume: readFieldOneLiner('net_ngl_sales_volume', NUMBER_FIELD),
	netOilSalesVolume: readFieldOneLiner('net_oil_sales_volume', NUMBER_FIELD),
	netProfit: readFieldOneLiner('net_profit', NUMBER_FIELD),
	netIncome: readFieldOneLiner('net_income', NUMBER_FIELD),
	netMcfeSalesVolume: readFieldOneLiner('net_mcfe_sales_volume', NUMBER_FIELD),
	nglGatheringExpense: readFieldOneLiner('ngl_gathering_expense', NUMBER_FIELD),
	nglMarketingExpense: readFieldOneLiner('ngl_marketing_expense', NUMBER_FIELD),
	nglOtherExpense: readFieldOneLiner('ngl_other_expense', NUMBER_FIELD),
	nglPrice: readFieldOneLiner('ngl_price', NUMBER_FIELD),
	nglProcessingExpense: readFieldOneLiner('ngl_processing_expense', NUMBER_FIELD),
	nglRevenue: readFieldOneLiner('ngl_revenue', NUMBER_FIELD),
	nglSeveranceTax: readFieldOneLiner('ngl_severance_tax', NUMBER_FIELD),
	nglShrunkEur: readFieldOneLiner('ngl_shrunk_eur', NUMBER_FIELD),
	nglTransportationExpense: readFieldOneLiner('ngl_transportation_expense', NUMBER_FIELD),
	nglYield: readFieldOneLiner('ngl_yield', NUMBER_FIELD),
	nglBoeConversion: readFieldOneLiner('ngl_boe_conversion', NUMBER_FIELD),
	nglDifferentials1: readFieldOneLiner('ngl_differentials_1', NUMBER_FIELD),
	nglDifferentials2: readFieldOneLiner('ngl_differentials_2', NUMBER_FIELD),
	nglRisk: readFieldOneLiner('ngl_risk', NUMBER_FIELD),
	nglShrunkEurOverPll: readFieldOneLiner('ngl_shrunk_eur_over_pll', NUMBER_FIELD),
	nriDripCondensate: readFieldOneLiner('nri_drip_condensate', NUMBER_FIELD),
	nriGas: readFieldOneLiner('nri_gas', NUMBER_FIELD),
	nriNgl: readFieldOneLiner('nri_ngl', NUMBER_FIELD),
	nriOil: readFieldOneLiner('nri_oil', NUMBER_FIELD),
	oilAssignedPSeriesFirstSegmentB: readFieldOneLiner('oil_assigned_p_series_first_segment_b', NUMBER_FIELD),
	oilAssignedPSeriesFirstSegmentD1Nominal: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_d1_nominal',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesFirstSegmentDiEffSec: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesFirstSegmentEndDate: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_end_date',
		STRING_FIELD,
	),
	oilAssignedPSeriesFirstSegmentQEnd: readFieldOneLiner('oil_assigned_p_series_first_segment_q_end', NUMBER_FIELD),
	oilAssignedPSeriesFirstSegmentQStart: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_q_start',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesFirstSegmentSegmentType: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_segment_type',
		STRING_FIELD,
	),
	oilAssignedPSeriesFirstSegmentStartDate: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_start_date',
		STRING_FIELD,
	),
	oilAssignedPSeriesFirstSegmentSwDate: readFieldOneLiner(
		'oil_assigned_p_series_first_segment_sw_date',
		STRING_FIELD,
	),
	oilAssignedPSeriesLastSegmentB: readFieldOneLiner('oil_assigned_p_series_last_segment_b', NUMBER_FIELD),
	oilAssignedPSeriesLastSegmentD1Nominal: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_d1_nominal',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesLastSegmentDiEffSec: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesLastSegmentEndDate: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_end_date',
		STRING_FIELD,
	),
	oilAssignedPSeriesLastSegmentQEnd: readFieldOneLiner('oil_assigned_p_series_last_segment_q_end', NUMBER_FIELD),
	oilAssignedPSeriesLastSegmentQStart: readFieldOneLiner('oil_assigned_p_series_last_segment_q_start', NUMBER_FIELD),
	oilAssignedPSeriesLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	oilAssignedPSeriesLastSegmentSegmentType: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_segment_type',
		STRING_FIELD,
	),
	oilAssignedPSeriesLastSegmentStartDate: readFieldOneLiner(
		'oil_assigned_p_series_last_segment_start_date',
		STRING_FIELD,
	),
	oilAssignedPSeriesLastSegmentSwDate: readFieldOneLiner('oil_assigned_p_series_last_segment_sw_date', STRING_FIELD),
	oilBestFitFirstSegmentB: readFieldOneLiner('oil_best_fit_first_segment_b', NUMBER_FIELD),
	oilBestFitFirstSegmentD1Nominal: readFieldOneLiner('oil_best_fit_first_segment_d1_nominal', NUMBER_FIELD),
	oilBestFitFirstSegmentDiEffSec: readFieldOneLiner('oil_best_fit_first_segment_di_eff_sec', NUMBER_FIELD),
	oilBestFitFirstSegmentEndDate: readFieldOneLiner('oil_best_fit_first_segment_end_date', STRING_FIELD),
	oilBestFitFirstSegmentQEnd: readFieldOneLiner('oil_best_fit_first_segment_q_end', NUMBER_FIELD),
	oilBestFitFirstSegmentQStart: readFieldOneLiner('oil_best_fit_first_segment_q_start', NUMBER_FIELD),
	oilBestFitFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'oil_best_fit_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	oilBestFitFirstSegmentSegmentType: readFieldOneLiner('oil_best_fit_first_segment_segment_type', STRING_FIELD),
	oilBestFitFirstSegmentStartDate: readFieldOneLiner('oil_best_fit_first_segment_start_date', STRING_FIELD),
	oilBestFitFirstSegmentSwDate: readFieldOneLiner('oil_best_fit_first_segment_sw_date', STRING_FIELD),
	oilBestFitLastSegmentB: readFieldOneLiner('oil_best_fit_last_segment_b', NUMBER_FIELD),
	oilBestFitLastSegmentD1Nominal: readFieldOneLiner('oil_best_fit_last_segment_d1_nominal', NUMBER_FIELD),
	oilBestFitLastSegmentDiEffSec: readFieldOneLiner('oil_best_fit_last_segment_di_eff_sec', NUMBER_FIELD),
	oilBestFitLastSegmentEndDate: readFieldOneLiner('oil_best_fit_last_segment_end_date', STRING_FIELD),
	oilBestFitLastSegmentQEnd: readFieldOneLiner('oil_best_fit_last_segment_q_end', NUMBER_FIELD),
	oilBestFitLastSegmentQStart: readFieldOneLiner('oil_best_fit_last_segment_q_start', NUMBER_FIELD),
	oilBestFitLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'oil_best_fit_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	oilBestFitLastSegmentSegmentType: readFieldOneLiner('oil_best_fit_last_segment_segment_type', STRING_FIELD),
	oilBestFitLastSegmentStartDate: readFieldOneLiner('oil_best_fit_last_segment_start_date', STRING_FIELD),
	oilBestFitLastSegmentSwDate: readFieldOneLiner('oil_best_fit_last_segment_sw_date', STRING_FIELD),
	oilBreakeven: readFieldOneLiner('oil_breakeven', NUMBER_FIELD),
	oilGatheringExpense: readFieldOneLiner('oil_gathering_expense', NUMBER_FIELD),
	oilLoss: readFieldOneLiner('oil_loss', NUMBER_FIELD),
	oilMarketingExpense: readFieldOneLiner('oil_marketing_expense', NUMBER_FIELD),
	oilOtherExpense: readFieldOneLiner('oil_other_expense', NUMBER_FIELD),
	oilP10FirstSegmentB: readFieldOneLiner('oil_p10_first_segment_b', NUMBER_FIELD),
	oilP10FirstSegmentD1Nominal: readFieldOneLiner('oil_p10_first_segment_d1_nominal', NUMBER_FIELD),
	oilP10FirstSegmentDiEffSec: readFieldOneLiner('oil_p10_first_segment_di_eff_sec', NUMBER_FIELD),
	oilP10FirstSegmentEndDate: readFieldOneLiner('oil_p10_first_segment_end_date', STRING_FIELD),
	oilP10FirstSegmentQEnd: readFieldOneLiner('oil_p10_first_segment_q_end', NUMBER_FIELD),
	oilP10FirstSegmentQStart: readFieldOneLiner('oil_p10_first_segment_q_start', NUMBER_FIELD),
	oilP10FirstSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p10_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP10FirstSegmentSegmentType: readFieldOneLiner('oil_p10_first_segment_segment_type', STRING_FIELD),
	oilP10FirstSegmentStartDate: readFieldOneLiner('oil_p10_first_segment_start_date', STRING_FIELD),
	oilP10FirstSegmentSwDate: readFieldOneLiner('oil_p10_first_segment_sw_date', STRING_FIELD),
	oilP10LastSegmentB: readFieldOneLiner('oil_p10_last_segment_b', NUMBER_FIELD),
	oilP10LastSegmentD1Nominal: readFieldOneLiner('oil_p10_last_segment_d1_nominal', NUMBER_FIELD),
	oilP10LastSegmentDiEffSec: readFieldOneLiner('oil_p10_last_segment_di_eff_sec', NUMBER_FIELD),
	oilP10LastSegmentEndDate: readFieldOneLiner('oil_p10_last_segment_end_date', STRING_FIELD),
	oilP10LastSegmentQEnd: readFieldOneLiner('oil_p10_last_segment_q_end', NUMBER_FIELD),
	oilP10LastSegmentQStart: readFieldOneLiner('oil_p10_last_segment_q_start', NUMBER_FIELD),
	oilP10LastSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p10_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP10LastSegmentSegmentType: readFieldOneLiner('oil_p10_last_segment_segment_type', STRING_FIELD),
	oilP10LastSegmentStartDate: readFieldOneLiner('oil_p10_last_segment_start_date', STRING_FIELD),
	oilP10LastSegmentSwDate: readFieldOneLiner('oil_p10_last_segment_sw_date', STRING_FIELD),
	oilP50FirstSegmentB: readFieldOneLiner('oil_p50_first_segment_b', NUMBER_FIELD),
	oilP50FirstSegmentD1Nominal: readFieldOneLiner('oil_p50_first_segment_d1_nominal', NUMBER_FIELD),
	oilP50FirstSegmentDiEffSec: readFieldOneLiner('oil_p50_first_segment_di_eff_sec', NUMBER_FIELD),
	oilP50FirstSegmentEndDate: readFieldOneLiner('oil_p50_first_segment_end_date', STRING_FIELD),
	oilP50FirstSegmentQEnd: readFieldOneLiner('oil_p50_first_segment_q_end', NUMBER_FIELD),
	oilP50FirstSegmentQStart: readFieldOneLiner('oil_p50_first_segment_q_start', NUMBER_FIELD),
	oilP50FirstSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p50_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP50FirstSegmentSegmentType: readFieldOneLiner('oil_p50_first_segment_segment_type', STRING_FIELD),
	oilP50FirstSegmentStartDate: readFieldOneLiner('oil_p50_first_segment_start_date', STRING_FIELD),
	oilP50FirstSegmentSwDate: readFieldOneLiner('oil_p50_first_segment_sw_date', STRING_FIELD),
	oilP50LastSegmentB: readFieldOneLiner('oil_p50_last_segment_b', NUMBER_FIELD),
	oilP50LastSegmentD1Nominal: readFieldOneLiner('oil_p50_last_segment_d1_nominal', NUMBER_FIELD),
	oilP50LastSegmentDiEffSec: readFieldOneLiner('oil_p50_last_segment_di_eff_sec', NUMBER_FIELD),
	oilP50LastSegmentEndDate: readFieldOneLiner('oil_p50_last_segment_end_date', STRING_FIELD),
	oilP50LastSegmentQEnd: readFieldOneLiner('oil_p50_last_segment_q_end', NUMBER_FIELD),
	oilP50LastSegmentQStart: readFieldOneLiner('oil_p50_last_segment_q_start', NUMBER_FIELD),
	oilP50LastSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p50_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP50LastSegmentSegmentType: readFieldOneLiner('oil_p50_last_segment_segment_type', STRING_FIELD),
	oilP50LastSegmentStartDate: readFieldOneLiner('oil_p50_last_segment_start_date', STRING_FIELD),
	oilP50LastSegmentSwDate: readFieldOneLiner('oil_p50_last_segment_sw_date', STRING_FIELD),
	oilP90FirstSegmentB: readFieldOneLiner('oil_p90_first_segment_b', NUMBER_FIELD),
	oilP90FirstSegmentD1Nominal: readFieldOneLiner('oil_p90_first_segment_d1_nominal', NUMBER_FIELD),
	oilP90FirstSegmentDiEffSec: readFieldOneLiner('oil_p90_first_segment_di_eff_sec', NUMBER_FIELD),
	oilP90FirstSegmentEndDate: readFieldOneLiner('oil_p90_first_segment_end_date', STRING_FIELD),
	oilP90FirstSegmentQEnd: readFieldOneLiner('oil_p90_first_segment_q_end', NUMBER_FIELD),
	oilP90FirstSegmentQStart: readFieldOneLiner('oil_p90_first_segment_q_start', NUMBER_FIELD),
	oilP90FirstSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p90_first_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP90FirstSegmentSegmentType: readFieldOneLiner('oil_p90_first_segment_segment_type', STRING_FIELD),
	oilP90FirstSegmentStartDate: readFieldOneLiner('oil_p90_first_segment_start_date', STRING_FIELD),
	oilP90FirstSegmentSwDate: readFieldOneLiner('oil_p90_first_segment_sw_date', STRING_FIELD),
	oilP90LastSegmentB: readFieldOneLiner('oil_p90_last_segment_b', NUMBER_FIELD),
	oilP90LastSegmentD1Nominal: readFieldOneLiner('oil_p90_last_segment_d1_nominal', NUMBER_FIELD),
	oilP90LastSegmentDiEffSec: readFieldOneLiner('oil_p90_last_segment_di_eff_sec', NUMBER_FIELD),
	oilP90LastSegmentEndDate: readFieldOneLiner('oil_p90_last_segment_end_date', STRING_FIELD),
	oilP90LastSegmentQEnd: readFieldOneLiner('oil_p90_last_segment_q_end', NUMBER_FIELD),
	oilP90LastSegmentQStart: readFieldOneLiner('oil_p90_last_segment_q_start', NUMBER_FIELD),
	oilP90LastSegmentRealizedDSwEffSec: readFieldOneLiner('oil_p90_last_segment_realized_d_sw_eff_sec', NUMBER_FIELD),
	oilP90LastSegmentSegmentType: readFieldOneLiner('oil_p90_last_segment_segment_type', STRING_FIELD),
	oilP90LastSegmentStartDate: readFieldOneLiner('oil_p90_last_segment_start_date', STRING_FIELD),
	oilP90LastSegmentSwDate: readFieldOneLiner('oil_p90_last_segment_sw_date', STRING_FIELD),
	oilPrice: readFieldOneLiner('oil_price', NUMBER_FIELD),
	oilProcessingExpense: readFieldOneLiner('oil_processing_expense', NUMBER_FIELD),
	oilRevenue: readFieldOneLiner('oil_revenue', NUMBER_FIELD),
	oilSeveranceTax: readFieldOneLiner('oil_severance_tax', NUMBER_FIELD),
	oilShrinkage: readFieldOneLiner('oil_shrinkage', NUMBER_FIELD),
	oilShrunkEur: readFieldOneLiner('oil_shrunk_eur', NUMBER_FIELD),
	oilTransportationExpense: readFieldOneLiner('oil_transportation_expense', NUMBER_FIELD),
	oilWellHeadEur: readFieldOneLiner('oil_well_head_eur', NUMBER_FIELD),
	oilBoeConversion: readFieldOneLiner('oil_boe_conversion', NUMBER_FIELD),
	oilDifferentials1: readFieldOneLiner('oil_differentials_1', NUMBER_FIELD),
	oilDifferentials2: readFieldOneLiner('oil_differentials_2', NUMBER_FIELD),
	oilProductionAsOfDate: readFieldOneLiner('oil_production_as_of_date', NUMBER_FIELD),
	oilRisk: readFieldOneLiner('oil_risk', NUMBER_FIELD),
	oilShrunkEurOverPll: readFieldOneLiner('oil_shrunk_eur_over_pll', NUMBER_FIELD),
	oilTcRisk: readFieldOneLiner('oil_tc_risk', NUMBER_FIELD),
	oilWellHeadEurOverPll: readFieldOneLiner('oil_well_head_eur_over_pll', NUMBER_FIELD),
	oneMonthGrossBoeSalesVolume: readFieldOneLiner('one_month_gross_BOE_sales_volume', NUMBER_FIELD),
	oneMonthGrossBoeWellHeadVolume: readFieldOneLiner('one_month_gross_BOE_well_head_volume', NUMBER_FIELD),
	oneMonthGrossDripCondensateSalesVolume: readFieldOneLiner(
		'one_month_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	oneMonthGrossGasSalesVolume: readFieldOneLiner('one_month_gross_gas_sales_volume', NUMBER_FIELD),
	oneMonthGrossGasWellHeadVolume: readFieldOneLiner('one_month_gross_gas_well_head_volume', NUMBER_FIELD),
	oneMonthGrossNglSalesVolume: readFieldOneLiner('one_month_gross_ngl_sales_volume', NUMBER_FIELD),
	oneMonthGrossOilSalesVolume: readFieldOneLiner('one_month_gross_oil_sales_volume', NUMBER_FIELD),
	oneMonthGrossOilWellHeadVolume: readFieldOneLiner('one_month_gross_oil_well_head_volume', NUMBER_FIELD),
	oneMonthGrossWaterWellHeadVolume: readFieldOneLiner('one_month_gross_water_well_head_volume', NUMBER_FIELD),
	oneMonthNetBoeSalesVolume: readFieldOneLiner('one_month_net_BOE_sales_volume', NUMBER_FIELD),
	oneMonthNetDripCondensateSalesVolume: readFieldOneLiner('one_month_net_drip_condensate_sales_volume', NUMBER_FIELD),
	oneMonthNetGasSalesVolume: readFieldOneLiner('one_month_net_gas_sales_volume', NUMBER_FIELD),
	oneMonthNetNglSalesVolume: readFieldOneLiner('one_month_net_ngl_sales_volume', NUMBER_FIELD),
	oneMonthNetOilSalesVolume: readFieldOneLiner('one_month_net_oil_sales_volume', NUMBER_FIELD),
	oneMonthWiBoeSalesVolume: readFieldOneLiner('one_month_wi_BOE_sales_volume', NUMBER_FIELD),
	oneMonthWiDripCondensateSalesVolume: readFieldOneLiner('one_month_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	oneMonthWiGasSalesVolume: readFieldOneLiner('one_month_wi_gas_sales_volume', NUMBER_FIELD),
	oneMonthWiNglSalesVolume: readFieldOneLiner('one_month_wi_ngl_sales_volume', NUMBER_FIELD),
	oneMonthWiOilSalesVolume: readFieldOneLiner('one_month_wi_oil_sales_volume', NUMBER_FIELD),
	oneYearGrossBoeSalesVolume: readFieldOneLiner('one_year_gross_BOE_sales_volume', NUMBER_FIELD),
	oneYearGrossBoeWellHeadVolume: readFieldOneLiner('one_year_gross_BOE_well_head_volume', NUMBER_FIELD),
	oneYearGrossDripCondensateSalesVolume: readFieldOneLiner(
		'one_year_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	oneYearGrossGasSalesVolume: readFieldOneLiner('one_year_gross_gas_sales_volume', NUMBER_FIELD),
	oneYearGrossGasWellHeadVolume: readFieldOneLiner('one_year_gross_gas_well_head_volume', NUMBER_FIELD),
	oneYearGrossNglSalesVolume: readFieldOneLiner('one_year_gross_ngl_sales_volume', NUMBER_FIELD),
	oneYearGrossOilSalesVolume: readFieldOneLiner('one_year_gross_oil_sales_volume', NUMBER_FIELD),
	oneYearGrossOilWellHeadVolume: readFieldOneLiner('one_year_gross_oil_well_head_volume', NUMBER_FIELD),
	oneYearGrossWaterWellHeadVolume: readFieldOneLiner('one_year_gross_water_well_head_volume', NUMBER_FIELD),
	oneYearNetBoeSalesVolume: readFieldOneLiner('one_year_net_BOE_sales_volume', NUMBER_FIELD),
	oneYearNetDripCondensateSalesVolume: readFieldOneLiner('one_year_net_drip_condensate_sales_volume', NUMBER_FIELD),
	oneYearNetGasSalesVolume: readFieldOneLiner('one_year_net_gas_sales_volume', NUMBER_FIELD),
	oneYearNetNglSalesVolume: readFieldOneLiner('one_year_net_ngl_sales_volume', NUMBER_FIELD),
	oneYearNetOilSalesVolume: readFieldOneLiner('one_year_net_oil_sales_volume', NUMBER_FIELD),
	oneYearWiBoeSalesVolume: readFieldOneLiner('one_year_wi_BOE_sales_volume', NUMBER_FIELD),
	oneYearWiDripCondensateSalesVolume: readFieldOneLiner('one_year_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	oneYearWiGasSalesVolume: readFieldOneLiner('one_year_wi_gas_sales_volume', NUMBER_FIELD),
	oneYearWiNglSalesVolume: readFieldOneLiner('one_year_wi_ngl_sales_volume', NUMBER_FIELD),
	oneYearWiOilSalesVolume: readFieldOneLiner('one_year_wi_oil_sales_volume', NUMBER_FIELD),
	originalWiDripCondensate: readFieldOneLiner('original_wi_drip_condensate', NUMBER_FIELD),
	originalWiGas: readFieldOneLiner('original_wi_gas', NUMBER_FIELD),
	originalWiNgl: readFieldOneLiner('original_wi_ngl', NUMBER_FIELD),
	originalWiOil: readFieldOneLiner('original_wi_oil', NUMBER_FIELD),
	otherMonthlyCost_1: readFieldOneLiner('other_monthly_cost_1', NUMBER_FIELD),
	otherMonthlyCost_2: readFieldOneLiner('other_monthly_cost_2', NUMBER_FIELD),
	payoutDuration: readFieldOneLiner('payout_duration', NUMBER_FIELD),
	secondDiscountCashFlow: readFieldOneLiner('second_discount_cash_flow', NUMBER_FIELD),
	secondDiscountRoi: readFieldOneLiner('second_discount_roi', NUMBER_FIELD),
	secondDiscountNetIncome: readFieldOneLiner('second_discount_net_income', NUMBER_FIELD),
	secondDiscountPayout: readFieldOneLiner('second_discount_payout', STRING_FIELD),
	secondDiscountPayoutDuration: readFieldOneLiner('second_discount_payout_duration', NUMBER_FIELD),
	secondDiscountRoiUndiscountedCapex: readFieldOneLiner('second_discount_roi_undiscounted_capex', NUMBER_FIELD),
	secondDiscountedCapex: readFieldOneLiner('second_discounted_capex', NUMBER_FIELD),
	shrunkGasBtu: readFieldOneLiner('shrunk_gas_btu', NUMBER_FIELD),
	sixMonthGrossBoeSalesVolume: readFieldOneLiner('six_month_gross_BOE_sales_volume', NUMBER_FIELD),
	sixMonthGrossBoeWellHeadVolume: readFieldOneLiner('six_month_gross_BOE_well_head_volume', NUMBER_FIELD),
	sixMonthGrossDripCondensateSalesVolume: readFieldOneLiner(
		'six_month_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	sixMonthGrossGasSalesVolume: readFieldOneLiner('six_month_gross_gas_sales_volume', NUMBER_FIELD),
	sixMonthGrossGasWellHeadVolume: readFieldOneLiner('six_month_gross_gas_well_head_volume', NUMBER_FIELD),
	sixMonthGrossNglSalesVolume: readFieldOneLiner('six_month_gross_ngl_sales_volume', NUMBER_FIELD),
	sixMonthGrossOilSalesVolume: readFieldOneLiner('six_month_gross_oil_sales_volume', NUMBER_FIELD),
	sixMonthGrossOilWellHeadVolume: readFieldOneLiner('six_month_gross_oil_well_head_volume', NUMBER_FIELD),
	sixMonthGrossWaterWellHeadVolume: readFieldOneLiner('six_month_gross_water_well_head_volume', NUMBER_FIELD),
	sixMonthNetBoeSalesVolume: readFieldOneLiner('six_month_net_BOE_sales_volume', NUMBER_FIELD),
	sixMonthNetDripCondensateSalesVolume: readFieldOneLiner('six_month_net_drip_condensate_sales_volume', NUMBER_FIELD),
	sixMonthNetGasSalesVolume: readFieldOneLiner('six_month_net_gas_sales_volume', NUMBER_FIELD),
	sixMonthNetNglSalesVolume: readFieldOneLiner('six_month_net_ngl_sales_volume', NUMBER_FIELD),
	sixMonthNetOilSalesVolume: readFieldOneLiner('six_month_net_oil_sales_volume', NUMBER_FIELD),
	sixMonthWiBoeSalesVolume: readFieldOneLiner('six_month_wi_BOE_sales_volume', NUMBER_FIELD),
	sixMonthWiDripCondensateSalesVolume: readFieldOneLiner('six_month_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	sixMonthWiGasSalesVolume: readFieldOneLiner('six_month_wi_gas_sales_volume', NUMBER_FIELD),
	sixMonthWiNglSalesVolume: readFieldOneLiner('six_month_wi_ngl_sales_volume', NUMBER_FIELD),
	sixMonthWiOilSalesVolume: readFieldOneLiner('six_month_wi_oil_sales_volume', NUMBER_FIELD),
	stateIncomeTax: readFieldOneLiner('state_income_tax', NUMBER_FIELD),
	tangibleAbandonment: readFieldOneLiner('tangible_abandonment', NUMBER_FIELD),
	tangibleAppraisal: readFieldOneLiner('tangible_appraisal', NUMBER_FIELD),
	tangibleArtificialLift: readFieldOneLiner('tangible_artificial_lift', NUMBER_FIELD),
	tangibleCompletion: readFieldOneLiner('tangible_completion', NUMBER_FIELD),
	tangibleDevelopment: readFieldOneLiner('tangible_development', NUMBER_FIELD),
	tangibleDrilling: readFieldOneLiner('tangible_drilling', NUMBER_FIELD),
	tangibleExploration: readFieldOneLiner('tangible_exploration', NUMBER_FIELD),
	tangibleFacilities: readFieldOneLiner('tangible_facilities', NUMBER_FIELD),
	tangibleLeasehold: readFieldOneLiner('tangible_leasehold', NUMBER_FIELD),
	tangibleLegal: readFieldOneLiner('tangible_legal', NUMBER_FIELD),
	tangibleOtherInvestment: readFieldOneLiner('tangible_other_investment', NUMBER_FIELD),
	tangiblePad: readFieldOneLiner('tangible_pad', NUMBER_FIELD),
	tangiblePipelines: readFieldOneLiner('tangible_pipelines', NUMBER_FIELD),
	tangibleSalvage: readFieldOneLiner('tangible_salvage', NUMBER_FIELD),
	tangibleWaterline: readFieldOneLiner('tangible_waterline', NUMBER_FIELD),
	tangibleWorkover: readFieldOneLiner('tangible_workover', NUMBER_FIELD),
	taxableIncome: readFieldOneLiner('taxable_income', NUMBER_FIELD),
	tenYearGrossBoeSalesVolume: readFieldOneLiner('ten_year_gross_BOE_sales_volume', NUMBER_FIELD),
	tenYearGrossBoeWellHeadVolume: readFieldOneLiner('ten_year_gross_BOE_well_head_volume', NUMBER_FIELD),
	tenYearGrossDripCondensateSalesVolume: readFieldOneLiner(
		'ten_year_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	tenYearGrossGasSalesVolume: readFieldOneLiner('ten_year_gross_gas_sales_volume', NUMBER_FIELD),
	tenYearGrossGasWellHeadVolume: readFieldOneLiner('ten_year_gross_gas_well_head_volume', NUMBER_FIELD),
	tenYearGrossNglSalesVolume: readFieldOneLiner('ten_year_gross_ngl_sales_volume', NUMBER_FIELD),
	tenYearGrossOilSalesVolume: readFieldOneLiner('ten_year_gross_oil_sales_volume', NUMBER_FIELD),
	tenYearGrossOilWellHeadVolume: readFieldOneLiner('ten_year_gross_oil_well_head_volume', NUMBER_FIELD),
	tenYearGrossWaterWellHeadVolume: readFieldOneLiner('ten_year_gross_water_well_head_volume', NUMBER_FIELD),
	tenYearNetBoeSalesVolume: readFieldOneLiner('ten_year_net_BOE_sales_volume', NUMBER_FIELD),
	tenYearNetDripCondensateSalesVolume: readFieldOneLiner('ten_year_net_drip_condensate_sales_volume', NUMBER_FIELD),
	tenYearNetGasSalesVolume: readFieldOneLiner('ten_year_net_gas_sales_volume', NUMBER_FIELD),
	tenYearNetNglSalesVolume: readFieldOneLiner('ten_year_net_ngl_sales_volume', NUMBER_FIELD),
	tenYearNetOilSalesVolume: readFieldOneLiner('ten_year_net_oil_sales_volume', NUMBER_FIELD),
	tenYearWiBoeSalesVolume: readFieldOneLiner('ten_year_wi_BOE_sales_volume', NUMBER_FIELD),
	tenYearWiDripCondensateSalesVolume: readFieldOneLiner('ten_year_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	tenYearWiGasSalesVolume: readFieldOneLiner('ten_year_wi_gas_sales_volume', NUMBER_FIELD),
	tenYearWiNglSalesVolume: readFieldOneLiner('ten_year_wi_ngl_sales_volume', NUMBER_FIELD),
	tenYearWiOilSalesVolume: readFieldOneLiner('ten_year_wi_oil_sales_volume', NUMBER_FIELD),
	threeMonthGrossBoeSalesVolume: readFieldOneLiner('three_month_gross_BOE_sales_volume', NUMBER_FIELD),
	threeMonthGrossBoeWellHeadVolume: readFieldOneLiner('three_month_gross_BOE_well_head_volume', NUMBER_FIELD),
	threeMonthGrossDripCondensateSalesVolume: readFieldOneLiner(
		'three_month_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	threeMonthGrossGasSalesVolume: readFieldOneLiner('three_month_gross_gas_sales_volume', NUMBER_FIELD),
	threeMonthGrossGasWellHeadVolume: readFieldOneLiner('three_month_gross_gas_well_head_volume', NUMBER_FIELD),
	threeMonthGrossNglSalesVolume: readFieldOneLiner('three_month_gross_ngl_sales_volume', NUMBER_FIELD),
	threeMonthGrossOilSalesVolume: readFieldOneLiner('three_month_gross_oil_sales_volume', NUMBER_FIELD),
	threeMonthGrossOilWellHeadVolume: readFieldOneLiner('three_month_gross_oil_well_head_volume', NUMBER_FIELD),
	threeMonthGrossWaterWellHeadVolume: readFieldOneLiner('three_month_gross_water_well_head_volume', NUMBER_FIELD),
	threeMonthNetBoeSalesVolume: readFieldOneLiner('three_month_net_BOE_sales_volume', NUMBER_FIELD),
	threeMonthNetDripCondensateSalesVolume: readFieldOneLiner(
		'three_month_net_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	threeMonthNetGasSalesVolume: readFieldOneLiner('three_month_net_gas_sales_volume', NUMBER_FIELD),
	threeMonthNetNglSalesVolume: readFieldOneLiner('three_month_net_ngl_sales_volume', NUMBER_FIELD),
	threeMonthNetOilSalesVolume: readFieldOneLiner('three_month_net_oil_sales_volume', NUMBER_FIELD),
	threeMonthWiBoeSalesVolume: readFieldOneLiner('three_month_wi_BOE_sales_volume', NUMBER_FIELD),
	threeMonthWiDripCondensateSalesVolume: readFieldOneLiner(
		'three_month_wi_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	threeMonthWiGasSalesVolume: readFieldOneLiner('three_month_wi_gas_sales_volume', NUMBER_FIELD),
	threeMonthWiNglSalesVolume: readFieldOneLiner('three_month_wi_ngl_sales_volume', NUMBER_FIELD),
	threeMonthWiOilSalesVolume: readFieldOneLiner('three_month_wi_oil_sales_volume', NUMBER_FIELD),
	threeYearGrossBoeSalesVolume: readFieldOneLiner('three_year_gross_BOE_sales_volume', NUMBER_FIELD),
	threeYearGrossBoeWellHeadVolume: readFieldOneLiner('three_year_gross_BOE_well_head_volume', NUMBER_FIELD),
	threeYearGrossDripCondensateSalesVolume: readFieldOneLiner(
		'three_year_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	threeYearGrossGasSalesVolume: readFieldOneLiner('three_year_gross_gas_sales_volume', NUMBER_FIELD),
	threeYearGrossGasWellHeadVolume: readFieldOneLiner('three_year_gross_gas_well_head_volume', NUMBER_FIELD),
	threeYearGrossNglSalesVolume: readFieldOneLiner('three_year_gross_ngl_sales_volume', NUMBER_FIELD),
	threeYearGrossOilSalesVolume: readFieldOneLiner('three_year_gross_oil_sales_volume', NUMBER_FIELD),
	threeYearGrossOilWellHeadVolume: readFieldOneLiner('three_year_gross_oil_well_head_volume', NUMBER_FIELD),
	threeYearGrossWaterWellHeadVolume: readFieldOneLiner('three_year_gross_water_well_head_volume', NUMBER_FIELD),
	threeYearNetBoeSalesVolume: readFieldOneLiner('three_year_net_BOE_sales_volume', NUMBER_FIELD),
	threeYearNetDripCondensateSalesVolume: readFieldOneLiner(
		'three_year_net_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	threeYearNetGasSalesVolume: readFieldOneLiner('three_year_net_gas_sales_volume', NUMBER_FIELD),
	threeYearNetNglSalesVolume: readFieldOneLiner('three_year_net_ngl_sales_volume', NUMBER_FIELD),
	threeYearNetOilSalesVolume: readFieldOneLiner('three_year_net_oil_sales_volume', NUMBER_FIELD),
	threeYearWiBoeSalesVolume: readFieldOneLiner('three_year_wi_BOE_sales_volume', NUMBER_FIELD),
	threeYearWiDripCondensateSalesVolume: readFieldOneLiner('three_year_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	threeYearWiGasSalesVolume: readFieldOneLiner('three_year_wi_gas_sales_volume', NUMBER_FIELD),
	threeYearWiNglSalesVolume: readFieldOneLiner('three_year_wi_ngl_sales_volume', NUMBER_FIELD),
	threeYearWiOilSalesVolume: readFieldOneLiner('three_year_wi_oil_sales_volume', NUMBER_FIELD),
	totalAbandonment: readFieldOneLiner('total_abandonment', NUMBER_FIELD),
	totalAppraisal: readFieldOneLiner('total_appraisal', NUMBER_FIELD),
	totalArtificialLift: readFieldOneLiner('total_artificial_lift', NUMBER_FIELD),
	totalCapex: readFieldOneLiner('total_capex', NUMBER_FIELD),
	totalCompletion: readFieldOneLiner('total_completion', NUMBER_FIELD),
	totalDevelopment: readFieldOneLiner('total_development', NUMBER_FIELD),
	totalDrilling: readFieldOneLiner('total_drilling', NUMBER_FIELD),
	totalDripCondensateVariableExpense: readFieldOneLiner('total_drip_condensate_variable_expense', NUMBER_FIELD),
	totalExpense: readFieldOneLiner('total_expense', NUMBER_FIELD),
	totalExploration: readFieldOneLiner('total_exploration', NUMBER_FIELD),
	totalFacilities: readFieldOneLiner('total_facilities', NUMBER_FIELD),
	totalFixedExpense: readFieldOneLiner('total_fixed_expense', NUMBER_FIELD),
	totalGasVariableExpense: readFieldOneLiner('total_gas_variable_expense', NUMBER_FIELD),
	totalIntangibleCapex: readFieldOneLiner('total_intangible_capex', NUMBER_FIELD),
	totalLeasehold: readFieldOneLiner('total_leasehold', NUMBER_FIELD),
	totalLegal: readFieldOneLiner('total_legal', NUMBER_FIELD),
	totalNegativeCashFlowMonthCount: readFieldOneLiner('total_negative_cash_flow_month_count', NUMBER_FIELD),
	totalNglVariableExpense: readFieldOneLiner('total_ngl_variable_expense', NUMBER_FIELD),
	totalOilVariableExpense: readFieldOneLiner('total_oil_variable_expense', NUMBER_FIELD),
	totalOtherInvestment: readFieldOneLiner('total_other_investment', NUMBER_FIELD),
	totalPad: readFieldOneLiner('total_pad', NUMBER_FIELD),
	totalPipelines: readFieldOneLiner('total_pipelines', NUMBER_FIELD),
	totalProductionTax: readFieldOneLiner('total_production_tax', NUMBER_FIELD),
	totalRevenue: readFieldOneLiner('total_revenue', NUMBER_FIELD),
	totalSalvage: readFieldOneLiner('total_salvage', NUMBER_FIELD),
	totalSeveranceTax: readFieldOneLiner('total_severance_tax', NUMBER_FIELD),
	totalTangibleCapex: readFieldOneLiner('total_tangible_capex', NUMBER_FIELD),
	totalVariableExpense: readFieldOneLiner('total_variable_expense', NUMBER_FIELD),
	totalWaterline: readFieldOneLiner('total_waterline', NUMBER_FIELD),
	totalWorkover: readFieldOneLiner('total_workover', NUMBER_FIELD),
	totalGrossCapex: readFieldOneLiner('total_gross_capex', NUMBER_FIELD),
	twoYearGrossBoeSalesVolume: readFieldOneLiner('two_year_gross_BOE_sales_volume', NUMBER_FIELD),
	twoYearGrossBoeWellHeadVolume: readFieldOneLiner('two_year_gross_BOE_well_head_volume', NUMBER_FIELD),
	twoYearGrossDripCondensateSalesVolume: readFieldOneLiner(
		'two_year_gross_drip_condensate_sales_volume',
		NUMBER_FIELD,
	),
	twoYearGrossGasSalesVolume: readFieldOneLiner('two_year_gross_gas_sales_volume', NUMBER_FIELD),
	twoYearGrossGasWellHeadVolume: readFieldOneLiner('two_year_gross_gas_well_head_volume', NUMBER_FIELD),
	twoYearGrossNglSalesVolume: readFieldOneLiner('two_year_gross_ngl_sales_volume', NUMBER_FIELD),
	twoYearGrossOilSalesVolume: readFieldOneLiner('two_year_gross_oil_sales_volume', NUMBER_FIELD),
	twoYearGrossOilWellHeadVolume: readFieldOneLiner('two_year_gross_oil_well_head_volume', NUMBER_FIELD),
	twoYearGrossWaterWellHeadVolume: readFieldOneLiner('two_year_gross_water_well_head_volume', NUMBER_FIELD),
	twoYearNetBoeSalesVolume: readFieldOneLiner('two_year_net_BOE_sales_volume', NUMBER_FIELD),
	twoYearNetDripCondensateSalesVolume: readFieldOneLiner('two_year_net_drip_condensate_sales_volume', NUMBER_FIELD),
	twoYearNetGasSalesVolume: readFieldOneLiner('two_year_net_gas_sales_volume', NUMBER_FIELD),
	twoYearNetNglSalesVolume: readFieldOneLiner('two_year_net_ngl_sales_volume', NUMBER_FIELD),
	twoYearNetOilSalesVolume: readFieldOneLiner('two_year_net_oil_sales_volume', NUMBER_FIELD),
	twoYearWiBoeSalesVolume: readFieldOneLiner('two_year_wi_BOE_sales_volume', NUMBER_FIELD),
	twoYearWiDripCondensateSalesVolume: readFieldOneLiner('two_year_wi_drip_condensate_sales_volume', NUMBER_FIELD),
	twoYearWiGasSalesVolume: readFieldOneLiner('two_year_wi_gas_sales_volume', NUMBER_FIELD),
	twoYearWiNglSalesVolume: readFieldOneLiner('two_year_wi_ngl_sales_volume', NUMBER_FIELD),
	twoYearWiOilSalesVolume: readFieldOneLiner('two_year_wi_oil_sales_volume', NUMBER_FIELD),
	undiscountedPayout: readFieldOneLiner('undiscounted_payout', STRING_FIELD),
	undiscountedRoi: readFieldOneLiner('undiscounted_roi', NUMBER_FIELD),
	unshrunkGasBtu: readFieldOneLiner('unshrunk_gas_btu', NUMBER_FIELD),
	waterAssignedPSeriesFirstSegmentB: readFieldOneLiner('water_assigned_p_series_first_segment_b', NUMBER_FIELD),
	waterAssignedPSeriesFirstSegmentD1Nominal: readFieldOneLiner(
		'water_assigned_p_series_first_segment_d1_nominal',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesFirstSegmentDiEffSec: readFieldOneLiner(
		'water_assigned_p_series_first_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesFirstSegmentEndDate: readFieldOneLiner(
		'water_assigned_p_series_first_segment_end_date',
		STRING_FIELD,
	),
	waterAssignedPSeriesFirstSegmentQEnd: readFieldOneLiner(
		'water_assigned_p_series_first_segment_q_end',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesFirstSegmentQStart: readFieldOneLiner(
		'water_assigned_p_series_first_segment_q_start',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_assigned_p_series_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesFirstSegmentSegmentType: readFieldOneLiner(
		'water_assigned_p_series_first_segment_segment_type',
		STRING_FIELD,
	),
	waterAssignedPSeriesFirstSegmentStartDate: readFieldOneLiner(
		'water_assigned_p_series_first_segment_start_date',
		STRING_FIELD,
	),
	waterAssignedPSeriesFirstSegmentSwDate: readFieldOneLiner(
		'water_assigned_p_series_first_segment_sw_date',
		STRING_FIELD,
	),
	waterAssignedPSeriesLastSegmentB: readFieldOneLiner('water_assigned_p_series_last_segment_b', NUMBER_FIELD),
	waterAssignedPSeriesLastSegmentD1Nominal: readFieldOneLiner(
		'water_assigned_p_series_last_segment_d1_nominal',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesLastSegmentDiEffSec: readFieldOneLiner(
		'water_assigned_p_series_last_segment_di_eff_sec',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesLastSegmentEndDate: readFieldOneLiner(
		'water_assigned_p_series_last_segment_end_date',
		STRING_FIELD,
	),
	waterAssignedPSeriesLastSegmentQEnd: readFieldOneLiner('water_assigned_p_series_last_segment_q_end', NUMBER_FIELD),
	waterAssignedPSeriesLastSegmentQStart: readFieldOneLiner(
		'water_assigned_p_series_last_segment_q_start',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_assigned_p_series_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterAssignedPSeriesLastSegmentSegmentType: readFieldOneLiner(
		'water_assigned_p_series_last_segment_segment_type',
		STRING_FIELD,
	),
	waterAssignedPSeriesLastSegmentStartDate: readFieldOneLiner(
		'water_assigned_p_series_last_segment_start_date',
		STRING_FIELD,
	),
	waterAssignedPSeriesLastSegmentSwDate: readFieldOneLiner(
		'water_assigned_p_series_last_segment_sw_date',
		STRING_FIELD,
	),
	waterBestFitFirstSegmentB: readFieldOneLiner('water_best_fit_first_segment_b', NUMBER_FIELD),
	waterBestFitFirstSegmentD1Nominal: readFieldOneLiner('water_best_fit_first_segment_d1_nominal', NUMBER_FIELD),
	waterBestFitFirstSegmentDiEffSec: readFieldOneLiner('water_best_fit_first_segment_di_eff_sec', NUMBER_FIELD),
	waterBestFitFirstSegmentEndDate: readFieldOneLiner('water_best_fit_first_segment_end_date', STRING_FIELD),
	waterBestFitFirstSegmentQEnd: readFieldOneLiner('water_best_fit_first_segment_q_end', NUMBER_FIELD),
	waterBestFitFirstSegmentQStart: readFieldOneLiner('water_best_fit_first_segment_q_start', NUMBER_FIELD),
	waterBestFitFirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_best_fit_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterBestFitFirstSegmentSegmentType: readFieldOneLiner('water_best_fit_first_segment_segment_type', STRING_FIELD),
	waterBestFitFirstSegmentStartDate: readFieldOneLiner('water_best_fit_first_segment_start_date', STRING_FIELD),
	waterBestFitFirstSegmentSwDate: readFieldOneLiner('water_best_fit_first_segment_sw_date', STRING_FIELD),
	waterBestFitLastSegmentB: readFieldOneLiner('water_best_fit_last_segment_b', NUMBER_FIELD),
	waterBestFitLastSegmentD1Nominal: readFieldOneLiner('water_best_fit_last_segment_d1_nominal', NUMBER_FIELD),
	waterBestFitLastSegmentDiEffSec: readFieldOneLiner('water_best_fit_last_segment_di_eff_sec', NUMBER_FIELD),
	waterBestFitLastSegmentEndDate: readFieldOneLiner('water_best_fit_last_segment_end_date', STRING_FIELD),
	waterBestFitLastSegmentQEnd: readFieldOneLiner('water_best_fit_last_segment_q_end', NUMBER_FIELD),
	waterBestFitLastSegmentQStart: readFieldOneLiner('water_best_fit_last_segment_q_start', NUMBER_FIELD),
	waterBestFitLastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_best_fit_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterBestFitLastSegmentSegmentType: readFieldOneLiner('water_best_fit_last_segment_segment_type', STRING_FIELD),
	waterBestFitLastSegmentStartDate: readFieldOneLiner('water_best_fit_last_segment_start_date', STRING_FIELD),
	waterBestFitLastSegmentSwDate: readFieldOneLiner('water_best_fit_last_segment_sw_date', STRING_FIELD),
	waterDisposal: readFieldOneLiner('water_disposal', NUMBER_FIELD),
	waterP10FirstSegmentB: readFieldOneLiner('water_p10_first_segment_b', NUMBER_FIELD),
	waterP10FirstSegmentD1Nominal: readFieldOneLiner('water_p10_first_segment_d1_nominal', NUMBER_FIELD),
	waterP10FirstSegmentDiEffSec: readFieldOneLiner('water_p10_first_segment_di_eff_sec', NUMBER_FIELD),
	waterP10FirstSegmentEndDate: readFieldOneLiner('water_p10_first_segment_end_date', STRING_FIELD),
	waterP10FirstSegmentQEnd: readFieldOneLiner('water_p10_first_segment_q_end', NUMBER_FIELD),
	waterP10FirstSegmentQStart: readFieldOneLiner('water_p10_first_segment_q_start', NUMBER_FIELD),
	waterP10FirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p10_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP10FirstSegmentSegmentType: readFieldOneLiner('water_p10_first_segment_segment_type', STRING_FIELD),
	waterP10FirstSegmentStartDate: readFieldOneLiner('water_p10_first_segment_start_date', STRING_FIELD),
	waterP10FirstSegmentSwDate: readFieldOneLiner('water_p10_first_segment_sw_date', STRING_FIELD),
	waterP10LastSegmentB: readFieldOneLiner('water_p10_last_segment_b', NUMBER_FIELD),
	waterP10LastSegmentD1Nominal: readFieldOneLiner('water_p10_last_segment_d1_nominal', NUMBER_FIELD),
	waterP10LastSegmentDiEffSec: readFieldOneLiner('water_p10_last_segment_di_eff_sec', NUMBER_FIELD),
	waterP10LastSegmentEndDate: readFieldOneLiner('water_p10_last_segment_end_date', STRING_FIELD),
	waterP10LastSegmentQEnd: readFieldOneLiner('water_p10_last_segment_q_end', NUMBER_FIELD),
	waterP10LastSegmentQStart: readFieldOneLiner('water_p10_last_segment_q_start', NUMBER_FIELD),
	waterP10LastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p10_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP10LastSegmentSegmentType: readFieldOneLiner('water_p10_last_segment_segment_type', STRING_FIELD),
	waterP10LastSegmentStartDate: readFieldOneLiner('water_p10_last_segment_start_date', STRING_FIELD),
	waterP10LastSegmentSwDate: readFieldOneLiner('water_p10_last_segment_sw_date', STRING_FIELD),
	waterP50FirstSegmentB: readFieldOneLiner('water_p50_first_segment_b', NUMBER_FIELD),
	waterP50FirstSegmentD1Nominal: readFieldOneLiner('water_p50_first_segment_d1_nominal', NUMBER_FIELD),
	waterP50FirstSegmentDiEffSec: readFieldOneLiner('water_p50_first_segment_di_eff_sec', NUMBER_FIELD),
	waterP50FirstSegmentEndDate: readFieldOneLiner('water_p50_first_segment_end_date', STRING_FIELD),
	waterP50FirstSegmentQEnd: readFieldOneLiner('water_p50_first_segment_q_end', NUMBER_FIELD),
	waterP50FirstSegmentQStart: readFieldOneLiner('water_p50_first_segment_q_start', NUMBER_FIELD),
	waterP50FirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p50_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP50FirstSegmentSegmentType: readFieldOneLiner('water_p50_first_segment_segment_type', STRING_FIELD),
	waterP50FirstSegmentStartDate: readFieldOneLiner('water_p50_first_segment_start_date', STRING_FIELD),
	waterP50FirstSegmentSwDate: readFieldOneLiner('water_p50_first_segment_sw_date', STRING_FIELD),
	waterP50LastSegmentB: readFieldOneLiner('water_p50_last_segment_b', NUMBER_FIELD),
	waterP50LastSegmentD1Nominal: readFieldOneLiner('water_p50_last_segment_d1_nominal', NUMBER_FIELD),
	waterP50LastSegmentDiEffSec: readFieldOneLiner('water_p50_last_segment_di_eff_sec', NUMBER_FIELD),
	waterP50LastSegmentEndDate: readFieldOneLiner('water_p50_last_segment_end_date', STRING_FIELD),
	waterP50LastSegmentQEnd: readFieldOneLiner('water_p50_last_segment_q_end', NUMBER_FIELD),
	waterP50LastSegmentQStart: readFieldOneLiner('water_p50_last_segment_q_start', NUMBER_FIELD),
	waterP50LastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p50_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP50LastSegmentSegmentType: readFieldOneLiner('water_p50_last_segment_segment_type', STRING_FIELD),
	waterP50LastSegmentStartDate: readFieldOneLiner('water_p50_last_segment_start_date', STRING_FIELD),
	waterP50LastSegmentSwDate: readFieldOneLiner('water_p50_last_segment_sw_date', STRING_FIELD),
	waterP90FirstSegmentB: readFieldOneLiner('water_p90_first_segment_b', NUMBER_FIELD),
	waterP90FirstSegmentD1Nominal: readFieldOneLiner('water_p90_first_segment_d1_nominal', NUMBER_FIELD),
	waterP90FirstSegmentDiEffSec: readFieldOneLiner('water_p90_first_segment_di_eff_sec', NUMBER_FIELD),
	waterP90FirstSegmentEndDate: readFieldOneLiner('water_p90_first_segment_end_date', STRING_FIELD),
	waterP90FirstSegmentQEnd: readFieldOneLiner('water_p90_first_segment_q_end', NUMBER_FIELD),
	waterP90FirstSegmentQStart: readFieldOneLiner('water_p90_first_segment_q_start', NUMBER_FIELD),
	waterP90FirstSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p90_first_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP90FirstSegmentSegmentType: readFieldOneLiner('water_p90_first_segment_segment_type', STRING_FIELD),
	waterP90FirstSegmentStartDate: readFieldOneLiner('water_p90_first_segment_start_date', STRING_FIELD),
	waterP90FirstSegmentSwDate: readFieldOneLiner('water_p90_first_segment_sw_date', STRING_FIELD),
	waterP90LastSegmentB: readFieldOneLiner('water_p90_last_segment_b', NUMBER_FIELD),
	waterP90LastSegmentD1Nominal: readFieldOneLiner('water_p90_last_segment_d1_nominal', NUMBER_FIELD),
	waterP90LastSegmentDiEffSec: readFieldOneLiner('water_p90_last_segment_di_eff_sec', NUMBER_FIELD),
	waterP90LastSegmentEndDate: readFieldOneLiner('water_p90_last_segment_end_date', STRING_FIELD),
	waterP90LastSegmentQEnd: readFieldOneLiner('water_p90_last_segment_q_end', NUMBER_FIELD),
	waterP90LastSegmentQStart: readFieldOneLiner('water_p90_last_segment_q_start', NUMBER_FIELD),
	waterP90LastSegmentRealizedDSwEffSec: readFieldOneLiner(
		'water_p90_last_segment_realized_d_sw_eff_sec',
		NUMBER_FIELD,
	),
	waterP90LastSegmentSegmentType: readFieldOneLiner('water_p90_last_segment_segment_type', STRING_FIELD),
	waterP90LastSegmentStartDate: readFieldOneLiner('water_p90_last_segment_start_date', STRING_FIELD),
	waterP90LastSegmentSwDate: readFieldOneLiner('water_p90_last_segment_sw_date', STRING_FIELD),
	waterWellHeadEur: readFieldOneLiner('water_well_head_eur', NUMBER_FIELD),
	waterProductionAsOfDate: readFieldOneLiner('water_production_as_of_date', NUMBER_FIELD),
	waterRisk: readFieldOneLiner('water_risk', NUMBER_FIELD),
	waterTcRisk: readFieldOneLiner('water_tc_risk', NUMBER_FIELD),
	waterWellHeadEurOverPll: readFieldOneLiner('water_well_head_eur_over_pll', NUMBER_FIELD),
	wellLife: readFieldOneLiner('well_life', NUMBER_FIELD),
	wetGasBoeConversion: readFieldOneLiner('wet_gas_boe_conversion', NUMBER_FIELD),
	wiBoeSalesVolume: readFieldOneLiner('wi_boe_sales_volume', NUMBER_FIELD),
	wiDripCondensate: readFieldOneLiner('wi_drip_condensate', NUMBER_FIELD),
	wiDripCondensateSalesVolume: readFieldOneLiner('wi_drip_condensate_sales_volume', NUMBER_FIELD),
	wiGas: readFieldOneLiner('wi_gas', NUMBER_FIELD),
	wiGasSalesVolume: readFieldOneLiner('wi_gas_sales_volume', NUMBER_FIELD),
	wiNgl: readFieldOneLiner('wi_ngl', NUMBER_FIELD),
	wiNglSalesVolume: readFieldOneLiner('wi_ngl_sales_volume', NUMBER_FIELD),
	wiOil: readFieldOneLiner('wi_oil', NUMBER_FIELD),
	wiOilSalesVolume: readFieldOneLiner('wi_oil_sales_volume', NUMBER_FIELD),
	wiMcfeSalesVolume: readFieldOneLiner('wi_mcfe_sales_volume', NUMBER_FIELD),
};

export const toApiOneLiner = (oneLiner: OneLinerData): ApiOneLiner => {
	const apiOneLiner: Record<string, ApiOneLiner[ApiOneLinerKey]> = {};
	Object.entries(API_ONE_LINER_FIELDS).forEach(([field, { read }]) => {
		if (read) {
			apiOneLiner[field] = read(oneLiner);
		}
	});
	return apiOneLiner;
};

type IEconRunDataField<T> = IField<IEconRunData, T>;

const getOneLinerData = (): IEconRunDataField<ApiOneLiner | undefined> => {
	return {
		type: OpenApiDataType.object,
		properties: API_ONE_LINER_FIELDS,
		read: (econRunData) => econRunData.oneLinerData && toApiOneLiner(econRunData.oneLinerData),
	};
};

const readEconRunDataField = <K extends keyof IEconRunData, TParsed = IEconRunData[K]>(
	key: K,
	definition: IFieldDefinition<TParsed>,
	options: IReadFieldOptions = {},
) => readDbField<IEconRunData, K, TParsed>(key, definition, options);

const readEconRunDataReservesCategoryField = <K extends keyof ReservesCategory, TParsed = ReservesCategory[K]>(
	key: K,
	definition: IFieldDefinition<TParsed>,
): IField<IEconRunData, ReservesCategory[K], TParsed> => ({
	...definition,
	read: (oneLiner) => oneLiner?.reservesCategory?.[key],
});

const API_ECON_RUN_DATA_FIELDS = {
	id: readEconRunDataField('_id', OBJECT_ID_FIELD, { sortable: true, allowCursor: true }),
	comboName: readEconRunDataField('comboName', STRING_FIELD, {
		filterOption: { read: { filterValues: 1 } },
		sortable: true,
	}),
	econPRMSResourcesClass: readEconRunDataReservesCategoryField('econ_prms_resources_class', STRING_FIELD),
	econPRMSReservesCategory: readEconRunDataReservesCategoryField('econ_prms_reserves_category', STRING_FIELD),
	econPRMSReservesSubCategory: readEconRunDataReservesCategoryField('econ_prms_reserves_sub_category', STRING_FIELD),
	econGroup: readEconRunDataField('groupName', STRING_FIELD),
	output: getOneLinerData(),
	well: readEconRunDataField('well', OBJECT_ID_FIELD, { filterOption: { read: { filterValues: 1 } } }),
};

export default API_ECON_RUN_DATA_FIELDS;

export type ApiEconRunDataKey = keyof typeof API_ECON_RUN_DATA_FIELDS;

type TypeOfField<FT> = FT extends IEconRunDataField<infer T> ? T : never;

export type ApiEconRunData = { [key in ApiEconRunDataKey]?: TypeOfField<(typeof API_ECON_RUN_DATA_FIELDS)[key]> };

export const toApiEconRunData = (econRunData: IEconRunData): ApiEconRunData => {
	const apiEconRunData: Record<string, ApiEconRunData[ApiEconRunDataKey]> = {};
	Object.entries(API_ECON_RUN_DATA_FIELDS).forEach(([field, { read }]) => {
		if (read) {
			apiEconRunData[field] = read(econRunData);
		}
	});
	return apiEconRunData;
};

export const getSort = (sort: ISort, cursor?: string): IApiSort | null =>
	getApiDbSort(sort, API_ECON_RUN_DATA_FIELDS, undefined, cursor);

export const sortableFields = sortableDbFields(API_ECON_RUN_DATA_FIELDS);

export const getFilters = (
	filters: ApiQueryFilters,
	project: BaseProjectResolved,
	scenarioId: Types.ObjectId,
	econRun: Pick<IEconRun, 'id' | 'runDate'>,
	cursor?: IFilter,
): IFilter =>
	getApiReadDbFilters(filters, API_ECON_RUN_DATA_FIELDS, {
		value: merge({ project: project._id, scenario: scenarioId, run: econRun.id }, cursor || {}),
	});

export const filterableFields = filterableReadDbFields(API_ECON_RUN_DATA_FIELDS);
