import numpy as np


def get_dtype_mapping(file_name, usecols):
    name = str(file_name.split('_df')[0]).upper()
    if name == 'FOR':
        dtype_mapping = {k: v for k, v in ALL_TABLE_DTYPE_MAPPING.get(name).items() if k in usecols}
    else:
        dtype_mapping = None

    return dtype_mapping


ALL_TABLE_DTYPE_MAPPING = {
    'ACT': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Ecogrpid': np.int16,
        'Exclsum': np.int16,
        'Exclcash': np.int16,
        'Exclvol': np.int16,
        'Countrycode': np.int16,
        'Curarcseq': np.int16,
        'Pdp Category': np.int16,
        'Rsv Class': np.int16,
        'Welltype': np.int16,
        'Casetype': np.int16,
        'Eval Model': np.int16,
        'Lse Name': object,
        'Major Phase': np.int16,
        'Fld': object,
        'Reservoir': object,
        'County': object,
        'State': object,
        'Country': object,
        'Oper': object,
        'Well': object,
        'Location': object,
        'Gasgath': object,
        'Oilgath': object,
        'Sop': np.int16,
        'Eop': np.int16,
        'Td': np.int16,
        'Depthunits': np.int16,
        'Lat': np.float16,
        'Long': np.float16,
        'Gradient': np.float16,
        'Tubingid': np.float16,
        'Acre Space': np.int16,
        'Areaunits': np.int16,
        'Temperatureunits': np.int16,
        'Prodcolumns[0]': np.int16,
        'Prodcolumns[1]': np.int16,
        'Prodcolumns[2]': np.int16,
        'Prodcolumns[3]': np.int16,
        'Prodcolumns[4]': np.int16,
        'Testcolumns[0]': np.int16,
        'Testcolumns[1]': np.int16,
        'Testcolumns[2]': np.int16,
        'Testcolumns[3]': np.int16,
        'Testcolumns[4]': np.int16,
        'Act:notes': object
    },
    'IDC': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Lblnum': np.int16,
        'Idval': object
    },
    'PNF': {
        'Rec No': np.int16,
        'Productcode': np.int16,
        'Descr': object
    },
    'ZON': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Type': np.int16,
        'Descr': object,
        'Zonnum': object,
        'Api Code': object,
        'Lperf': np.int16,
        'Uperf': np.int16
    },
    'VOL': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Sg': np.float16,
        'So': np.float16,
        'Sw': np.float16,
        'Bg': np.float16,
        'Bo': np.float16,
        'Rsi': np.float16,
        'Zi': np.float16,
        'Porosity': np.float16,
        'Drainarea': np.float16,
        'Thickness': np.float16,
        'Respress': np.float16,
        'Restemp': np.float16,
        'Gasrecovery': np.float16,
        'Oilrecovery': np.float16,
        'Gasult': np.float16,
        'Oilult': np.float16,
        'Gasinplace': np.float16,
        'Oilinplace': np.float16
    },
    'CLA': {
        'Rec No': np.int16,
        'Cla Id': np.int16,
        'Name': object,
        'Shortname': object,
        'Sortnum': np.int16,
        'Fixed': np.int16
    },
    'CAT': {
        'Rec No': np.int16,
        'Cat Id': np.int16,
        'Name': object,
        'Shortname': object,
        'Sortnum': np.int16,
        'Fixed': np.int16
    },
    'TST': {
        'Rec No': object,
        'Lse Id': object,
        'Type': object,
        'Sitp': object,
        'Sibhp': object,
        'Bhpz': object,
        'Ftp': object,
        'Tdate': object,
        'Mcfday': object,
        'Watday': object,
        'Bblday': object,
        'Csgpres': object,
        'Gp': object,
        'Op': object,
        'Wp': object,
        'Chokesize': object,
        'Zfactor': object,
        'Notes': object,
        'Sourcelseid': object
    },
    'DAT': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Type': np.int16,
        'Year': np.int16,
        'Prod1td': np.float16,
        'Prod2td': np.float16,
        'Prod3td': np.float16,
        'Prod4td': np.float16,
        'Prod5td': np.float16,
        'Prod1[0]': np.float16,
        'Prod1[1]': np.float16,
        'Prod1[2]': np.float16,
        'Prod1[3]': np.float16,
        'Prod1[4]': np.float16,
        'Prod1[5]': np.float16,
        'Prod1[6]': np.float16,
        'Prod1[7]': np.float16,
        'Prod1[8]': np.float16,
        'Prod1[9]': np.float16,
        'Prod1[10]': np.float16,
        'Prod1[11]': np.float16,
        'Prod2[0]': np.float16,
        'Prod2[1]': np.float16,
        'Prod2[2]': np.float16,
        'Prod2[3]': np.float16,
        'Prod2[4]': np.float16,
        'Prod2[5]': np.float16,
        'Prod2[6]': np.float16,
        'Prod2[7]': np.float16,
        'Prod2[8]': np.float16,
        'Prod2[9]': np.float16,
        'Prod2[10]': np.float16,
        'Prod2[11]': np.float16,
        'Prod3[0]': np.float16,
        'Prod3[1]': np.float16,
        'Prod3[2]': np.float16,
        'Prod3[3]': np.float16,
        'Prod3[4]': np.float16,
        'Prod3[5]': np.float16,
        'Prod3[6]': np.float16,
        'Prod3[7]': np.float16,
        'Prod3[8]': np.float16,
        'Prod3[9]': np.float16,
        'Prod3[10]': np.float16,
        'Prod3[11]': np.float16,
        'Prod4[0]': np.float16,
        'Prod4[1]': np.float16,
        'Prod4[2]': np.float16,
        'Prod4[3]': np.float16,
        'Prod4[4]': np.float16,
        'Prod4[5]': np.float16,
        'Prod4[6]': np.float16,
        'Prod4[7]': np.float16,
        'Prod4[8]': np.float16,
        'Prod4[9]': np.float16,
        'Prod4[10]': np.float16,
        'Prod4[11]': np.float16,
        'Prod5[0]': np.float16,
        'Prod5[1]': np.float16,
        'Prod5[2]': np.float16,
        'Prod5[3]': np.float16,
        'Prod5[4]': np.float16,
        'Prod5[5]': np.float16,
        'Prod5[6]': np.float16,
        'Prod5[7]': np.float16,
        'Prod5[8]': np.float16,
        'Prod5[9]': np.float16,
        'Prod5[10]': np.float16,
        'Prod5[11]': np.float16
    },
    'TIT': {
        'Rec No': np.int16,
        'Proj Descr': object,
        'Modelsubdir': object,
        'Modelid': np.int16,
        'Disfact': np.float16,
        'Titlefontsize': np.float16,
        'Shownotes': np.int16,
        'Asof Date': np.int16,
        'Disc Date': np.int16,
        'Discmeth': np.int16,
        'Numcompound': np.int16,
        'Lastlseid': np.int16,
        'Groupid': np.int16,
        'Fiscaleco': np.int16,
        'Endmoneco': np.int16,
        'Nummoneco': np.int16,
        'Maxecoyears': np.int16,
        'Btitle Lbl[0]': np.int16,
        'Btitle Lbl[1]': np.int16,
        'Btitle Lbl[2]': np.int16,
        'Btitle Lbl[3]': np.int16,
        'Btitle Lbl[4]': np.int16,
        'Btitle Lbl[5]': np.int16,
        'Btitle Lbl[6]': np.int16,
        'Btitle Lbl[7]': np.int16,
        'Btitle Lbl[8]': np.int16,
        'Ttitle Lbl[0]': np.int16,
        'Ttitle Lbl[1]': np.int16,
        'Ttitle Lbl[2]': np.int16,
        'Ttitle Lbl[3]': np.int16,
        'Ttitle Lbl[4]': np.int16,
        'Ttitle Lbl[5]': np.int16,
        'Ttitle Lbl[6]': np.int16,
        'Ttitle Lbl[7]': np.int16,
        'Ttitle Lbl[8]': np.int16,
        'Graphtitleson': np.int16,
        'Titlesconfig': np.int16,
        'Usingthreads[0]': np.int16,
        'Usingthreads[1]': np.int16,
        'Usingthreads[2]': np.int16,
        'Usingthreads[3]': np.int16,
        'Usingthreads[4]': np.int16,
        'Usingthreads[5]': np.int16,
        'Usingthreads[6]': np.int16,
        'Usingthreads[7]': np.int16,
        'Usingthreads[8]': np.int16,
        'Usingthreads[9]': np.int16,
        'Titswitch[0]': np.int16,
        'Titswitch[1]': np.int16,
        'Titswitch[2]': np.int16,
        'Titswitch[3]': np.int16,
        'Titswitch[4]': np.int16,
        'Titswitch[5]': np.int16,
        'Titswitch[6]': np.int16,
        'Titswitch[7]': np.int16,
        'Titswitch[8]': np.int16,
        'Titswitch[9]': np.int16,
        'Titswitch[10]': np.int16,
        'Titswitch[11]': np.int16,
        'Titswitch[12]': np.int16,
        'Titswitch[13]': np.int16,
        'Titswitch[14]': np.int16,
        'Titswitch[15]': np.int16,
        'Titswitch[16]': np.int16,
        'Titswitch[17]': np.int16,
        'Titswitch[18]': np.int16,
        'Titswitch[19]': np.int16,
        'Titswitch[20]': np.int16,
        'Titswitch[21]': np.int16,
        'Titswitch[22]': np.int16,
        'Titswitch[23]': np.int16,
        'Titswitch[24]': np.int16,
        'Titswitch[25]': np.int16,
        'Titswitch[26]': np.int16,
        'Titswitch[27]': np.int16,
        'Titswitch[28]': np.int16,
        'Titswitch[29]': np.int16,
        'Btitle Spec[0]': np.int16,
        'Btitle Spec[1]': np.int16,
        'Btitle Spec[2]': np.int16,
        'Btitle Spec[3]': np.int16,
        'Btitle Spec[4]': np.int16,
        'Btitle Spec[5]': np.int16,
        'Btitle Spec[6]': np.int16,
        'Btitle Spec[7]': np.int16,
        'Btitle Spec[8]': np.int16,
        'Ttitle Spec[0]': np.int16,
        'Ttitle Spec[1]': np.int16,
        'Ttitle Spec[2]': np.int16,
        'Ttitle Spec[3]': np.int16,
        'Ttitle Spec[4]': np.int16,
        'Ttitle Spec[5]': np.int16,
        'Ttitle Spec[6]': np.int16,
        'Ttitle Spec[7]': np.int16,
        'Ttitle Spec[8]': np.int16,
        'Btitle Text': object,
        'Ttitle Text': object,
        'Editmoddate': np.int16,
        'Editmodtime': np.int16,
        'Volnsysid': object,
        'Defcurrency': object,
        'Defconvention': np.int16,
        'Outputrevcol1': np.int16,
        'Outputrevcol2': np.int16,
        'Outputexpcol1': np.int16,
        'Outputexpcol2': np.int16,
        'Outputexptype1': np.int16,
        'Outputexptype2': np.int16,
        'Democode': np.int16,
        'Tit:proj Notes': object
    },
    'GCA': {
        'Rec No': np.int16,
        'Type': np.int16,
        'Cla Id': np.int16,
        'Modpointer': np.int16,
        'Startdate': np.int16,
        'Forwhom': object
    },
    'GCL': {
        'Rec No': np.int16,
        'Type': np.int16,
        'Cla Id': np.int16,
        'Seq': np.int16,
        'Length': np.int16,
        'Value': np.float16,
        'Allowancededuct': np.float16,
        'Crowndeduct': np.float16,
        'Freeholddeduct': np.float16
    },
    'ECF': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Pricesce': np.int16,
        'Expsce': np.int16,
        'Taxsce': np.int16,
        'Invinflation': np.int16,
        'Expinflation': np.int16,
        'Maxyrs': np.int16,
        'Errorok': np.int16,
        'Btupointer': np.int16,
        'Projoverdate': np.int16,
        'Killdate': np.int16,
        'Groupkill': np.int16,
        'Groupextend': np.int16,
        'Btu': np.float16,
        'Disfact': np.float16,
        'Lsevalue': np.float16,
        'Wrkvalue': np.float16,
        'Royvalue': np.float16,
        'Ror': np.float16,
        'Roi': np.float16,
        'Payout': np.float16,
        'Codes[0]': np.float16,
        'Codes[1]': np.float16,
        'Codes[2]': np.float16,
        'Codes[3]': np.float16,
        'Codes[4]': np.float16,
        'Codes[5]': np.float16,
        'Codes[6]': np.float16,
        'Codes[7]': np.float16,
        'Codes[8]': np.float16,
        'Codes[9]': np.float16,
        'Codes2[0]': np.float16,
        'Codes2[1]': np.float16,
        'Codes2[2]': np.float16,
        'Codes2[3]': np.float16,
        'Codes2[4]': np.float16,
        'Codes2[5]': np.float16,
        'Codes2[6]': np.float16,
        'Codes2[7]': np.float16,
        'Codes2[8]': np.float16,
        'Codes2[9]': np.float16,
        'Cutoffs[0]': np.float16,
        'Cutoffs[1]': np.float16,
        'Cutoffs[2]': np.float16,
        'Cutoffs[3]': np.float16,
        'Cutoffs[4]': np.float16,
        'Cutoffs[5]': np.float16,
        'Cutoffs[6]': np.float16,
        'Cutoffs[7]': np.float16,
        'Cutoffenable[0]': np.int16,
        'Cutoffenable[1]': np.int16,
        'Cutoffenable[2]': np.int16,
        'Cutoffenable[3]': np.int16,
        'Cutoffenable[4]': np.int16,
        'Cutoffenable[5]': np.int16,
        'Cutoffenable[6]': np.int16,
        'Cutoffenable[7]': np.int16,
        'Rcmpparent': np.int16,
        'Rcmpoffset': np.int16,
        'Rcmplinks[0]': np.int16,
        'Rcmplinks[1]': np.int16,
        'Rcmplinks[2]': np.int16,
        'Rcmplinks[3]': np.int16,
        'Rcmplinks[4]': np.int16,
        'Rcmplinks[5]': np.int16,
        'Rcmplinks[6]': np.int16,
        'Rcmplinks[7]': np.int16,
        'Rcmplinks[8]': np.int16,
        'Rcmplinks[9]': np.int16,
        'Rcmplinks[10]': np.int16,
        'Rcmplinks[11]': np.int16,
        'Rcmplinks[12]': np.int16,
        'Rcmplinks[13]': np.int16,
        'Rcmplinks[14]': np.int16,
        'Rcmplinks[15]': np.int16,
        'Rcmplinks[16]': np.int16,
        'Rcmplinks[17]': np.int16,
        'Rcmplinks[18]': np.int16,
        'Rcmplinks[19]': np.int16,
        'Exp Block': np.int16,
        'Price Block': np.int16,
        'Sevtaxmode': np.int16,
        'Advtaxmode': np.int16,
        'Currency': object
    },
    'FLU': {
        'Rec No': object,
        'Lse Id': object,
        'Analydate': object,
        'Byconst': object,
        'Bygravity': object,
        'Condensate': object,
        'C1': object,
        'C2': object,
        'C3': object,
        'Ic4': object,
        'Nc4': object,
        'Ic5': object,
        'Nc5': object,
        'Nc6': object,
        'Nc7': object,
        'Nc8': object,
        'Nc9': object,
        'Nc10': object,
        'N2': object,
        'Co2': object,
        'H2s': object,
        'O2': object,
        'H2': object,
        'He': object,
        'H2o': object,
        'Respress': object,
        'Restemp': object,
        'B Temp': object,
        'B Press': object,
        'Initialanal': object,
        'Ggravity': object,
        'Gsgravity': object,
        'Tcriticalg': object,
        'Presscriticalg': object,
        'Tcriticalo': object,
        'Presscriticalo': object,
        'Netheat': object,
        'Grossheat': object,
        'Grossheatw': object,
        'Oilgravity': object,
        'Gor': object,
        'Rsi': object,
        'Seppress': object,
        'Septemp': object,
        'Bp': object,
        'Bg': object,
        'Bg Ovr': object,
        'Bo': object,
        'Bo Ovr': object,
        'Bt': object,
        'Bt Ovr': object,
        'Por': object,
        'Por Ovr': object,
        'Sg': object,
        'So': object,
        'Sw': object,
        'Tboil': object,
        'Co': object,
        'Cg': object,
        'Cw': object,
        'Z': object,
        'Oilud': object,
        'Oilul': object,
        'Mwg': object,
        'Mwo': object,
        'Gasu': object,
        'Bw': object,
        'Rsw': object,
        'Nacl': object,
        'Cfr': object,
        'Tic': object,
        'Uw': object,
        'Restype': object
    },
    'FOR': {
        'Begcum[0]': np.float16,
        'Begcum[1]': np.float16,
        'Begcum[2]': np.float16,
        'Begcum[3]': np.float16,
        'Begcum[4]': np.float16,
        'Begcum[5]': np.float16,
        'Begcum[6]': np.float16,
        'Begcum[7]': np.float16,
        'Begcum[8]': np.float16,
        'Begcum[9]': np.float16,
        'Endcum[0]': np.float16,
        'Endcum[1]': np.float16,
        'Endcum[2]': np.float16,
        'Endcum[3]': np.float16,
        'Endcum[4]': np.float16,
        'Endcum[5]': np.float16,
        'Endcum[6]': np.float16,
        'Endcum[7]': np.float16,
        'Endcum[8]': np.float16,
        'Endcum[9]': np.float16,
        'Productrisk[0]': np.float16,
        'Productrisk[1]': np.float16,
        'Productrisk[2]': np.float16,
        'Productrisk[3]': np.float16,
        'Productrisk[4]': np.float16,
        'Productrisk[5]': np.float16,
        'Productrisk[6]': np.float16,
        'Productrisk[7]': np.float16,
        'Productrisk[8]': np.float16,
        'Productrisk[9]': np.float16,
        'Cumvol': np.float32,
        'Remvol': np.float32,
        'Eurvol': np.float32,
        'Streamswitch[0]': np.int16,
        'Streamswitch[1]': np.int16,
        'Streamswitch[2]': np.int16,
        'Streamswitch[3]': np.int16,
        'Streamswitch[4]': np.int16,
        'Streamswitch[5]': np.int16,
        'Streamswitch[6]': np.int16,
        'Streamswitch[7]': np.int16,
        'Streamswitch[8]': np.int16,
        'Streamswitch[9]': np.int16,
        'Streamswitch[10]': np.int16,
        'Streamswitch[11]': np.int16,
        'Streamswitch[12]': np.int16,
        'Streamswitch[13]': np.int16,
        'Streamswitch[14]': np.int16,
        'Streamswitch[15]': np.int16,
        'Streamswitch[16]': np.int16,
        'Streamswitch[17]': np.int16,
        'Streamswitch[18]': np.int16,
        'Streamswitch[19]': np.int16,
        'Histsym': np.int16,
        'Projsym': np.int16,
        'Projoverhist': np.int16,
        'Balance': np.float16,
        'Dateofbalance': np.int16,
        'Numcount': np.int16,
        'Numform[0].VALUETYPE': np.int16,
        'Numform[0].PCODE': np.int16,
        'Numform[0].PRODVALTYPE': np.int16,
        'Numform[0].ACTION': np.int16,
        'Numform[0].VALUEREAL': np.float32,
        'Numform[0].DATEVAL': np.int16,
        'Numform[1].VALUETYPE': np.int16,
        'Numform[1].PCODE': np.int16,
        'Numform[1].PRODVALTYPE': np.int16,
        'Numform[1].ACTION': np.int16,
        'Numform[1].VALUEREAL': np.float32,
        'Numform[1].DATEVAL': np.int16,
        'Numform[2].VALUETYPE': np.int16,
        'Numform[2].PCODE': np.int16,
        'Numform[2].PRODVALTYPE': np.int16,
        'Numform[2].ACTION': np.int16,
        'Numform[2].VALUEREAL': np.float32,
        'Numform[2].DATEVAL': np.int16,
        'Numform[3].VALUETYPE': np.int16,
        'Numform[3].PCODE': np.int16,
        'Numform[3].PRODVALTYPE': np.int16,
        'Numform[3].ACTION': np.int16,
        'Numform[3].VALUEREAL': np.float32,
        'Numform[3].DATEVAL': np.int16,
        'Numform[4].VALUETYPE': np.int16,
        'Numform[4].PCODE': np.int16,
        'Numform[4].PRODVALTYPE': np.int16,
        'Numform[4].ACTION': np.int16,
        'Numform[4].VALUEREAL': np.float32,
        'Numform[4].DATEVAL': np.int16,
        'Numform[5].VALUETYPE': np.int16,
        'Numform[5].PCODE': np.int16,
        'Numform[5].PRODVALTYPE': np.int16,
        'Numform[5].ACTION': np.int16,
        'Numform[5].VALUEREAL': np.float32,
        'Numform[5].DATEVAL': np.int16,
        'Numform[6].VALUETYPE': np.int16,
        'Numform[6].PCODE': np.int16,
        'Numform[6].PRODVALTYPE': np.int16,
        'Numform[6].ACTION': np.int16,
        'Numform[6].VALUEREAL': np.float32,
        'Numform[6].DATEVAL': np.int16,
        'Numform[7].VALUETYPE': np.int16,
        'Numform[7].PCODE': np.int16,
        'Numform[7].PRODVALTYPE': np.int16,
        'Numform[7].ACTION': np.int16,
        'Numform[7].VALUEREAL': np.float32,
        'Numform[7].DATEVAL': np.int16,
        'Numform[8].VALUETYPE': np.int16,
        'Numform[8].PCODE': np.int16,
        'Numform[8].PRODVALTYPE': np.int16,
        'Numform[8].ACTION': np.int16,
        'Numform[8].VALUEREAL': np.float32,
        'Numform[8].DATEVAL': np.int16,
        'Numform[9].VALUETYPE': np.int16,
        'Numform[9].PCODE': np.int16,
        'Numform[9].PRODVALTYPE': np.int16,
        'Numform[9].ACTION': np.int16,
        'Numform[9].VALUEREAL': np.float32,
        'Numform[9].DATEVAL': np.int16,
        'Numform[10].VALUETYPE': np.int16,
        'Numform[10].PCODE': np.int16,
        'Numform[10].PRODVALTYPE': np.int16,
        'Numform[10].ACTION': np.int16,
        'Numform[10].VALUEREAL': np.float32,
        'Numform[10].DATEVAL': np.int16,
        'Numform[11].VALUETYPE': np.int16,
        'Numform[11].PCODE': np.int16,
        'Numform[11].PRODVALTYPE': np.int16,
        'Numform[11].ACTION': np.int16,
        'Numform[11].VALUEREAL': np.float32,
        'Numform[11].DATEVAL': np.int16,
        'Numform[12].VALUETYPE': np.int16,
        'Numform[12].PCODE': np.int16,
        'Numform[12].PRODVALTYPE': np.int16,
        'Numform[12].ACTION': np.int16,
        'Numform[12].VALUEREAL': np.float32,
        'Numform[12].DATEVAL': np.int16,
        'Numform[13].VALUETYPE': np.int16,
        'Numform[13].PCODE': np.int16,
        'Numform[13].PRODVALTYPE': np.int16,
        'Numform[13].ACTION': np.int16,
        'Numform[13].VALUEREAL': np.float32,
        'Numform[13].DATEVAL': np.int16,
        'Numform[14].VALUETYPE': np.int16,
        'Numform[14].PCODE': np.int16,
        'Numform[14].PRODVALTYPE': np.int16,
        'Numform[14].ACTION': np.int16,
        'Numform[14].VALUEREAL': np.float32,
        'Numform[14].DATEVAL': np.int16,
        'Numform[15].VALUETYPE': np.int16,
        'Numform[15].PCODE': np.int16,
        'Numform[15].PRODVALTYPE': np.int16,
        'Numform[15].ACTION': np.int16,
        'Numform[15].VALUEREAL': np.float32,
        'Numform[15].DATEVAL': np.int16,
        'Numform[16].VALUETYPE': np.int16,
        'Numform[16].PCODE': np.int16,
        'Numform[16].PRODVALTYPE': np.int16,
        'Numform[16].ACTION': np.int16,
        'Numform[16].VALUEREAL': np.float32,
        'Numform[16].DATEVAL': np.int16,
        'Numform[17].VALUETYPE': np.int16,
        'Numform[17].PCODE': np.int16,
        'Numform[17].PRODVALTYPE': np.int16,
        'Numform[17].ACTION': np.int16,
        'Numform[17].VALUEREAL': np.float32,
        'Numform[17].DATEVAL': np.int16,
        'Numform[18].VALUETYPE': np.int16,
        'Numform[18].PCODE': np.int16,
        'Numform[18].PRODVALTYPE': np.int16,
        'Numform[18].ACTION': np.int16,
        'Numform[18].VALUEREAL': np.float32,
        'Numform[18].DATEVAL': np.int16,
        'Numform[19].VALUETYPE': np.int16,
        'Numform[19].PCODE': np.int16,
        'Numform[19].PRODVALTYPE': np.int16,
        'Numform[19].ACTION': np.int16,
        'Numform[19].VALUEREAL': np.float32,
        'Numform[19].DATEVAL': np.int16,
        'Numform[20].VALUETYPE': np.int16,
        'Numform[20].PCODE': np.int16,
        'Numform[20].PRODVALTYPE': np.int16,
        'Numform[20].ACTION': np.int16,
        'Numform[20].VALUEREAL': np.float32,
        'Numform[20].DATEVAL': np.int16,
        'Numform[21].VALUETYPE': np.int16,
        'Numform[21].PCODE': np.int16,
        'Numform[21].PRODVALTYPE': np.int16,
        'Numform[21].ACTION': np.int16,
        'Numform[21].VALUEREAL': np.float32,
        'Numform[21].DATEVAL': np.int16,
        'Numform[22].VALUETYPE': np.int16,
        'Numform[22].PCODE': np.int16,
        'Numform[22].PRODVALTYPE': np.int16,
        'Numform[22].ACTION': np.int16,
        'Numform[22].VALUEREAL': np.float32,
        'Numform[22].DATEVAL': np.int16,
        'Numform[23].VALUETYPE': np.int16,
        'Numform[23].PCODE': np.int16,
        'Numform[23].PRODVALTYPE': np.int16,
        'Numform[23].ACTION': np.int16,
        'Numform[23].VALUEREAL': np.float32,
        'Numform[23].DATEVAL': np.int16,
        'Numform[24].VALUETYPE': np.int16,
        'Numform[24].PCODE': np.int16,
        'Numform[24].PRODVALTYPE': np.int16,
        'Numform[24].ACTION': np.int16,
        'Numform[24].VALUEREAL': np.float32,
        'Numform[24].DATEVAL': np.int16,
        'Numform[25].VALUETYPE': np.int16,
        'Numform[25].PCODE': np.int16,
        'Numform[25].PRODVALTYPE': np.int16,
        'Numform[25].ACTION': np.int16,
        'Numform[25].VALUEREAL': np.float32,
        'Numform[25].DATEVAL': np.int16,
        'Numform[26].VALUETYPE': np.int16,
        'Numform[26].PCODE': np.int16,
        'Numform[26].PRODVALTYPE': np.int16,
        'Numform[26].ACTION': np.int16,
        'Numform[26].VALUEREAL': np.float32,
        'Numform[26].DATEVAL': np.int16,
        'Numform[27].VALUETYPE': np.int16,
        'Numform[27].PCODE': np.int16,
        'Numform[27].PRODVALTYPE': np.int16,
        'Numform[27].ACTION': np.int16,
        'Numform[27].VALUEREAL': np.float32,
        'Numform[27].DATEVAL': np.int16,
        'Numform[28].VALUETYPE': np.int16,
        'Numform[28].PCODE': np.int16,
        'Numform[28].PRODVALTYPE': np.int16,
        'Numform[28].ACTION': np.int16,
        'Numform[28].VALUEREAL': np.float32,
        'Numform[28].DATEVAL': np.int16,
        'Numform[29].VALUETYPE': np.int16,
        'Numform[29].PCODE': np.int16,
        'Numform[29].PRODVALTYPE': np.int16,
        'Numform[29].ACTION': np.int16,
        'Numform[29].VALUEREAL': np.float32,
        'Numform[29].DATEVAL': np.int16,
        'Numform[30].VALUETYPE': np.int16,
        'Numform[30].PCODE': np.int16,
        'Numform[30].PRODVALTYPE': np.int16,
        'Numform[30].ACTION': np.int16,
        'Numform[30].VALUEREAL': np.float32,
        'Numform[30].DATEVAL': np.int16,
        'Numform[31].VALUETYPE': np.int16,
        'Numform[31].PCODE': np.int16,
        'Numform[31].PRODVALTYPE': np.int16,
        'Numform[31].ACTION': np.int16,
        'Numform[31].VALUEREAL': np.float32,
        'Numform[31].DATEVAL': np.int16,
        'Numform[32].VALUETYPE': np.int16,
        'Numform[32].PCODE': np.int16,
        'Numform[32].PRODVALTYPE': np.int16,
        'Numform[32].ACTION': np.int16,
        'Numform[32].VALUEREAL': np.float32,
        'Numform[32].DATEVAL': np.int16,
        'Numform[33].VALUETYPE': np.int16,
        'Numform[33].PCODE': np.int16,
        'Numform[33].PRODVALTYPE': np.int16,
        'Numform[33].ACTION': np.int16,
        'Numform[33].VALUEREAL': np.float32,
        'Numform[33].DATEVAL': np.int16,
        'Numform[34].VALUETYPE': np.int16,
        'Numform[34].PCODE': np.int16,
        'Numform[34].PRODVALTYPE': np.int16,
        'Numform[34].ACTION': np.int16,
        'Numform[34].VALUEREAL': np.float32,
        'Numform[34].DATEVAL': np.int16,
        'Numform[35].VALUETYPE': np.int16,
        'Numform[35].PCODE': np.int16,
        'Numform[35].PRODVALTYPE': np.int16,
        'Numform[35].ACTION': np.int16,
        'Numform[35].VALUEREAL': np.float32,
        'Numform[35].DATEVAL': np.int16,
        'Numform[36].VALUETYPE': np.int16,
        'Numform[36].PCODE': np.int16,
        'Numform[36].PRODVALTYPE': np.int16,
        'Numform[36].ACTION': np.int16,
        'Numform[36].VALUEREAL': np.float32,
        'Numform[36].DATEVAL': np.int16,
        'Numform[37].VALUETYPE': np.int16,
        'Numform[37].PCODE': np.int16,
        'Numform[37].PRODVALTYPE': np.int16,
        'Numform[37].ACTION': np.int16,
        'Numform[37].VALUEREAL': np.float32,
        'Numform[37].DATEVAL': np.int16,
        'Numform[38].VALUETYPE': np.int16,
        'Numform[38].PCODE': np.int16,
        'Numform[38].PRODVALTYPE': np.int16,
        'Numform[38].ACTION': np.int16,
        'Numform[38].VALUEREAL': np.float32,
        'Numform[38].DATEVAL': np.int16,
        'Numform[39].VALUETYPE': np.int16,
        'Numform[39].PCODE': np.int16,
        'Numform[39].PRODVALTYPE': np.int16,
        'Numform[39].ACTION': np.int16,
        'Numform[39].VALUEREAL': np.float32,
        'Numform[39].DATEVAL': np.int16,
        'Numform[40].VALUETYPE': np.int16,
        'Numform[40].PCODE': np.int16,
        'Numform[40].PRODVALTYPE': np.int16,
        'Numform[40].ACTION': np.int16,
        'Numform[40].VALUEREAL': np.float32,
        'Numform[40].DATEVAL': np.int16,
        'Numform[41].VALUETYPE': np.int16,
        'Numform[41].PCODE': np.int16,
        'Numform[41].PRODVALTYPE': np.int16,
        'Numform[41].ACTION': np.int16,
        'Numform[41].VALUEREAL': np.float32,
        'Numform[41].DATEVAL': np.int16,
        'Numform[42].VALUETYPE': np.int16,
        'Numform[42].PCODE': np.int16,
        'Numform[42].PRODVALTYPE': np.int16,
        'Numform[42].ACTION': np.int16,
        'Numform[42].VALUEREAL': np.float32,
        'Numform[42].DATEVAL': np.int16,
        'Numform[43].VALUETYPE': np.int16,
        'Numform[43].PCODE': np.int16,
        'Numform[43].PRODVALTYPE': np.int16,
        'Numform[43].ACTION': np.int16,
        'Numform[43].VALUEREAL': np.float32,
        'Numform[43].DATEVAL': np.int16,
        'Numform[44].VALUETYPE': np.int16,
        'Numform[44].PCODE': np.int16,
        'Numform[44].PRODVALTYPE': np.int16,
        'Numform[44].ACTION': np.int16,
        'Numform[44].VALUEREAL': np.float32,
        'Numform[44].DATEVAL': np.int16,
        'Numform[45].VALUETYPE': np.int16,
        'Numform[45].PCODE': np.int16,
        'Numform[45].PRODVALTYPE': np.int16,
        'Numform[45].ACTION': np.int16,
        'Numform[45].VALUEREAL': np.float32,
        'Numform[45].DATEVAL': np.int16,
        'Numform[46].VALUETYPE': np.int16,
        'Numform[46].PCODE': np.int16,
        'Numform[46].PRODVALTYPE': np.int16,
        'Numform[46].ACTION': np.int16,
        'Numform[46].VALUEREAL': np.float32,
        'Numform[46].DATEVAL': np.int16,
        'Numform[47].VALUETYPE': np.int16,
        'Numform[47].PCODE': np.int16,
        'Numform[47].PRODVALTYPE': np.int16,
        'Numform[47].ACTION': np.int16,
        'Numform[47].VALUEREAL': np.float32,
        'Numform[47].DATEVAL': np.int16,
        'Numform[48].VALUETYPE': np.int16,
        'Numform[48].PCODE': np.int16,
        'Numform[48].PRODVALTYPE': np.int16,
        'Numform[48].ACTION': np.int16,
        'Numform[48].VALUEREAL': np.float32,
        'Numform[48].DATEVAL': np.int16,
        'Numform[49].VALUETYPE': np.int16,
        'Numform[49].PCODE': np.int16,
        'Numform[49].PRODVALTYPE': np.int16,
        'Numform[49].ACTION': np.int16,
        'Numform[49].VALUEREAL': np.float32,
        'Numform[49].DATEVAL': np.int16,
        'Numform[50].VALUETYPE': np.int16,
        'Numform[50].PCODE': np.int16,
        'Numform[50].PRODVALTYPE': np.int16,
        'Numform[50].ACTION': np.int16,
        'Numform[50].VALUEREAL': np.float32,
        'Numform[50].DATEVAL': np.int16,
        'Numform[51].VALUETYPE': np.int16,
        'Numform[51].PCODE': np.int16,
        'Numform[51].PRODVALTYPE': np.int16,
        'Numform[51].ACTION': np.int16,
        'Numform[51].VALUEREAL': np.float32,
        'Numform[51].DATEVAL': np.int16,
        'Numform[52].VALUETYPE': np.int16,
        'Numform[52].PCODE': np.int16,
        'Numform[52].PRODVALTYPE': np.int16,
        'Numform[52].ACTION': np.int16,
        'Numform[52].VALUEREAL': np.float32,
        'Numform[52].DATEVAL': np.int16,
        'Numform[53].VALUETYPE': np.int16,
        'Numform[53].PCODE': np.int16,
        'Numform[53].PRODVALTYPE': np.int16,
        'Numform[53].ACTION': np.int16,
        'Numform[53].VALUEREAL': np.float32,
        'Numform[53].DATEVAL': np.int16,
        'Numform[54].VALUETYPE': np.int16,
        'Numform[54].PCODE': np.int16,
        'Numform[54].PRODVALTYPE': np.int16,
        'Numform[54].ACTION': np.int16,
        'Numform[54].VALUEREAL': np.float32,
        'Numform[54].DATEVAL': np.int16,
        'Numform[55].VALUETYPE': np.int16,
        'Numform[55].PCODE': np.int16,
        'Numform[55].PRODVALTYPE': np.int16,
        'Numform[55].ACTION': np.int16,
        'Numform[55].VALUEREAL': np.float32,
        'Numform[55].DATEVAL': np.int16,
        'Numform[56].VALUETYPE': np.int16,
        'Numform[56].PCODE': np.int16,
        'Numform[56].PRODVALTYPE': np.int16,
        'Numform[56].ACTION': np.int16,
        'Numform[56].VALUEREAL': np.float32,
        'Numform[56].DATEVAL': np.int16,
        'Numform[57].VALUETYPE': np.int16,
        'Numform[57].PCODE': np.int16,
        'Numform[57].PRODVALTYPE': np.int16,
        'Numform[57].ACTION': np.int16,
        'Numform[57].VALUEREAL': np.float32,
        'Numform[57].DATEVAL': np.int16,
        'Numform[58].VALUETYPE': np.int16,
        'Numform[58].PCODE': np.int16,
        'Numform[58].PRODVALTYPE': np.int16,
        'Numform[58].ACTION': np.int16,
        'Numform[58].VALUEREAL': np.float32,
        'Numform[58].DATEVAL': np.int16,
        'Numform[59].VALUETYPE': np.int16,
        'Numform[59].PCODE': np.int16,
        'Numform[59].PRODVALTYPE': np.int16,
        'Numform[59].ACTION': np.int16,
        'Numform[59].VALUEREAL': np.float32,
        'Numform[59].DATEVAL': np.int16,
        'Numform[60].VALUETYPE': np.int16,
        'Numform[60].PCODE': np.int16,
        'Numform[60].PRODVALTYPE': np.int16,
        'Numform[60].ACTION': np.int16,
        'Numform[60].VALUEREAL': np.float32,
        'Numform[60].DATEVAL': np.int16,
        'Numform[61].VALUETYPE': np.int16,
        'Numform[61].PCODE': np.int16,
        'Numform[61].PRODVALTYPE': np.int16,
        'Numform[61].ACTION': np.int16,
        'Numform[61].VALUEREAL': np.float32,
        'Numform[61].DATEVAL': np.int16,
        'Numform[62].VALUETYPE': np.int16,
        'Numform[62].PCODE': np.int16,
        'Numform[62].PRODVALTYPE': np.int16,
        'Numform[62].ACTION': np.int16,
        'Numform[62].VALUEREAL': np.float32,
        'Numform[62].DATEVAL': np.int16,
        'Numform[63].VALUETYPE': np.int16,
        'Numform[63].PCODE': np.int16,
        'Numform[63].PRODVALTYPE': np.int16,
        'Numform[63].ACTION': np.int16,
        'Numform[63].VALUEREAL': np.float32,
        'Numform[63].DATEVAL': np.int16,
        'Numform[64].VALUETYPE': np.int16,
        'Numform[64].PCODE': np.int16,
        'Numform[64].PRODVALTYPE': np.int16,
        'Numform[64].ACTION': np.int16,
        'Numform[64].VALUEREAL': np.float32,
        'Numform[64].DATEVAL': np.int16,
        'Numform[65].VALUETYPE': np.int16,
        'Numform[65].PCODE': np.int16,
        'Numform[65].PRODVALTYPE': np.int16,
        'Numform[65].ACTION': np.int16,
        'Numform[65].VALUEREAL': np.float32,
        'Numform[65].DATEVAL': np.int16,
        'Numform[66].VALUETYPE': np.int16,
        'Numform[66].PCODE': np.int16,
        'Numform[66].PRODVALTYPE': np.int16,
        'Numform[66].ACTION': np.int16,
        'Numform[66].VALUEREAL': np.float32,
        'Numform[66].DATEVAL': np.int16,
        'Numform[67].VALUETYPE': np.int16,
        'Numform[67].PCODE': np.int16,
        'Numform[67].PRODVALTYPE': np.int16,
        'Numform[67].ACTION': np.int16,
        'Numform[67].VALUEREAL': np.float32,
        'Numform[67].DATEVAL': np.int16,
        'Numform[68].VALUETYPE': np.int16,
        'Numform[68].PCODE': np.int16,
        'Numform[68].PRODVALTYPE': np.int16,
        'Numform[68].ACTION': np.int16,
        'Numform[68].VALUEREAL': np.float32,
        'Numform[68].DATEVAL': np.int16,
        'Numform[69].VALUETYPE': np.int16,
        'Numform[69].PCODE': np.int16,
        'Numform[69].PRODVALTYPE': np.int16,
        'Numform[69].ACTION': np.int16,
        'Numform[69].VALUEREAL': np.float32,
        'Numform[69].DATEVAL': np.int16,
        'Numform[70].VALUETYPE': np.int16,
        'Numform[70].PCODE': np.int16,
        'Numform[70].PRODVALTYPE': np.int16,
        'Numform[70].ACTION': np.int16,
        'Numform[70].VALUEREAL': np.float32,
        'Numform[70].DATEVAL': np.int16,
        'Numform[71].VALUETYPE': np.int16,
        'Numform[71].PCODE': np.int16,
        'Numform[71].PRODVALTYPE': np.int16,
        'Numform[71].ACTION': np.int16,
        'Numform[71].VALUEREAL': np.float32,
        'Numform[71].DATEVAL': np.int16,
        'Numform[72].VALUETYPE': np.int16,
        'Numform[72].PCODE': np.int16,
        'Numform[72].PRODVALTYPE': np.int16,
        'Numform[72].ACTION': np.int16,
        'Numform[72].VALUEREAL': np.float32,
        'Numform[72].DATEVAL': np.int16,
        'Numform[73].VALUETYPE': np.int16,
        'Numform[73].PCODE': np.int16,
        'Numform[73].PRODVALTYPE': np.int16,
        'Numform[73].ACTION': np.int16,
        'Numform[73].VALUEREAL': np.float32,
        'Numform[73].DATEVAL': np.int16,
        'Numform[74].VALUETYPE': np.int16,
        'Numform[74].PCODE': np.int16,
        'Numform[74].PRODVALTYPE': np.int16,
        'Numform[74].ACTION': np.int16,
        'Numform[74].VALUEREAL': np.float32,
        'Numform[74].DATEVAL': np.int16,
        'Numform[75].VALUETYPE': np.int16,
        'Numform[75].PCODE': np.int16,
        'Numform[75].PRODVALTYPE': np.int16,
        'Numform[75].ACTION': np.int16,
        'Numform[75].VALUEREAL': np.float32,
        'Numform[75].DATEVAL': np.int16,
        'Numform[76].VALUETYPE': np.int16,
        'Numform[76].PCODE': np.int16,
        'Numform[76].PRODVALTYPE': np.int16,
        'Numform[76].ACTION': np.int16,
        'Numform[76].VALUEREAL': np.float32,
        'Numform[76].DATEVAL': np.int16,
        'Numform[77].VALUETYPE': np.int16,
        'Numform[77].PCODE': np.int16,
        'Numform[77].PRODVALTYPE': np.int16,
        'Numform[77].ACTION': np.int16,
        'Numform[77].VALUEREAL': np.float32,
        'Numform[77].DATEVAL': np.int16,
        'Numform[78].VALUETYPE': np.int16,
        'Numform[78].PCODE': np.int16,
        'Numform[78].PRODVALTYPE': np.int16,
        'Numform[78].ACTION': np.int16,
        'Numform[78].VALUEREAL': np.float32,
        'Numform[78].DATEVAL': np.int16,
        'Numform[79].VALUETYPE': np.int16,
        'Numform[79].PCODE': np.int16,
        'Numform[79].PRODVALTYPE': np.int16,
        'Numform[79].ACTION': np.int16,
        'Numform[79].VALUEREAL': np.float32,
        'Numform[79].DATEVAL': np.int16,
        'Numform[80].VALUETYPE': np.int16,
        'Numform[80].PCODE': np.int16,
        'Numform[80].PRODVALTYPE': np.int16,
        'Numform[80].ACTION': np.int16,
        'Numform[80].VALUEREAL': np.float32,
        'Numform[80].DATEVAL': np.int16,
        'Numform[81].VALUETYPE': np.int16,
        'Numform[81].PCODE': np.int16,
        'Numform[81].PRODVALTYPE': np.int16,
        'Numform[81].ACTION': np.int16,
        'Numform[81].VALUEREAL': np.float32,
        'Numform[81].DATEVAL': np.int16,
        'Numform[82].VALUETYPE': np.int16,
        'Numform[82].PCODE': np.int16,
        'Numform[82].PRODVALTYPE': np.int16,
        'Numform[82].ACTION': np.int16,
        'Numform[82].VALUEREAL': np.float32,
        'Numform[82].DATEVAL': np.int16,
        'Numform[83].VALUETYPE': np.int16,
        'Numform[83].PCODE': np.int16,
        'Numform[83].PRODVALTYPE': np.int16,
        'Numform[83].ACTION': np.int16,
        'Numform[83].VALUEREAL': np.float32,
        'Numform[83].DATEVAL': np.int16,
        'Numform[84].VALUETYPE': np.int16,
        'Numform[84].PCODE': np.int16,
        'Numform[84].PRODVALTYPE': np.int16,
        'Numform[84].ACTION': np.int16,
        'Numform[84].VALUEREAL': np.float32,
        'Numform[84].DATEVAL': np.int16,
        'Numform[85].VALUETYPE': np.int16,
        'Numform[85].PCODE': np.int16,
        'Numform[85].PRODVALTYPE': np.int16,
        'Numform[85].ACTION': np.int16,
        'Numform[85].VALUEREAL': np.float32,
        'Numform[85].DATEVAL': np.int16,
        'Numform[86].VALUETYPE': np.int16,
        'Numform[86].PCODE': np.int16,
        'Numform[86].PRODVALTYPE': np.int16,
        'Numform[86].ACTION': np.int16,
        'Numform[86].VALUEREAL': np.float32,
        'Numform[86].DATEVAL': np.int16,
        'Numform[87].VALUETYPE': np.int16,
        'Numform[87].PCODE': np.int16,
        'Numform[87].PRODVALTYPE': np.int16,
        'Numform[87].ACTION': np.int16,
        'Numform[87].VALUEREAL': np.float32,
        'Numform[87].DATEVAL': np.int16,
        'Numform[88].VALUETYPE': np.int16,
        'Numform[88].PCODE': np.int16,
        'Numform[88].PRODVALTYPE': np.int16,
        'Numform[88].ACTION': np.int16,
        'Numform[88].VALUEREAL': np.float32,
        'Numform[88].DATEVAL': np.int16,
        'Numform[89].VALUETYPE': np.int16,
        'Numform[89].PCODE': np.int16,
        'Numform[89].PRODVALTYPE': np.int16,
        'Numform[89].ACTION': np.int16,
        'Numform[89].VALUEREAL': np.float32,
        'Numform[89].DATEVAL': np.int16,
        'Numform[90].VALUETYPE': np.int16,
        'Numform[90].PCODE': np.int16,
        'Numform[90].PRODVALTYPE': np.int16,
        'Numform[90].ACTION': np.int16,
        'Numform[90].VALUEREAL': np.float32,
        'Numform[90].DATEVAL': np.int16,
        'Numform[91].VALUETYPE': np.int16,
        'Numform[91].PCODE': np.int16,
        'Numform[91].PRODVALTYPE': np.int16,
        'Numform[91].ACTION': np.int16,
        'Numform[91].VALUEREAL': np.float32,
        'Numform[91].DATEVAL': np.int16,
        'Numform[92].VALUETYPE': np.int16,
        'Numform[92].PCODE': np.int16,
        'Numform[92].PRODVALTYPE': np.int16,
        'Numform[92].ACTION': np.int16,
        'Numform[92].VALUEREAL': np.float32,
        'Numform[92].DATEVAL': np.int16,
        'Numform[93].VALUETYPE': np.int16,
        'Numform[93].PCODE': np.int16,
        'Numform[93].PRODVALTYPE': np.int16,
        'Numform[93].ACTION': np.int16,
        'Numform[93].VALUEREAL': np.float32,
        'Numform[93].DATEVAL': np.int16,
        'Numform[94].VALUETYPE': np.int16,
        'Numform[94].PCODE': np.int16,
        'Numform[94].PRODVALTYPE': np.int16,
        'Numform[94].ACTION': np.int16,
        'Numform[94].VALUEREAL': np.float32,
        'Numform[94].DATEVAL': np.int16,
        'Numform[95].VALUETYPE': np.int16,
        'Numform[95].PCODE': np.int16,
        'Numform[95].PRODVALTYPE': np.int16,
        'Numform[95].ACTION': np.int16,
        'Numform[95].VALUEREAL': np.float32,
        'Numform[95].DATEVAL': np.int16,
        'Numform[96].VALUETYPE': np.int16,
        'Numform[96].PCODE': np.int16,
        'Numform[96].PRODVALTYPE': np.int16,
        'Numform[96].ACTION': np.int16,
        'Numform[96].VALUEREAL': np.float32,
        'Numform[96].DATEVAL': np.int16,
        'Numform[97].VALUETYPE': np.int16,
        'Numform[97].PCODE': np.int16,
        'Numform[97].PRODVALTYPE': np.int16,
        'Numform[97].ACTION': np.int16,
        'Numform[97].VALUEREAL': np.float32,
        'Numform[97].DATEVAL': np.int16,
        'Numform[98].VALUETYPE': np.int16,
        'Numform[98].PCODE': np.int16,
        'Numform[98].PRODVALTYPE': np.int16,
        'Numform[98].ACTION': np.int16,
        'Numform[98].VALUEREAL': np.float32,
        'Numform[98].DATEVAL': np.int16,
        'Numform[99].VALUETYPE': np.int16,
        'Numform[99].PCODE': np.int16,
        'Numform[99].PRODVALTYPE': np.int16,
        'Numform[99].ACTION': np.int16,
        'Numform[99].VALUEREAL': np.float32,
        'Numform[99].DATEVAL': np.int16
    },
    'ARC': {
        'Rec No': np.int16,
        'Seq': np.int16,
        'Abbrev': object,
        'Descr': object
    },
    'LSG': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Type': np.int16,
        'Productcode': np.int16,
        'Seq': np.int16,
        'Length': np.int16,
        'Value': np.float16,
        'Value2': np.float16,
        'Carriedint': np.int16,
        'Rangelow': np.float16,
        'Rangehigh': np.float16
    },
    'LPV': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Type': np.int16,
        'Productcode': np.int16,
        'Modpointer': np.int16,
        'Startdate': np.int16,
        'Boolparam[0]': np.int16,
        'Boolparam[1]': np.int16,
        'Boolparam[2]': np.int16,
        'Boolparam[3]': np.int16,
        'Boolparam[4]': np.int16,
        'Boolparam[5]': np.int16,
        'Boolparam[6]': np.int16,
        'Boolparam[7]': np.int16,
        'Boolparam[8]': np.int16,
        'Boolparam[9]': np.int16,
        'Realparam[0]': np.float16,
        'Realparam[1]': np.float16,
        'Realparam[2]': np.float16,
        'Realparam[3]': np.float16,
        'Realparam[4]': np.float16
    },
    'INV': {
        'Rec No': object,
        'Lse Id': object,
        'Grp Id': object,
        'Seqno': object,
        'Catseq': object,
        'Descr': object,
        'Inv Netcost': object,
        'Inv Initial': object,
        'Islinked': object,
        'Harddate': object,
        'Strdate': object,
        'Linkid': object,
        'Linkoffset': object,
        'Inv Amnt': object,
        'Intang Amnt': object,
        'Riskfactor': object,
        'Allocinv': object,
        'Applyrisk': object,
        'Gcaeligible': object,
        'Gcarecoveryterm': object,
        'Gcacustomfactor': object,
        'Gcaror': object,
        'Ccaeligible': object,
        'Exempt50': object,
        'Availableforuse': object,
        'Archiveinv': object,
        'Arcseq': object
    },
    'OWN': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Grp Id': np.int16,
        'Seq': np.int16,
        'Revtype': np.int16,
        'Revvalue': np.float16,
        'Resolveddate': np.int16,
        'Lsenri': np.float16,
        'Wrkint': np.float16,
        'Revint': np.float16,
        'Npint': np.float16,
        'Rpg Id': np.int16
    },
    'ADJ': {
        'Rec No': object,
        'Lse Id': object,
        'Grp Id': object,
        'Adjtype': object,
        'Seq': object,
        'Pcode': object,
        'Revint': object
    },
    'UNI': {
        'Rec No': np.int16,
        'Uni Id': np.int16,
        'Parentunit': np.int16,
        'Abbr': object,
        'Power': np.int16
    },
    'MSC': {
        'Rec No': np.int16,
        'Lse Id': np.int16,
        'Pcode': np.int16,
        'Type': np.int16,
        'Bytevalue': np.int16,
        'Longvalue': np.int16,
        'Realvalue': np.float16,
        'Stringvalue': object
    },
    'MSG': {
        'Rec No': np.int16,
        'Type': np.int16,
        'Mpv Id': np.int16,
        'Seq': np.int16,
        'Length': np.int16,
        'Value': np.float16,
        'Value2': np.float16,
        'Rangelow': np.float16,
        'Rangehigh': np.float16
    },
    'MPV': {
        'Rec No': np.int16,
        'Type': np.int16,
        'Mpv Id': np.int16,
        'Productname': object,
        'Modelname': object,
        'Startdate': np.int16,
        'Currency': object,
        'Unitid': np.int16,
        'Unitstr': object,
        'Boolparam[0]': np.int16,
        'Boolparam[1]': np.int16,
        'Boolparam[2]': np.int16,
        'Boolparam[3]': np.int16,
        'Boolparam[4]': np.int16,
        'Boolparam[5]': np.int16,
        'Boolparam[6]': np.int16,
        'Boolparam[7]': np.int16,
        'Boolparam[8]': np.int16,
        'Boolparam[9]': np.int16,
        'Realparam[0]': np.float16,
        'Realparam[1]': np.float16,
        'Realparam[2]': np.float16,
        'Realparam[3]': np.float16,
        'Realparam[4]': np.float16,
        'State': object,
        'County': object,
        'Timestamp': object
    }
}
