numerical_bases = {
    'eur', 'acre_spacing', 'azimuth', 'casing_id', 'choke_size', 'cluster_count', 'cum_boe',
    'cum_boe_per_perforated_interval', 'cum_gas', 'cum_gas_per_perforated_interval', 'cum_gor', 'cum_mmcfge',
    'cum_mmcfge_per_perforated_interval', 'cum_oil', 'cum_oil_per_perforated_interval', 'cum_water',
    'cum_water_per_perforated_interval', 'custom_number_0', 'custom_number_1', 'custom_number_10', 'custom_number_11',
    'custom_number_12', 'custom_number_13', 'custom_number_14', 'custom_number_15', 'custom_number_16',
    'custom_number_17', 'custom_number_18', 'custom_number_19', 'custom_number_2', 'custom_number_3', 'custom_number_4',
    'custom_number_5', 'custom_number_6', 'custom_number_7', 'custom_number_8', 'custom_number_9',
    'distance_from_base_of_zone', 'distance_from_top_of_zone', 'elevation', 'first_12_boe',
    'first_12_boe_per_perforated_interval', 'first_12_gas', 'first_12_gas_per_perforated_interval', 'first_12_gor',
    'first_12_mmcfge', 'first_12_mmcfge_per_perforated_interval', 'first_12_oil',
    'first_12_oil_per_perforated_interval', 'first_12_water', 'first_12_water_per_perforated_interval', 'first_6_boe',
    'first_6_boe_per_perforated_interval', 'first_6_gas', 'first_6_gas_per_perforated_interval', 'first_6_gor',
    'first_6_mmcfge', 'first_6_mmcfge_per_perforated_interval', 'first_6_oil', 'first_6_oil_per_perforated_interval',
    'first_6_water', 'first_6_water_per_perforated_interval', 'first_additive_volume', 'first_cluster_count',
    'first_fluid_per_perforated_interval', 'first_fluid_volume', 'first_max_injection_pressure',
    'first_max_injection_rate', 'first_prop_weight', 'first_proppant_per_fluid',
    'first_proppant_per_perforated_interval', 'first_stage_count', 'first_test_flow_tbg_press', 'first_test_gas_vol',
    'first_test_gor', 'first_test_oil_vol', 'first_test_water_vol', 'footage_in_landing_zone',
    'formation_thickness_mean', 'gas_specific_gravity', 'ground_elevation', 'hz_well_spacing_any_zone',
    'hz_well_spacing_same_zone', 'initial_respress', 'initial_restemp', 'landing_zone_base', 'landing_zone_top',
    'last_12_boe', 'last_12_boe_per_perforated_interval', 'last_12_gas', 'last_12_gas_per_perforated_interval',
    'last_12_gor', 'last_12_mmcfge', 'last_12_mmcfge_per_perforated_interval', 'last_12_oil',
    'last_12_oil_per_perforated_interval', 'last_12_water', 'last_12_water_per_perforated_interval', 'last_month_boe',
    'last_month_boe_per_perforated_interval', 'last_month_gas', 'last_month_gas_per_perforated_interval',
    'last_month_gor', 'last_month_mmcfge', 'last_month_mmcfge_per_perforated_interval', 'last_month_oil',
    'last_month_oil_per_perforated_interval', 'last_month_water', 'last_month_water_per_perforated_interval',
    'lateral_length', 'lease_number', 'lower_perforation', 'matrix_permeability', 'measured_depth', 'month_produced',
    'num_treatment_records', 'oil_api_gravity', 'oil_specific_gravity', 'perf_lateral_length', 'refrac_additive_volume',
    'refrac_cluster_count', 'refrac_fluid_per_perforated_interval', 'refrac_fluid_volume',
    'refrac_max_injection_pressure', 'refrac_max_injection_rate', 'refrac_prop_weight', 'refrac_proppant_per_fluid',
    'refrac_proppant_per_perforated_interval', 'refrac_stage_count', 'stage_spacing', 'surfaceLatitude',
    'surfaceLongitude', 'thickness', 'toeLatitude', 'toeLongitude', 'total_additive_volume', 'total_cluster_count',
    'total_fluid_per_perforated_interval', 'total_fluid_volume', 'total_prop_weight', 'total_proppant_per_fluid',
    'total_proppant_per_perforated_interval', 'total_stage_count', 'true_vertical_depth', 'tubing_depth', 'tubing_id',
    'upper_perforation', 'vt_well_spacing_any_zone', 'vt_well_spacing_same_zone'
}

normalization_bases = {
    'first_prop_weight/perf_lateral_length': 'eur/perf_lateral_length',
    'first_fluid_volume/perf_lateral_length': 'eur/perf_lateral_length',
    'first_prop_weight/perf_lateral_length/hz_well_spacing_same_zone':
    'eur/perf_lateral_length/hz_well_spacing_same_zone',
    'first_fluid_volume/perf_lateral_length/hz_well_spacing_same_zone':
    'eur/perf_lateral_length/hz_well_spacing_same_zone',
    'first_prop_weight/acre_spacing': 'eur/acre_spacing',
    'first_fluid_volume/acre_spacing': 'eur/acre_spacing',
    'eur': numerical_bases,
    'perf_lateral_length': 'peak_rate'
}

orginal_custom_header_dict = {
    "custom_number_0": "Custom Number Header 1",
    "custom_number_1": "Custom Number Header 2",
    "custom_number_2": "Custom Number Header 3",
    "custom_number_3": "Custom Number Header 4",
    "custom_number_4": "Custom Number Header 5",
    "custom_number_5": "Custom Number Header 6",
    "custom_number_6": "Custom Number Header 7",
    "custom_number_7": "Custom Number Header 8",
    "custom_number_8": "Custom Number Header 9",
    "custom_number_9": "Custom Number Header 10",
    "custom_number_10": "Custom Number Header 11",
    "custom_number_11": "Custom Number Header 12",
    "custom_number_12": "Custom Number Header 13",
    "custom_number_13": "Custom Number Header 14",
    "custom_number_14": "Custom Number Header 15",
    "custom_number_15": "Custom Number Header 16",
    "custom_number_16": "Custom Number Header 17",
    "custom_number_17": "Custom Number Header 18",
    "custom_number_18": "Custom Number Header 19",
    "custom_number_19": "Custom Number Header 20"
}

well_p = {
    'acre_spacing': 1,
    'azimuth': 1,
    'casing_id': 1,
    'choke_size': 1,
    'cluster_count': 1,
    'distance_from_base_of_zone': 1,
    'distance_from_top_of_zone': 1,
    'elevation': 1,
    'first_additive_volume': 1,
    'first_cluster_count': 1,
    'first_fluid_per_perforated_interval': 1,
    'first_fluid_volume': 1,
    'first_max_injection_pressure': 1,
    'first_max_injection_rate': 1,
    'first_prop_weight': 1,
    'first_proppant_per_fluid': 1,
    'first_proppant_per_perforated_interval': 1,
    'first_stage_count': 1,
    'first_test_flow_tbg_press': 1,
    'first_test_gas_vol': 1,
    'first_test_gor': 1,
    'first_test_oil_vol': 1,
    'first_test_water_vol': 1,
    'footage_in_landing_zone': 1,
    'formation_thickness_mean': 1,
    'gas_specific_gravity': 1,
    'perf_lateral_length': 1,
    'ground_elevation': 1,
    'hz_well_spacing_any_zone': 1,
    'hz_well_spacing_same_zone': 1,
    'initial_respress': 1,
    'initial_restemp': 1,
    'landing_zone_base': 1,
    'landing_zone_top': 1,
    'lateral_length': 1,
    'lease_number': 1,
    'lower_perforation': 1,
    'matrix_permeability': 1,
    'measured_depth': 1,
    'num_treatment_records': 1,
    'oil_api_gravity': 1,
    'oil_specific_gravity': 1,
    'refrac_additive_volume': 1,
    'refrac_cluster_count': 1,
    'refrac_fluid_per_perforated_interval': 1,
    'refrac_fluid_volume': 1,
    'refrac_max_injection_pressure': 1,
    'refrac_max_injection_rate': 1,
    'refrac_prop_weight': 1,
    'refrac_proppant_per_fluid': 1,
    'refrac_proppant_per_perforated_interval': 1,
    'refrac_stage_count': 1,
    'stage_spacing': 1,
    'surfaceLatitude': 1,
    'surfaceLongitude': 1,
    'thickness': 1,
    'toeLatitude': 1,
    'toeLongitude': 1,
    'total_additive_volume': 1,
    'total_cluster_count': 1,
    'total_fluid_per_perforated_interval': 1,
    'total_fluid_volume': 1,
    'total_prop_weight': 1,
    'total_proppant_per_fluid': 1,
    'total_proppant_per_perforated_interval': 1,
    'total_stage_count': 1,
    'true_vertical_depth': 1,
    'tubing_depth': 1,
    'tubing_id': 1,
    'upper_perforation': 1,
    'vt_well_spacing_any_zone': 1,
    'vt_well_spacing_same_zone': 1,
    'cum_boe': 1,
    'cum_oil': 1,
    'cum_gas': 1,
    'cum_gor': 1,
    'cum_water': 1,
    'cum_mmcfge': 1,
    'cum_boe_per_perforated_interval': 1,
    'cum_gas_per_perforated_interval': 1,
    'cum_oil_per_perforated_interval': 1,
    'cum_water_per_perforated_interval': 1,
    'cum_mmcfge_per_perforated_interval': 1,
    'first_12_boe': 1,
    'first_12_boe_per_perforated_interval': 1,
    'first_12_gas': 1,
    'first_12_gas_per_perforated_interval': 1,
    'first_12_gor': 1,
    'first_12_oil': 1,
    'first_12_oil_per_perforated_interval': 1,
    'first_12_water': 1,
    'first_12_water_per_perforated_interval': 1,
    'first_12_mmcfge': 1,
    'first_12_mmcfge_per_perforated_interval': 1,
    'first_6_boe': 1,
    'first_6_boe_per_perforated_interval': 1,
    'first_6_gas': 1,
    'first_6_gas_per_perforated_interval': 1,
    'first_6_gor': 1,
    'first_6_mmcfge': 1,
    'first_6_mmcfge_per_perforated_interval': 1,
    'first_6_oil': 1,
    'first_6_oil_per_perforated_interval': 1,
    'first_6_water': 1,
    'first_6_water_per_perforated_interval': 1,
    'last_12_boe': 1,
    'last_12_boe_per_perforated_interval': 1,
    'last_12_gas': 1,
    'last_12_gas_per_perforated_interval': 1,
    'last_12_gor': 1,
    'last_12_mmcfge': 1,
    'last_12_mmcfge_per_perforated_interval': 1,
    'last_12_oil': 1,
    'last_12_oil_per_perforated_interval': 1,
    'last_12_water': 1,
    'last_12_water_per_perforated_interval': 1,
    'last_month_boe': 1,
    'last_month_boe_per_perforated_interval': 1,
    'last_month_gas': 1,
    'last_month_gas_per_perforated_interval': 1,
    'last_month_gor': 1,
    'last_month_mmcfge': 1,
    'last_month_mmcfge_per_perforated_interval': 1,
    'last_month_oil': 1,
    'last_month_oil_per_perforated_interval': 1,
    'last_month_water': 1,
    'last_month_water_per_perforated_interval': 1,
    'month_produced': 1,
    'wi_oil': 1,
    'nri_oil': 1,
    'before_income_tax_cash_flow': 1,
    'first_discount_cash_flow': 1,
    'undiscounted_roi': 1,
    'irr': 1,
    'payout_duration': 1,
    'oil_breakeven': 1,
    'gas_breakeven': 1,
    'oil_shrunk_eur': 1,
    'gas_shrunk_eur': 1,
    'ngl_shrunk_eur': 1,
    'oil_shrunk_eur_over_pll': 1,
    'gas_shrunk_eur_over_pll': 1,
    'ngl_shrunk_eur_over_pll': 1,
    'custom_number_0': 1,
    'custom_number_1': 1,
    'custom_number_2': 1,
    'custom_number_3': 1,
    'custom_number_4': 1,
    'custom_number_5': 1,
    'custom_number_6': 1,
    'custom_number_7': 1,
    'custom_number_8': 1,
    'custom_number_9': 1,
    'custom_number_10': 1,
    'custom_number_11': 1,
    'custom_number_12': 1,
    'custom_number_13': 1,
    'custom_number_14': 1,
    'custom_number_15': 1,
    'custom_number_16': 1,
    'custom_number_17': 1,
    'custom_number_18': 1,
    'custom_number_19': 1
}
