import {
	faArrowDown,
	faArrowUp,
	faBell,
	faBezierCurve,
	faBuilding,
	faCalendar,
	faCalendarAlt,
	faCameraPolaroid,
	faChartBar,
	faChartScatter,
	faCircleNotch,
	faCloudUpload,
	faCog,
	faCompress,
	faDatabase,
	faDownload,
	faExpand,
	faFileSpreadsheet,
	faFilter,
	faFolderOpen,
	faFunction,
	faHeartRate,
	faHeat,
	faKey,
	faLayerGroup,
	faPen,
	faRabbitFast,
	faSackDollar,
	faShare,
	faSigma,
	faSync,
	faTable,
	faTimes,
	faTint,
} from '@fortawesome/pro-regular-svg-icons';

import { ReactComponent as CarbonNetworkIconDark } from './network_models_dark.svg';
import { ReactComponent as CarbonNetworkIconLight } from './network_models_light.svg';

export const FeatureIcons = {
	access: faKey,
	ccToCc: faFileSpreadsheet,
	close: faTimes,
	company: faBuilding,
	compress: faCompress,
	dataImport: faCloudUpload,
	dataSync: faSync,
	dataSyncAgentInstances: faCameraPolaroid,
	dataSyncDataFlows: faCircleNotch,
	dataSyncDataSources: faDatabase,
	dataSyncDataSecrets: faKey,
	diImport: faCloudUpload,
	download: faDownload,
	economics: faSackDollar,
	edit: faPen,
	expand: faExpand,
	filter: faFilter,
	forecastDiag: faHeartRate,
	forecasts: faFunction,
	heatmap: faHeat,
	layers: faLayerGroup,
	lookupTable: faTable,
	notifications: faBell,
	projects: faFolderOpen,
	reports: faChartScatter,
	run: faRabbitFast,
	scenarios: faBezierCurve,
	schedule: faCalendar,
	scheduleOutput: faCalendarAlt,
	scheduleGantt: faChartBar,
	settings: faCog,
	shareableCodes: faShare,
	summary: faCircleNotch,
	typecurve: faSigma,
	wells: faTint,
	networkModel: {
		dark: CarbonNetworkIconDark,
		light: CarbonNetworkIconLight,
	},
	sortAsc: faArrowUp,
	sortDesc: faArrowDown,
};
