# Default substitutions: $PROJECT_ID

steps:
  # see: https://cloud.google.com/build/docs/deploying-builds/deploy-appengine#continuous_deployment
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/flex-cc-base",
        "-f",
        "./apps/flex_cc/Dockerfile.base",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/flex-cc-base"]

timeout: 1800s

options:
  machineType: "N1_HIGHCPU_8"
