version: "3.9"

services:
  flex-cc:
    container_name: flex-cc
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - 5001:5000
      - 5679:5678
    volumes:
      - .:/app/
      - ./combocurve:/app/combocurve
    extra_hosts:
      - "host.docker.internal:host-gateway"
