export const Z_INDEX_ECONOMICS_DIALOGUE = 130000;
export const Z_INDEX_COLUMN_POPUP_MENU_MAIN = Z_INDEX_ECONOMICS_DIALOGUE + 1;
export const Z_INDEX_COLUMN_POPUP_MENU_SUBMENU = Z_INDEX_COLUMN_POPUP_MENU_MAIN + 1;
