runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: 18

service: external-api

# [START configuration]
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  rollout_strategy: managed
  name: carbon-api.combocurve.com
# [END configuration]

env_variables:
  EXTERNAL_API_IMPORT_URL: "https://external-api-import-phl3uwlpbq-uc.a.run.app"
  WELL_SERVICE_URL: "https://well-service-phl3uwlpbq-uc.a.run.app"
  FORECAST_SERVICE_URL: "https://forecast-service-phl3uwlpbq-uc.a.run.app"
  GCP_PRIMARY_PROJECT_ID: carbon-combocurve
  GCP_REGIONAL_PROJECT_ID: carbon-combocurve
  REGION: "us-central1"
  DAILY_FORECAST_VOLUME_YEAR_NUMBER_LIMIT: 5
  ECON_MONTHLY_CONCURRENCY: 4
  ECON_MONTHLY_ATTEMPTS: 4
  ECON_MONTHLY_ATTEMPT_DELAY_MS: 1000

automatic_scaling:
  cool_down_period_sec: 120
  min_num_instances: 2
  cpu_utilization:
    target_utilization: 0.5
  # default max_num_instances is 20
  max_num_instances: 10
