from enum import Enum

AC_ECONOMIC = 'AC_ECONOMIC'
AC_PROPERTY = 'AC_PROPERTY'
AC_DAILY = 'AC_DAILY'
AC_PRODUCT = 'AC_PRODUCT'
PROPNUM = 'PROPNUM'
AC_SETUP = 'AC_SETUP'
AC_SETUPDATA = 'AC_SETUPDATA'
AR_SIDEFILE = 'AR_SIDEFILE'
AR_LOOKUP = 'ARLOOKUP'
CC_FORECAST = 'CC_FORECAST'
AR_ENDDATE = 'ARENDDATE'


class PhdwinModelEnum(Enum):
    reserves = 'Reserves Category'
    general_options = 'General Options'
    dates = 'Dates'
    ownership = 'Ownership and Reversion'
    capex = 'CAPEX'
    pricing = 'Pricing'
    differentials = 'Differentials'
    stream_props = 'Stream Properties'
    expenses = 'Expenses'
    prod_tax = 'Production Taxes'
    forecast = 'Forecast'
    risk = 'Risking'
    actual_v_forecast = 'Actual vs Forecast'


class ErrorColumn(Enum):
    scenario = 'SCENARIO'
    well = PROPNUM
    section = 'SECTION'
    model = 'MODEL'
    message = 'MESSAGE'
    row = 'INPUT ROW'
    severity = 'SEVERITY'


class PhdwinErrorColumn(Enum):
    well = 'Lease Number'
    model = 'MODEL'
    message = 'MESSAGE'
    severity = 'SEVERITY'


class FileDir(Enum):
    m = "@M"
    base = "../run_local/"
    daily = "/AC_DAILY.csv"
    monthly = "/AC_PRODUCT.csv"
    info = "/AC_PROPERTY.csv"
    economic = "/AC_ECONOMIC.csv"
    scenario = "/AC_SCENARIO.csv"
    lookup = "/ARLOOKUP.csv"
    end = "/ARENDDATE.csv"
    sidefile = "/AR_SIDEFILE.csv"
    project = "/PROJECT.csv"
    projlist = "/PROJLIST.csv"
    setup_data = "/AC_SETUPDATA.csv"
    setup = "/AC_SETUP.csv"
    ecophase = "/ECOPHASE.csv"
    dbslist = "/DBSLIST.csv"
    arsystbl = "/ARSYSTBL.csv"


class AriesFilesEnum(Enum):
    ac_property = 'acProperty'
    ac_daily = 'acDaily'
    ac_product = 'acProduct'
    ac_economic = 'acEconomic'
    ac_scenario = 'acScenario'
    ac_setup = 'acSetup'
    ac_setupdata = 'acSetupdata'
    ar_sidefile = 'arSidefile'
    ar_enddate = 'arEnddate'
    ar_lookup = 'arLookup'
    aries_project = 'ariesProject'
    projlist = 'projlist'
    ecophase = 'ecophase'
    dbslist = 'dbslist'
    arsystbl = 'arsystbl'


ARIES_FILES_LABEL = {
    AriesFilesEnum.ac_property: AC_PROPERTY,
    AriesFilesEnum.ac_daily: AC_DAILY,
    AriesFilesEnum.ac_product: AC_PRODUCT,
    AriesFilesEnum.ac_economic: AC_ECONOMIC,
    AriesFilesEnum.ac_scenario: 'AC_SCENARIO',
    AriesFilesEnum.ac_setup: AC_SETUP,
    AriesFilesEnum.ac_setupdata: AC_SETUPDATA,
    AriesFilesEnum.ar_sidefile: 'AR_SIDEFILE',
    AriesFilesEnum.ar_enddate: 'ARENDDATE',
    AriesFilesEnum.ar_lookup: 'ARLOOKUP',
    AriesFilesEnum.aries_project: 'PROJECT',
    AriesFilesEnum.projlist: 'PROJLIST',
    AriesFilesEnum.ecophase: 'ECOPHASE',
    AriesFilesEnum.dbslist: 'DBSLIST',
    AriesFilesEnum.arsystbl: 'ARSYSTBL',
}


class ForecastEnum(Enum):
    start_index = 'start_idx'
    start_date = 'start_date'
    end_index = 'end_idx'
    end_date = 'end_date'
    p_dict = 'P_dict'
    plot_index = 'plot_idx'
    p_extra = 'p_extra'
    best = 'best'
    data = 'data'
    segments = 'segments'
    q_start = 'q_start'
    qend = 'qend'
    q_end = 'q_end'
    qi = 'qi'
    b = 'b'
    d_eff = 'D_eff'
    deff_phd = 'deff'
    d = 'D'
    d_exp_eff = 'D_exp_eff'
    d_exp = 'D_exp'
    q_switch = 'q_sw'
    switch_index = 'sw_idx'
    r_d_eff_sw = 'realized_D_eff_sw'
    t_d_eff_sw = 'target_D_eff_sw'
    linear_deff = 'linear_deff'
    slope = 'slope'
    exp_inc = 'exp_inc'
    exp_dec = 'exp_dec'
    arps = 'arps'
    arps_modified = 'arps_modified'
    name = 'name'
    flat = 'flat'
    linear = 'linear'
    empty = 'empty'
    commom = 'common'
    c = 'c'
    forecast_bool = 'forecasted'
    forecast_type = 'forecastType'
    ratio = 'ratio'
    rate = 'rate'
    base_phase = 'basePhase'
    other_phase = 'other_phase'
    yields = 'yields'
    ngl_yield = 'yield'
    well_oil_cum = 'well_head_oil_cum'
    well_gas_cum = 'well_head_gas_cum'
    unshrunk_gas = 'Unshrunk Gas'
    shrunk_gas = 'Shrunk Gas'
    tangent_deff = 'tangent_deff'
    nominal_deff = 'nominal_deff'
    secant_deff = 'secant_deff'


class UnitEnum(Enum):
    year = 'YR'
    years = 'YRS'
    incr_year = 'IYR'
    incr_years = 'IYRS'
    month = 'MO'
    incr_month = 'IMO'
    incr_months = 'IMOS'
    months = 'MOS'
    life = 'LIFE'
    ad = 'AD'
    bpm = 'B/M'
    mpm = 'M/M'
    upm = 'U/M'
    bpy = 'B/Y'
    mpy = 'M/Y'
    upy = 'U/Y'
    mbpd = 'MB/D'
    mmpd = 'MM/D'
    mupd = 'MU/D'
    mbpm = 'MB/M'
    mmpm = 'MM/M'
    mbpy = 'MB/Y'
    mmpy = 'MM/Y'
    bpmcf = 'B/MM'
    mmpb = 'MM/B'
    frac = 'FRAC'
    perc_sign = '%'
    dollar_sign = '$'
    bbl = 'BBL'
    mb = 'MB'
    mmb = 'MMB'
    mcf = 'MCF'
    mmf = 'MMF'
    bcf = 'BCF'
    imu = 'IMU'
    u = 'U'
    mu = 'MU'
    dollar_per_year = '$/Y'
    dollar_per_unit = '$/U'
    dollar_per_mcf = '$/M'
    dollar_per_bbl = '$/B'
    dollar_escalation = '$E'
    perc_escalation = 'PE'
    perc_compound_escalation = 'PC'
    escalation = 'ESC'
    mcf_per_day = 'MPD'
    bbl_per_day = 'BPD'


class ExpressionEnum(Enum):
    yes = 'yes'
    no = 'no'


class PhaseEnum(Enum):
    oil = 'oil'
    gas = 'gas'
    water = 'water'
    ngl = 'ngl'
    aries_water = 'WTR'
    aries_condensate = 'cnd'
    ngl_yield = 'ngl/gas'
    cnd_yield = 'cnd/gas'
    condensate = 'drip_condensate'


class TableEnum(Enum):
    life = 'LIFE'
    record = 'RECORD'
    line = 'LINE'
    line_number = 'LINENUMBER'


class WellHeaderEnum(Enum):
    api_14 = 'api14'
    api_10 = 'api10'
    aries_id = 'aries_id'
    propnum = PROPNUM
    chosen_key_id = 'chosenKeyID'
    chosen_id = 'chosenID'
    project = 'project'
    data_pool = 'dataPool'
    data_source = 'dataSource'
    inpt_id = 'inptID'
    copied_from = 'copiedFrom'
    first_prop_weight = 'first_prop_weight'
    lateral_length = 'lateral_length'
    measured_depth = 'measured_depth'
    perf_lateral_length = 'perf_lateral_length'
    primary_product = 'primary_product'
    surface_latitude = 'surfaceLatitude'
    surface_longitude = 'surfaceLongitude'
    tvd = 'true_vertical_depth'
    md = 'measured_depth'
    first_fluid_volume = 'first_fluid_volume'
    well_name = 'well_name'


class EconEnum(Enum):
    sidefile = 'SIDEFILE'
    lookup = 'LOOKUP'
    file = 'FILE'
    econ_function = 'econ_function'
    econ_limit = 'Econ Limit'
    fpd_offset = 'offset_to_fpd'
    asof_offset = 'offset_to_as_of_date'
    econ_limit_offset = 'offset_to_econ_limit'
    asof_date = 'as_of_date'
    as_of = 'as_of'
    options = 'options'
    var_exp = 'variable_expenses'
    gathering = 'gathering'
    transport = 'transportation'
    opc = 'processing'
    market = 'marketing'
    other = 'other'
    calc = 'calculation'
    rows = 'rows'
    cap = 'cap'
    w_interest = 'wi'
    opnet = 'OPNET'
    hundred_wi = '100_pct_wi'
    lease_nri = 'Lease NRI'
    one_minus_wi = '1 - WI'
    one_minus_nri = '1 - NRI'
    one_minus_lease_nri = '1 - Lease NRI'
    net_interest = 'nri'
    shrunk = 'shrunk'
    unshrunk = 'unshrunk'
    shrunk_gas = 'shrunk_gas'
    unshrunk_gas = 'unshrunk_gas'
    shrinkage_condition = 'shrinkage_condition'
    yields = 'yields'
    deal_terms = 'deal_terms'
    sub_items = 'subItems'
    label = 'label'
    value = 'value'
    adval_tax = 'ad_valorem_tax'
    aban_exp = 'ABAN'
    atx = 'ATX'
    atx_per_t = 'ATX/T'
    stx = 'STX'
    lse = 'LSE'
    own = 'OWN'
    net = 'NET'
    cumm = 'CUMS'
    loss = 'LOSS'
    eloss = 'ELOSS'
    pmax = 'PMAX'
    noh = 'NOH'
    oh = 'OH'
    zero = 'ZERO'
    overlay_sequence = -9999
    liquid_trans_cost_per = 'LTC/'
    deduct_before_sev_tax = 'deduct_before_severance_tax'
    deduct_sev_tax = 'deduct_severance_tax'
    stx_per = 'STX/'
    stx_per_oil = 'STX/OIL'
    stx_per_gas = 'STX/GAS'
    stx_per_ngl = 'STX/NGL'
    opc_per = 'OPC/'
    ga_per = 'GA/'
    oh_per = 'OH/'
    price_per = 'PRI/'
    paj_per = 'PAJ/'
    pad_per = 'PAD/'
    curtail_per = 'CUR/'
    multiplier_for = 'MUL/'
    oil_ratio = 'OIL/'
    gas_ratio = 'GAS/'
    water_ratio = 'WTR/'
    sev_tax = 'severance_tax'
    risk = 'risking'
    risk_model = 'risking_model'
    price_model = 'price_model'
    differential_model = 'differential_model'
    unit_cost = 'unit_cost'
    escalation_model = 'escalation_model'
    differentials = 'differentials'
    volume_multiplier = 'volume_multiplier'
    multiplier = 'multiplier'
    prod_vs_fit_model = 'production_vs_fit_model'
    stream_properties = 'stream_properties'
    replace_actual = 'replace_actual'
    ignore_hist_prod = 'ignore_hist_prod'
    actual_or_forecast = 'actual_or_forecast'
    shrinkage = 'shrinkage'
    pct_remaining = 'pct_remaining'
    min_cut_off = 'min_cut_off'
    el_delay = 'econ_limit_delay'
    include_capex = 'include_capex'
    opinc = 'OPINC'
    no = 'NO'
    bfit = 'BFIT'
    ok = 'OK'
    date = 'date'
    period = 'period'
    never = 'never'
    fpd = 'fpd'
    asof = 'asof'
    cut_off = 'cut_off'
    water_disposal = 'water_disposal'
    fixed_expense = 'fixed_expenses'
    fixed_exp = 'fixed_expense'
    variable_expense = 'variable_expenses'
    other_cost_1 = 'other_monthly_cost_1'
    other_cost_2 = 'other_monthly_cost_2'
    other_cost_3 = 'other_monthly_cost_3'
    other_cost_4 = 'other_monthly_cost_4'
    other_cost_5 = 'other_monthly_cost_5'
    other_cost_6 = 'other_monthly_cost_6'
    other_cost_7 = 'other_monthly_cost_7'
    other_cost_8 = 'other_monthly_cost_8'
    monthly_cost = 'monthly_well_cost'
    sch_well_expense = 'Scheduled Well Expense (Well Cost)'
    sch_monthly_expense = 'Scheduled Monthly Expense (Fixed Cost)'
    opt_cost_model = 'Operating Cost Model (Variable Expense)'
    trans_cost_var = 'Trans Cost Model (Variable Expense)'
    other_cost_var = 'Other Cost Model (Variable Expense)'
    well_cost = 'Well Cost'
    fixed_cost = 'Fixed Cost'
    reserves_category = 'reserves_category'
    prms_class = 'prms_resources_class'
    prms_cat = 'prms_reserves_category'
    prms_sub_cat = 'prms_reserves_sub_category'
    dates_setting = 'dates_setting'
    max_well_life = 'max_well_life'
    entire_well_life = 'entire_well_life'
    discount_date = 'discount_date'
    max_eco_years = 'maxecoyears'
    discount = 'discount'
    pct_per_year = 'pct_per_year'
    dollar_per_year = 'dollar_per_year'
    esc_calc_method = 'calculation_method'
    esc_frequency = 'escalation_frequency'


class EconHeaderEnum(Enum):
    expression = 'EXPRESSION'
    propnum = 'PROPNUM'
    qualifier = 'QUALIFIER'
    sequence = 'SEQUENCE'
    extracted_sequence = 'EXTRACTED SEQUENCE'
    section = 'SECTION'
    owner = 'OWNER'
    linetype = 'LINETYPE'
    linenumber = 'LINENUMBER'
    name = 'NAME'
    keyword = 'keyword_mark'
    initial_keyword = 'KEYWORD'
    file_name = 'FILENAME'
    sec_type = 'SECTYPE'
    common_lines = 'COMLINES'
    default_lines = 'DEFLINES'
    pw = 'PW'
    common = 'COMMON'
    default = 'DEFAULT'
    sec_name = 'SECNAME'
    frame = 'FRAME'
    corptax = 'CORPTAX'
    varates = 'VARATES'
    misc_section_key = 2
    forecast_section_key = 4
    list_method_special_key = 24
    price_section_key = 5
    tax_expense_section_key = 6
    own_section_key = 7
    capex_section_key = 8
    overlay_section_key = 9


class OverlayEnum(Enum):
    opc_gas_wi = '687'
    opc_oil_wi = '686'
    opc_gas_ini = '253'
    opc_oil_ini = '252'
    opc_ngl_ini = '256'
    opc_cnd_ini = '254'
    gpc_ngl_ini = '297'
    opc_t = '267'
    oh_t = '316'
    oh_w = '317'
    opc_ogw = '272'
    opc_oil_well = '702'
    tran_oil_wi = '707'
    opc_gas_well = '703'
    opc_oil_gas_well = '706'
    gtc_gas_wi = '708'
    workover_exp = '714'
    gtc_gas_ini = '277'
    gtc_gas_nri = '1040'
    gpc_gas = '286'
    cmp_gas = '280'
    trc_gas = '283'
    gtc_lqd = '274'
    gpc_gas_wi = '711'
    lease_net_oil = '145'
    lease_net_gas = '146'
    net_oil = '815'
    net_gas = '816'
    net_cnd = '817'
    net_ngl = '819'
    wi = '95'
    nri = '145'
    load = 'LOAD'
    adval_tax_wi = '1064'
    gross_oil = '370'
    gross_gas = '371'
    gross_cnd = '372'
    gross_ngl = '374'
    gross_wtr = '375'
    gross_wtr_2 = '376'
    sales_oil = '391'
    sales_gas = '392'
    sales_cnd = '393'
    sales_ngl = '395'
    appraised_opc_ngl = '1022'
    appraised_opc_oil = '1018'
    ltc_oil_cnd_nri = '1039'
    ltc_oil_cnd_ini = '274'
    gross_oil_sev_tax = '458'
    gross_gas_sev_tax = '459'
    gross_cnd_sev_tax = '460'
    gross_ngl_sev_tax = '462'
    oil_sev_tax_rate = '40'
    gas_sev_tax_rate = '41'
    ngl_sev_tax_rate = '44'
    cnd_sev_tax_rate = '42'
    oil_wi = '753'
    gas_wi = '754'
    cnd_wi = '755'
    ngl_wi = '757'
    gross_oil_rev = '427'
    gross_gas_rev = '428'
    gross_cnd_rev = '429'
    gross_ngl_rev = '431'
    all_gas_net = '1019'
    oil_shrink = '391'
    multiply = 'MUL'
    divide = 'DIV'


class OperatorEnum(Enum):
    multiply = 'MUL'
    divide = 'DIV'
    plus = 'PLUS'
    minus = 'MINUS'


class CCSchemaEnum(Enum):
    well = 'well'
    name = 'name'
    wells = 'wells'
    _id = '_id'
    project = 'project'
    created = 'createdAt'
    updated = 'updatedAt'
    assumption_key = 'assumptionKey'
    date = 'date'
    dates = 'dates'
    start = 'start'
    end = 'end'
    start_date = 'start_date'
    end_date = 'end_date'
    mdy_date_slash_format = '%m/%d/%Y'
    ymd_date_dash_format = '%Y-%m-%d'
    major = 'major'
    base = 'base'
    effective = 'effective'
    primary_product = 'primary_product'
    round_off_value = 7
    date_round_off = 7


class PriceEnum(Enum):
    diff_percent = 'differential_percentage'
    diff_dollar = 'differential_dollar'
    price = 'price'
    pricing = 'pricing'
    price_model = 'price_model'
    diff = 'differentials'
    diff_1 = 'differentials_1'
    diff_2 = 'differentials_2'
    dollar_per_mcf = 'dollar_per_mcf'
    dollar_per_bbl = 'dollar_per_bbl'
    dollar_per_month = 'dollar_per_month'
    dollar_per_mmbtu = 'dollar_per_mmbtu'
    dollar_per_boe = 'dollar_per_boe'
    pct_of_base_price = 'pct_of_base_price'
    pct_of_revenue = 'pct_of_revenue'
    pct_of_oil_price = 'pct_of_oil_price'


class ReservesEnum(Enum):
    proved = 'proved'
    probable = 'probable'
    possible = 'possible'
    reserves = 'reserves'
    producing = 'producing'
    non_producing = 'non-producing'
    undeveloped = 'undeveloped'
    behind_pipe = 'behind pipe'
    shut_in = 'shut-in'
    injection = 'injection'
    p_a = 'p&a'
    contingent = 'contingent'
    c_1 = 'c1'
