jest.setTimeout(30000);

// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const { ObjectId } = require('mongodb');

// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const setupDb = require('../../tests/setup-db');
// eslint-disable-next-line @typescript-eslint/no-var-requires -- TODO eslint fix later
const { up } = require('./20210719155753-set-well-defaults');

let db;
let client;
let mongod;

const wellsBefore = [
	{ _id: new ObjectId('123456789012345678900001') },
	{
		_id: new ObjectId('123456789012345678900002'),
		dataPool: 'internal',
		dataSource: 'other',
		project: null,
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900003'),
		dataPool: 'internal',
		dataSource: 'internal',
		project: null,
		lateral_length: 1000,
		perf_lateral_length: 1000,
		primary_product: null,
		true_vertical_depth: null,
		copied: true,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: 45,
		surfaceLongitude: 45,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: 10000,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900004'),
		dataPool: 'internal',
		dataSource: 'internal',
		lateral_length: 1000,
		perf_lateral_length: 1000,
		copied: true,
		surfaceLatitude: 45,
		surfaceLongitude: 45,
		total_fluid_volume: 10000,
	},
	{
		_id: new ObjectId('123456789012345678900005'),
		dataPool: 'internal',
		dataSource: 'other',
		project: null,
		copied: false,
	},
	{
		_id: new ObjectId('123456789012345678900006'),
		dataPool: 'internal',
		dataSource: 'di',
		project: new ObjectId('123456789012345678901001'),
		copied: false,
	},
	{
		_id: new ObjectId('123456789012345678900007'),
		chosenID: '12345678900005',
		dataSource: 'internal',
		project: new ObjectId('60f1dfaa3d2f562ef8475140'),
		first_fluid_volume: null,
		first_prod_date: null,
		first_prop_weight: null,
		lateral_length: null,
		measured_depth: null,
		perf_lateral_length: null,
		primary_product: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		true_vertical_depth: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: new Date('2000-05-15T00:00:00.000Z'),
		createdAt: new Date('2021-07-17T03:57:22.578Z'),
		inptID: 'INPTwl5uhUCyTZ',
		has_monthly: true,
		last_prod_date_monthly: new Date('2001-08-15T00:00:00.000Z'),
		has_daily: false,
		last_prod_date_daily: null,
		schemaVersion: 1,
		dataPool: 'internal',
		copied: false,
		chosenKeyID: 'chosen id',
		mostRecentImport: new ObjectId('60f256edc505e6216f1f6f0e'),
		mostRecentImportDesc: 'internal-cpeña20210717t000427',
		mostRecentImportType: 'spreadsheet',
		mostRecentImportDate: new Date('2021-07-17T04:04:59.231Z'),
		well_name: 'well 5',
		updatedAt: new Date('2021-07-17T04:07:25.634Z'),
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
	},
];
const wellsAfter = [
	{
		_id: new ObjectId('123456789012345678900001'),
		dataPool: 'internal',
		dataSource: 'other',
		project: null,
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900002'),
		dataPool: 'internal',
		dataSource: 'other',
		project: null,
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		copied: false,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900003'),
		dataPool: 'internal',
		dataSource: 'internal',
		project: null,
		lateral_length: 1000,
		perf_lateral_length: 1000,
		primary_product: null,
		true_vertical_depth: null,
		copied: true,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: 45,
		surfaceLongitude: 45,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: 10000,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900004'),
		dataPool: 'internal',
		dataSource: 'internal',
		lateral_length: 1000,
		perf_lateral_length: 1000,
		copied: true,
		surfaceLatitude: 45,
		surfaceLongitude: 45,
		total_fluid_volume: 10000,
		project: null,
		primary_product: null,
		true_vertical_depth: null,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900005'),
		dataPool: 'internal',
		dataSource: 'other',
		project: null,
		copied: false,
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900006'),
		dataPool: 'internal',
		dataSource: 'di',
		project: new ObjectId('123456789012345678901001'),
		copied: false,
		lateral_length: null,
		perf_lateral_length: null,
		primary_product: null,
		true_vertical_depth: null,
		first_fluid_volume: null,
		first_prop_weight: null,
		measured_depth: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: null,
	},
	{
		_id: new ObjectId('123456789012345678900007'),
		chosenID: '12345678900005',
		dataSource: 'internal',
		project: new ObjectId('60f1dfaa3d2f562ef8475140'),
		first_fluid_volume: null,
		first_prod_date: null,
		first_prop_weight: null,
		lateral_length: null,
		measured_depth: null,
		perf_lateral_length: null,
		primary_product: null,
		surfaceLatitude: null,
		surfaceLongitude: null,
		true_vertical_depth: null,
		first_proppant_per_fluid: null,
		refrac_proppant_per_perforated_interval: null,
		refrac_fluid_per_perforated_interval: null,
		refrac_proppant_per_fluid: null,
		total_fluid_volume: null,
		total_prop_weight: null,
		total_proppant_per_fluid: null,
		first_proppant_per_perforated_interval: null,
		first_fluid_per_perforated_interval: null,
		total_fluid_per_perforated_interval: null,
		total_proppant_per_perforated_interval: null,
		first_prod_date_daily_calc: null,
		first_prod_date_monthly_calc: new Date('2000-05-15T00:00:00.000Z'),
		createdAt: new Date('2021-07-17T03:57:22.578Z'),
		inptID: 'INPTwl5uhUCyTZ',
		has_monthly: true,
		last_prod_date_monthly: new Date('2001-08-15T00:00:00.000Z'),
		has_daily: false,
		last_prod_date_daily: null,
		schemaVersion: 1,
		dataPool: 'internal',
		chosenKeyID: 'chosen id',
		mostRecentImport: new ObjectId('60f256edc505e6216f1f6f0e'),
		mostRecentImportDesc: 'internal-cpeña20210717t000427',
		mostRecentImportType: 'spreadsheet',
		mostRecentImportDate: new Date('2021-07-17T04:04:59.231Z'),
		well_name: 'well 5',
		updatedAt: new Date('2021-07-17T04:07:25.634Z'),
		total_additive_volume: null,
		total_cluster_count: null,
		total_stage_count: null,
		copied: false,
	},
];

beforeAll(async () => {
	({ db, client, mongod } = await setupDb());
});

afterAll(async () => {
	await mongod.stop();
	await client.close();
});

describe('20210719155753-set-well-defaults', () => {
	let wellsCollection;

	beforeAll(async () => {
		wellsCollection = db.collection('wells');
		await wellsCollection.insertMany(wellsBefore);
	});

	test('up', async () => {
		await up({ db });

		const result = await wellsCollection.find({}).sort({ _id: 1 }).toArray();

		expect(result).toEqual(wellsAfter);
	});

	test('idempotency', async () => {
		await up({ db });
		await up({ db });

		const result = await wellsCollection.find({}).sort({ _id: 1 }).toArray();

		expect(result).toEqual(wellsAfter);
	});
});
