const toApiEconMonthly = (econMonthly) => ({
	comboName: econMonthly.combo_name,
	date: econMonthly.date && econMonthly.date.value,
	output: toApiEconMonthlyData(econMonthly),
	well: econMonthly.well_id,
});

// eslint-disable-next-line complexity
const toApiEconMonthlyData = (econMonthly) => ({
	adValoremTax: econMonthly.ad_valorem_tax ?? null,
	afterIncomeTaxCashFlow: econMonthly.after_income_tax_cash_flow ?? null,
	beforeIncomeTaxCashFlow: econMonthly.before_income_tax_cash_flow ?? null,
	depreciation: econMonthly.depreciation ?? null,
	dripCondensateGatheringExpense: econMonthly.drip_condensate_gathering_expense ?? null,
	dripCondensateMarketingExpense: econMonthly.drip_condensate_marketing_expense ?? null,
	dripCondensateOtherExpense: econMonthly.drip_condensate_other_expense ?? null,
	dripCondensatePrice: econMonthly.drip_condensate_price ?? null,
	dripCondensateProcessingExpense: econMonthly.drip_condensate_processing_expense ?? null,
	dripCondensateRevenue: econMonthly.drip_condensate_revenue ?? null,
	dripCondensateSeveranceTax: econMonthly.drip_condensate_severance_tax ?? null,
	dripCondensateTransportationExpense: econMonthly.drip_condensate_transportation_expense ?? null,
	federalIncomeTax: econMonthly.federal_income_tax ?? null,
	firstDiscountCashFlow: econMonthly.first_discount_cash_flow ?? null,
	gasGatheringExpense: econMonthly.gas_gathering_expense ?? null,
	gasMarketingExpense: econMonthly.gas_marketing_expense ?? null,
	gasOtherExpense: econMonthly.gas_other_expense ?? null,
	gasPrice: econMonthly.gas_price ?? null,
	gasProcessingExpense: econMonthly.gas_processing_expense ?? null,
	gasRevenue: econMonthly.gas_revenue ?? null,
	gasSeveranceTax: econMonthly.gas_severance_tax ?? null,
	gasStartUsingForecastDate: econMonthly.gas_start_using_forecast_date ?? null,
	gasTransportationExpense: econMonthly.gas_transportation_expense ?? null,
	grossBoeSalesVolume: econMonthly.gross_boe_sales_volume ?? null,
	grossBoeWellHeadVolume: econMonthly.gross_boe_well_head_volume ?? null,
	grossDripCondensateSalesVolume: econMonthly.gross_drip_condensate_sales_volume ?? null,
	grossGasSalesVolume: econMonthly.gross_gas_sales_volume ?? null,
	grossGasWellHeadVolume: econMonthly.gross_gas_well_head_volume ?? null,
	grossNglSalesVolume: econMonthly.gross_ngl_sales_volume ?? null,
	grossOilSalesVolume: econMonthly.gross_oil_sales_volume ?? null,
	grossOilWellHeadVolume: econMonthly.gross_oil_well_head_volume ?? null,
	grossWaterWellHeadVolume: econMonthly.gross_water_well_head_volume ?? null,
	grossWellCount: econMonthly.gross_well_count ?? null,
	intangibleAbandonment: econMonthly.intangible_abandonment ?? null,
	intangibleAppraisal: econMonthly.intangible_appraisal ?? null,
	intangibleArtificialLift: econMonthly.intangible_artificial_lift ?? null,
	intangibleCompletion: econMonthly.intangible_completion ?? null,
	intangibleDevelopment: econMonthly.intangible_development ?? null,
	intangibleDrilling: econMonthly.intangible_drilling ?? null,
	intangibleExploration: econMonthly.intangible_exploration ?? null,
	intangibleFacilities: econMonthly.intangible_facilities ?? null,
	intangibleLeasehold: econMonthly.intangible_leasehold ?? null,
	intangibleLegal: econMonthly.intangible_legal ?? null,
	intangibleOtherInvestment: econMonthly.intangible_other_investment ?? null,
	intangiblePad: econMonthly.intangible_pad ?? null,
	intangiblePipelines: econMonthly.intangible_pipelines ?? null,
	intangibleSalvage: econMonthly.intangible_salvage ?? null,
	intangibleWaterline: econMonthly.intangible_waterline ?? null,
	intangibleWorkover: econMonthly.intangible_workover ?? null,
	monthlyWellCost: econMonthly.monthly_well_cost ?? null,
	netBoeSalesVolume: econMonthly.net_boe_sales_volume ?? null,
	netDripCondensateSalesVolume: econMonthly.net_drip_condensate_sales_volume ?? null,
	netGasSalesVolume: econMonthly.net_gas_sales_volume ?? null,
	netNglSalesVolume: econMonthly.net_ngl_sales_volume ?? null,
	netOilSalesVolume: econMonthly.net_oil_sales_volume ?? null,
	netProfit: econMonthly.net_profit ?? null,
	nglGatheringExpense: econMonthly.ngl_gathering_expense ?? null,
	nglMarketingExpense: econMonthly.ngl_marketing_expense ?? null,
	nglOtherExpense: econMonthly.ngl_other_expense ?? null,
	nglPrice: econMonthly.ngl_price ?? null,
	nglProcessingExpense: econMonthly.ngl_processing_expense ?? null,
	nglRevenue: econMonthly.ngl_revenue ?? null,
	nglSeveranceTax: econMonthly.ngl_severance_tax ?? null,
	nglTransportationExpense: econMonthly.ngl_transportation_expense ?? null,
	nriDripCondensate: econMonthly.nri_drip_condensate ?? null,
	nriGas: econMonthly.nri_gas ?? null,
	nriNgl: econMonthly.nri_ngl ?? null,
	nriOil: econMonthly.nri_oil ?? null,
	nriWellCount: econMonthly.nri_well_count ?? null,
	oilGatheringExpense: econMonthly.oil_gathering_expense ?? null,
	oilMarketingExpense: econMonthly.oil_marketing_expense ?? null,
	oilOtherExpense: econMonthly.oil_other_expense ?? null,
	oilPrice: econMonthly.oil_price ?? null,
	oilProcessingExpense: econMonthly.oil_processing_expense ?? null,
	oilRevenue: econMonthly.oil_revenue ?? null,
	oilSeveranceTax: econMonthly.oil_severance_tax ?? null,
	oilStartUsingForecastDate: econMonthly.oil_start_using_forecast_date ?? null,
	oilTransportationExpense: econMonthly.oil_transportation_expense ?? null,
	otherMonthlyCost_1: econMonthly.other_monthly_cost_1 ?? null,
	otherMonthlyCost_2: econMonthly.other_monthly_cost_2 ?? null,
	secondDiscountCashFlow: econMonthly.second_discount_cash_flow ?? null,
	stateIncomeTax: econMonthly.state_income_tax ?? null,
	tangibleAbandonment: econMonthly.tangible_abandonment ?? null,
	tangibleAppraisal: econMonthly.tangible_appraisal ?? null,
	tangibleArtificialLift: econMonthly.tangible_artificial_lift ?? null,
	tangibleCompletion: econMonthly.tangible_completion ?? null,
	tangibleDevelopment: econMonthly.tangible_development ?? null,
	tangibleDrilling: econMonthly.tangible_drilling ?? null,
	tangibleExploration: econMonthly.tangible_exploration ?? null,
	tangibleFacilities: econMonthly.tangible_facilities ?? null,
	tangibleLeasehold: econMonthly.tangible_leasehold ?? null,
	tangibleLegal: econMonthly.tangible_legal ?? null,
	tangibleOtherInvestment: econMonthly.tangible_other_investment ?? null,
	tangiblePad: econMonthly.tangible_pad ?? null,
	tangiblePipelines: econMonthly.tangible_pipelines ?? null,
	tangibleSalvage: econMonthly.tangible_salvage ?? null,
	tangibleWaterline: econMonthly.tangible_waterline ?? null,
	tangibleWorkover: econMonthly.tangible_workover ?? null,
	taxableIncome: econMonthly.taxable_income ?? null,
	totalAbandonment: econMonthly.total_abandonment ?? null,
	totalAppraisal: econMonthly.total_appraisal ?? null,
	totalArtificialLift: econMonthly.total_artificial_lift ?? null,
	totalCapex: econMonthly.total_capex ?? null,
	totalCompletion: econMonthly.total_completion ?? null,
	totalDevelopment: econMonthly.total_development ?? null,
	totalDrilling: econMonthly.total_drilling ?? null,
	totalDripCondensateVariableExpense: econMonthly.total_drip_condensate_variable_expense ?? null,
	totalExpense: econMonthly.total_expense ?? null,
	totalExploration: econMonthly.total_exploration ?? null,
	totalFacilities: econMonthly.total_facilities ?? null,
	totalFixedExpense: econMonthly.total_fixed_expense ?? null,
	totalGasVariableExpense: econMonthly.total_gas_variable_expense ?? null,
	totalGrossCapex: econMonthly.total_gross_capex ?? null,
	totalIntangibleCapex: econMonthly.total_intangible_capex ?? null,
	totalLeasehold: econMonthly.total_leasehold ?? null,
	totalLegal: econMonthly.total_legal ?? null,
	totalNglVariableExpense: econMonthly.total_ngl_variable_expense ?? null,
	totalOilVariableExpense: econMonthly.total_oil_variable_expense ?? null,
	totalOtherInvestment: econMonthly.total_other_investment ?? null,
	totalPad: econMonthly.total_pad ?? null,
	totalPipelines: econMonthly.total_pipelines ?? null,
	totalProductionTax: econMonthly.total_production_tax ?? null,
	totalRevenue: econMonthly.total_revenue ?? null,
	totalSalvage: econMonthly.total_salvage ?? null,
	totalSeveranceTax: econMonthly.total_severance_tax ?? null,
	totalTangibleCapex: econMonthly.total_tangible_capex ?? null,
	totalVariableExpense: econMonthly.total_variable_expense ?? null,
	totalWaterline: econMonthly.total_waterline ?? null,
	totalWorkover: econMonthly.total_workover ?? null,
	waterDisposal: econMonthly.water_disposal ?? null,
	waterStartUsingForecastDate: econMonthly.water_start_using_forecast_date ?? null,
	wiBoeSalesVolume: econMonthly.wi_boe_sales_volume ?? null,
	wiDripCondensate: econMonthly.wi_drip_condensate ?? null,
	wiDripCondensateSalesVolume: econMonthly.wi_drip_condensate_sales_volume ?? null,
	wiGas: econMonthly.wi_gas ?? null,
	wiGasSalesVolume: econMonthly.wi_gas_sales_volume ?? null,
	wiNgl: econMonthly.wi_ngl ?? null,
	wiNglSalesVolume: econMonthly.wi_ngl_sales_volume ?? null,
	wiOil: econMonthly.wi_oil ?? null,
	wiOilSalesVolume: econMonthly.wi_oil_sales_volume ?? null,
	wiWellCount: econMonthly.wi_well_count ?? null,
	dripCondensateDifferentials1: econMonthly.drip_condensate_differentials_1 ?? null,
	dripCondensateDifferentials2: econMonthly.drip_condensate_differentials_2 ?? null,
	dripCondensateYield: econMonthly.drip_condensate_yield ?? null,
	firstDiscountNetIncome: econMonthly.first_discount_net_income ?? null,
	firstDiscountedCapex: econMonthly.first_discounted_capex ?? null,
	gasDifferentials1: econMonthly.gas_differentials_1 ?? null,
	gasDifferentials2: econMonthly.gas_differentials_2 ?? null,
	gasFlare: econMonthly.gas_flare ?? null,
	gasLoss: econMonthly.gas_loss ?? null,
	gasShrinkage: econMonthly.gas_shrinkage ?? null,
	grossMcfeSalesVolume: econMonthly.gross_mcfe_sales_volume ?? null,
	grossMcfeWellHeadVolume: econMonthly.gross_mcfe_well_head_volume ?? null,
	inputDripCondensatePrice: econMonthly.input_drip_condensate_price ?? null,
	inputGasPrice: econMonthly.input_gas_price ?? null,
	inputNglPrice: econMonthly.input_ngl_price ?? null,
	inputOilPrice: econMonthly.input_oil_price ?? null,
	leaseNri: econMonthly.lease_nri ?? null,
	netIncome: econMonthly.net_income ?? null,
	netMcfeSalesVolume: econMonthly.net_mcfe_sales_volume ?? null,
	nglDifferentials1: econMonthly.ngl_differentials_1 ?? null,
	nglDifferentials2: econMonthly.ngl_differentials_2 ?? null,
	nglYield: econMonthly.ngl_yield ?? null,
	oilDifferentials1: econMonthly.oil_differentials_1 ?? null,
	oilDifferentials2: econMonthly.oil_differentials_2 ?? null,
	oilLoss: econMonthly.oil_loss ?? null,
	oilShrinkage: econMonthly.oil_shrinkage ?? null,
	secondDiscountNetIncome: econMonthly.second_discount_net_income ?? null,
	secondDiscountedCapex: econMonthly.second_discounted_capex ?? null,
	wiMcfeSalesVolume: econMonthly.wi_mcfe_sales_volume ?? null,
});

const toEconMonthlyTableSchema = (econMonthly) => ({
	created_at: econMonthly.created_at,
	ad_valorem_tax: econMonthly.ad_valorem_tax,
	after_income_tax_cash_flow: econMonthly.after_income_tax_cash_flow,
	before_income_tax_cash_flow: econMonthly.before_income_tax_cash_flow,
	capex_qualifier: econMonthly.capex_qualifier,
	combo_name: econMonthly.combo_name,
	date: econMonthly.date,
	dates_qualifier: econMonthly.dates_qualifier,
	depreciation: econMonthly.depreciation,
	drip_condensate_gathering_expense: econMonthly.drip_condensate_gathering_expense,
	drip_condensate_marketing_expense: econMonthly.drip_condensate_marketing_expense,
	drip_condensate_other_expense: econMonthly.drip_condensate_other_expense,
	drip_condensate_price: econMonthly.drip_condensate_price,
	drip_condensate_processing_expense: econMonthly.drip_condensate_processing_expense,
	drip_condensate_revenue: econMonthly.drip_condensate_revenue,
	drip_condensate_severance_tax: econMonthly.drip_condensate_severance_tax,
	drip_condensate_transportation_expense: econMonthly.drip_condensate_transportation_expense,
	error: econMonthly.error,
	expenses_qualifier: econMonthly.expenses_qualifier,
	federal_income_tax: econMonthly.federal_income_tax,
	first_discount_cash_flow: econMonthly.first_discount_cash_flow,
	forecast_p_series_qualifier: econMonthly.forecast_p_series_qualifier,
	forecast_qualifier: econMonthly.forecast_qualifier,
	gas_gathering_expense: econMonthly.gas_gathering_expense,
	gas_marketing_expense: econMonthly.gas_marketing_expense,
	gas_other_expense: econMonthly.gas_other_expense,
	gas_price: econMonthly.gas_price,
	gas_processing_expense: econMonthly.gas_processing_expense,
	gas_revenue: econMonthly.gas_revenue,
	gas_severance_tax: econMonthly.gas_severance_tax,
	gas_transportation_expense: econMonthly.gas_transportation_expense,
	gross_boe_sales_volume: econMonthly.gross_boe_sales_volume,
	gross_boe_well_head_volume: econMonthly.gross_boe_well_head_volume,
	gross_drip_condensate_sales_volume: econMonthly.gross_drip_condensate_sales_volume,
	gross_gas_sales_volume: econMonthly.gross_gas_sales_volume,
	gross_gas_well_head_volume: econMonthly.gross_gas_well_head_volume,
	gross_ngl_sales_volume: econMonthly.gross_ngl_sales_volume,
	gross_oil_sales_volume: econMonthly.gross_oil_sales_volume,
	gross_oil_well_head_volume: econMonthly.gross_oil_well_head_volume,
	gross_water_well_head_volume: econMonthly.gross_water_well_head_volume,
	intangible_abandonment: econMonthly.intangible_abandonment,
	intangible_appraisal: econMonthly.intangible_appraisal,
	intangible_artificial_lift: econMonthly.intangible_artificial_lift,
	intangible_completion: econMonthly.intangible_completion,
	intangible_development: econMonthly.intangible_development,
	intangible_drilling: econMonthly.intangible_drilling,
	intangible_exploration: econMonthly.intangible_exploration,
	intangible_facilities: econMonthly.intangible_facilities,
	intangible_leasehold: econMonthly.intangible_leasehold,
	intangible_legal: econMonthly.intangible_legal,
	intangible_other_investment: econMonthly.intangible_other_investment,
	intangible_pad: econMonthly.intangible_pad,
	intangible_pipelines: econMonthly.intangible_pipelines,
	intangible_salvage: econMonthly.intangible_salvage,
	intangible_waterline: econMonthly.intangible_waterline,
	intangible_workover: econMonthly.intangible_workover,
	monthly_well_cost: econMonthly.monthly_well_cost,
	net_boe_sales_volume: econMonthly.net_boe_sales_volume,
	net_drip_condensate_sales_volume: econMonthly.net_drip_condensate_sales_volume,
	net_gas_sales_volume: econMonthly.net_gas_sales_volume,
	net_ngl_sales_volume: econMonthly.net_ngl_sales_volume,
	net_oil_sales_volume: econMonthly.net_oil_sales_volume,
	net_profit: econMonthly.net_profit,
	ngl_gathering_expense: econMonthly.ngl_gathering_expense,
	ngl_marketing_expense: econMonthly.ngl_marketing_expense,
	ngl_other_expense: econMonthly.ngl_other_expense,
	ngl_price: econMonthly.ngl_price,
	ngl_processing_expense: econMonthly.ngl_processing_expense,
	ngl_revenue: econMonthly.ngl_revenue,
	ngl_severance_tax: econMonthly.ngl_severance_tax,
	ngl_transportation_expense: econMonthly.ngl_transportation_expense,
	nri_drip_condensate: econMonthly.nri_drip_condensate,
	nri_gas: econMonthly.nri_gas,
	nri_ngl: econMonthly.nri_ngl,
	nri_oil: econMonthly.nri_oil,
	oil_gathering_expense: econMonthly.oil_gathering_expense,
	oil_marketing_expense: econMonthly.oil_marketing_expense,
	oil_other_expense: econMonthly.oil_other_expense,
	oil_price: econMonthly.oil_price,
	oil_processing_expense: econMonthly.oil_processing_expense,
	oil_revenue: econMonthly.oil_revenue,
	oil_severance_tax: econMonthly.oil_severance_tax,
	oil_transportation_expense: econMonthly.oil_transportation_expense,
	other_monthly_cost_1: econMonthly.other_monthly_cost_1,
	other_monthly_cost_2: econMonthly.other_monthly_cost_2,
	other_monthly_cost_3: econMonthly.other_monthly_cost_3,
	other_monthly_cost_4: econMonthly.other_monthly_cost_4,
	other_monthly_cost_5: econMonthly.other_monthly_cost_5,
	other_monthly_cost_6: econMonthly.other_monthly_cost_6,
	other_monthly_cost_7: econMonthly.other_monthly_cost_7,
	other_monthly_cost_8: econMonthly.other_monthly_cost_8,
	ownership_reversion_qualifier: econMonthly.ownership_reversion_qualifier,
	econ_prms_reserves_category: econMonthly.econ_prms_reserves_category,
	econ_prms_reserves_sub_category: econMonthly.econ_prms_reserves_sub_category,
	econ_prms_resources_class: econMonthly.econ_prms_resources_class,
	production_taxes_qualifier: econMonthly.production_taxes_qualifier,
	production_vs_fit_qualifier: econMonthly.production_vs_fit_qualifier,
	reserves_category_qualifier: econMonthly.reserves_category_qualifier,
	risking_qualifier: econMonthly.risking_qualifier,
	run_date: econMonthly.run_date,
	run_id: econMonthly.run_id,
	schedule_qualifier: econMonthly.schedule_qualifier,
	second_discount_cash_flow: econMonthly.second_discount_cash_flow,
	state_income_tax: econMonthly.state_income_tax,
	stream_properties_qualifier: econMonthly.stream_properties_qualifier,
	tangible_abandonment: econMonthly.tangible_abandonment,
	tangible_appraisal: econMonthly.tangible_appraisal,
	tangible_artificial_lift: econMonthly.tangible_artificial_lift,
	tangible_completion: econMonthly.tangible_completion,
	tangible_development: econMonthly.tangible_development,
	tangible_drilling: econMonthly.tangible_drilling,
	tangible_exploration: econMonthly.tangible_exploration,
	tangible_facilities: econMonthly.tangible_facilities,
	tangible_leasehold: econMonthly.tangible_leasehold,
	tangible_legal: econMonthly.tangible_legal,
	tangible_other_investment: econMonthly.tangible_other_investment,
	tangible_pad: econMonthly.tangible_pad,
	tangible_pipelines: econMonthly.tangible_pipelines,
	tangible_salvage: econMonthly.tangible_salvage,
	tangible_waterline: econMonthly.tangible_waterline,
	tangible_workover: econMonthly.tangible_workover,
	taxable_income: econMonthly.taxable_income,
	total_abandonment: econMonthly.total_abandonment,
	total_appraisal: econMonthly.total_appraisal,
	total_artificial_lift: econMonthly.total_artificial_lift,
	total_capex: econMonthly.total_capex,
	total_completion: econMonthly.total_completion,
	total_development: econMonthly.total_development,
	total_drilling: econMonthly.total_drilling,
	total_drip_condensate_variable_expense: econMonthly.total_drip_condensate_variable_expense,
	total_expense: econMonthly.total_expense,
	total_exploration: econMonthly.total_exploration,
	total_facilities: econMonthly.total_facilities,
	total_fixed_expense: econMonthly.total_fixed_expense,
	total_gas_variable_expense: econMonthly.total_gas_variable_expense,
	total_intangible_capex: econMonthly.total_intangible_capex,
	total_leasehold: econMonthly.total_leasehold,
	total_legal: econMonthly.total_legal,
	total_ngl_variable_expense: econMonthly.total_ngl_variable_expense,
	total_oil_variable_expense: econMonthly.total_oil_variable_expense,
	total_other_investment: econMonthly.total_other_investment,
	total_pad: econMonthly.total_pad,
	total_pipelines: econMonthly.total_pipelines,
	total_production_tax: econMonthly.total_production_tax,
	total_revenue: econMonthly.total_revenue,
	total_salvage: econMonthly.total_salvage,
	total_severance_tax: econMonthly.total_severance_tax,
	total_tangible_capex: econMonthly.total_tangible_capex,
	total_variable_expense: econMonthly.total_variable_expense,
	total_waterline: econMonthly.total_waterline,
	total_workover: econMonthly.total_workover,
	warning: econMonthly.warning,
	water_disposal: econMonthly.water_disposal,
	well_id: econMonthly.well_id,
	well_index: econMonthly.well_index,
	wi_boe_sales_volume: econMonthly.wi_boe_sales_volume,
	wi_drip_condensate: econMonthly.wi_drip_condensate,
	wi_drip_condensate_sales_volume: econMonthly.wi_drip_condensate_sales_volume,
	wi_gas: econMonthly.wi_gas,
	wi_gas_sales_volume: econMonthly.wi_gas_sales_volume,
	wi_ngl: econMonthly.wi_ngl,
	wi_ngl_sales_volume: econMonthly.wi_ngl_sales_volume,
	wi_oil: econMonthly.wi_oil,
	wi_oil_sales_volume: econMonthly.wi_oil_sales_volume,
	combo_well_id: econMonthly.combo_well_id,
	gross_well_count: econMonthly.gross_well_count,
	wi_well_count: econMonthly.wi_well_count,
	nri_well_count: econMonthly.nri_well_count,
	oil_start_using_forecast_date: econMonthly.oil_start_using_forecast_date,
	gas_start_using_forecast_date: econMonthly.gas_start_using_forecast_date,
	water_start_using_forecast_date: econMonthly.water_start_using_forecast_date,
	reversion_date: econMonthly.reversion_date,
	gor: econMonthly.gor,
	wor: econMonthly.wor,
	water_cut: econMonthly.water_cut,
	econ_first_production_date: econMonthly.econ_first_production_date,
	pricing_qualifier: econMonthly.pricing_qualifier,
	differentials_qualifier: econMonthly.differentials_qualifier,
	incremental_name: econMonthly.incremental_name,
	incremental_index: econMonthly.incremental_index,
	combo_well_incremental_id: econMonthly.combo_well_incremental_id,
	first_discounted_capex: econMonthly.first_discounted_capex,
	second_discounted_capex: econMonthly.second_discounted_capex,
	net_income: econMonthly.net_income,
	first_discount_net_income: econMonthly.first_discount_net_income,
	second_discount_net_income: econMonthly.second_discount_net_income,
	input_oil_price: econMonthly.input_oil_price,
	input_gas_price: econMonthly.input_gas_price,
	input_ngl_price: econMonthly.input_ngl_price,
	input_drip_condensate_price: econMonthly.input_drip_condensate_price,
	oil_differentials_1: econMonthly.oil_differentials_1,
	gas_differentials_1: econMonthly.gas_differentials_1,
	ngl_differentials_1: econMonthly.ngl_differentials_1,
	drip_condensate_differentials_1: econMonthly.drip_condensate_differentials_1,
	oil_differentials_2: econMonthly.oil_differentials_2,
	gas_differentials_2: econMonthly.gas_differentials_2,
	ngl_differentials_2: econMonthly.ngl_differentials_2,
	drip_condensate_differentials_2: econMonthly.drip_condensate_differentials_2,
	oil_differentials_3: econMonthly.oil_differentials_3,
	gas_differentials_3: econMonthly.gas_differentials_3,
	ngl_differentials_3: econMonthly.ngl_differentials_3,
	drip_condensate_differentials_3: econMonthly.drip_condensate_differentials_3,
	ngl_yield: econMonthly.ngl_yield,
	drip_condensate_yield: econMonthly.drip_condensate_yield,
	oil_shrinkage: econMonthly.oil_shrinkage,
	gas_shrinkage: econMonthly.gas_shrinkage,
	oil_loss: econMonthly.oil_loss,
	gas_loss: econMonthly.gas_loss,
	gas_flare: econMonthly.gas_flare,
	gross_mcfe_well_head_volume: econMonthly.gross_mcfe_well_head_volume,
	gross_mcfe_sales_volume: econMonthly.gross_mcfe_sales_volume,
	wi_mcfe_sales_volume: econMonthly.wi_mcfe_sales_volume,
	net_mcfe_sales_volume: econMonthly.net_mcfe_sales_volume,
	lease_nri: econMonthly.lease_nri,
	oil_risk: econMonthly.oil_risk,
	gas_risk: econMonthly.gas_risk,
	ngl_risk: econMonthly.ngl_risk,
	drip_condensate_risk: econMonthly.drip_condensate_risk,
	water_risk: econMonthly.water_risk,
	pre_risk_oil_volume: econMonthly.pre_risk_oil_volume,
	pre_risk_gas_volume: econMonthly.pre_risk_gas_volume,
	pre_risk_water_volume: econMonthly.pre_risk_water_volume,
	pre_risk_ngl_volume: econMonthly.pre_risk_ngl_volume,
	pre_risk_drip_condensate_volume: econMonthly.pre_risk_drip_condensate_volume,
	unshrunk_oil_volume: econMonthly.unshrunk_oil_volume,
	unshrunk_gas_volume: econMonthly.unshrunk_gas_volume,
	pre_flare_gas_volume: econMonthly.pre_flare_gas_volume,
	total_gross_capex: econMonthly.total_gross_capex,
	pre_yield_gas_volume_drip_condensate: econMonthly.pre_yield_gas_volume_drip_condensate,
	pre_yield_gas_volume_ngl: econMonthly.pre_yield_gas_volume_ngl,
});

const toWellHeaderTableSchema = (econMonthly) => ({
	well_id: econMonthly.well_id,
	run_id: econMonthly.run_id,
	run_date: econMonthly.run_date,
	created_at: econMonthly.created_at,
	prms_resources_class: econMonthly.prms_resources_class,
	prms_reserves_category: econMonthly.prms_reserves_category,
	prms_reserves_sub_category: econMonthly.prms_reserves_sub_category,
	api14: econMonthly.api14,
	basin: econMonthly.basin,
	chosen_id: econMonthly.chosen_id,
	county: econMonthly.county,
	current_operator: econMonthly.current_operator,
	current_operator_alias: econMonthly.current_operator_alias,
	first_prod_date_monthly_calc: econMonthly.first_prod_date_monthly_calc,
	hole_direction: econMonthly.hole_direction,
	hz_well_spacing_same_zone: econMonthly.hz_well_spacing_same_zone,
	inpt_id: econMonthly.inpt_id,
	landing_zone: econMonthly.landing_zone,
	perf_lateral_length: econMonthly.perf_lateral_length,
	stage_spacing: econMonthly.stage_spacing,
	state: econMonthly.state,
	status: econMonthly.status,
	surface_latitude: econMonthly.surface_latitude,
	surface_longitude: econMonthly.surface_longitude,
	target_formation: econMonthly.target_formation,
	toe_latitude: econMonthly.toe_latitude,
	toe_longitude: econMonthly.toe_longitude,
	total_fluid_per_perforated_interval: econMonthly.total_fluid_per_perforated_interval,
	total_proppant_per_perforated_interval: econMonthly.total_proppant_per_perforated_interval,
	total_stage_count: econMonthly.total_stage_count,
	true_vertical_depth: econMonthly.true_vertical_depth,
	type_curve_area: econMonthly.type_curve_area,
	vt_well_spacing_same_zone: econMonthly.vt_well_spacing_same_zone,
	well_name: econMonthly.well_name,
	well_number: econMonthly.well_number,
	well_type: econMonthly.well_type,
	field: econMonthly.field,
	play: econMonthly.play,
	oil_gatherer: econMonthly.oil_gatherer,
	gas_gatherer: econMonthly.gas_gatherer,
	ngl_gatherer: econMonthly.ngl_gatherer,
	pad_name: econMonthly.pad_name,
	acre_spacing: econMonthly.acre_spacing,
	allocation_type: econMonthly.allocation_type,
	api10: econMonthly.api10,
	aries_id: econMonthly.aries_id,
	azimuth: econMonthly.azimuth,
	completion_design: econMonthly.completion_design,
	completion_end_date: econMonthly.completion_end_date,
	completion_start_date: econMonthly.completion_start_date,
	country: econMonthly.country,
	cum_boe: econMonthly.cum_boe,
	cum_boe_per_perforated_interval: econMonthly.cum_boe_per_perforated_interval,
	cum_gas: econMonthly.cum_gas,
	cum_gas_per_perforated_interval: econMonthly.cum_gas_per_perforated_interval,
	cum_gor: econMonthly.cum_gor,
	cum_mmcfge: econMonthly.cum_mmcfge,
	cum_mmcfge_per_perforated_interval: econMonthly.cum_mmcfge_per_perforated_interval,
	cum_oil: econMonthly.cum_oil,
	cum_oil_per_perforated_interval: econMonthly.cum_oil_per_perforated_interval,
	cum_water: econMonthly.cum_water,
	cum_water_per_perforated_interval: econMonthly.cum_water_per_perforated_interval,
	current_operator_ticker: econMonthly.current_operator_ticker,
	data_source: econMonthly.data_source,
	drainage_area: econMonthly.drainage_area,
	drill_end_date: econMonthly.drill_end_date,
	drill_start_date: econMonthly.drill_start_date,
	first_6_boe: econMonthly.first_6_boe,
	first_6_boe_per_perforated_interval: econMonthly.first_6_boe_per_perforated_interval,
	first_6_gas: econMonthly.first_6_gas,
	first_6_gas_per_perforated_interval: econMonthly.first_6_gas_per_perforated_interval,
	first_6_gor: econMonthly.first_6_gor,
	first_6_mmcfge: econMonthly.first_6_mmcfge,
	first_6_mmcfge_per_perforated_interval: econMonthly.first_6_mmcfge_per_perforated_interval,
	first_6_oil: econMonthly.first_6_oil,
	first_6_oil_per_perforated_interval: econMonthly.first_6_oil_per_perforated_interval,
	first_6_water: econMonthly.first_6_water,
	first_6_water_per_perforated_interval: econMonthly.first_6_water_per_perforated_interval,
	first_cluster_count: econMonthly.first_cluster_count,
	first_fluid_per_perforated_interval: econMonthly.first_fluid_per_perforated_interval,
	first_fluid_volume: econMonthly.first_fluid_volume,
	first_prod_date: econMonthly.first_prod_date,
	first_prod_date_daily_calc: econMonthly.first_prod_date_daily_calc,
	first_prop_weight: econMonthly.first_prop_weight,
	first_proppant_per_fluid: econMonthly.first_proppant_per_fluid,
	first_proppant_per_perforated_interval: econMonthly.first_proppant_per_perforated_interval,
	first_stage_count: econMonthly.first_stage_count,
	first_treatment_type: econMonthly.first_treatment_type,
	fluid_type: econMonthly.fluid_type,
	footage_in_landing_zone: econMonthly.footage_in_landing_zone,
	formation_thickness_mean: econMonthly.formation_thickness_mean,
	generic: econMonthly.generic,
	gross_perforated_interval: econMonthly.gross_perforated_interval,
	has_daily: econMonthly.has_daily,
	has_monthly: econMonthly.has_monthly,
	heel_latitude: econMonthly.heel_latitude,
	heel_longitude: econMonthly.heel_longitude,
	horizontal_spacing: econMonthly.horizontal_spacing,
	hz_well_spacing_any_zone: econMonthly.hz_well_spacing_any_zone,
	last_prod_date_daily: econMonthly.last_prod_date_daily,
	last_prod_date_monthly: econMonthly.last_prod_date_monthly,
	lateral_length: econMonthly.lateral_length,
	lease_name: econMonthly.lease_name,
	measured_depth: econMonthly.measured_depth,
	months_produced: econMonthly.months_produced,
	num_treatment_records: econMonthly.num_treatment_records,
	oil_specific_gravity: econMonthly.oil_specific_gravity,
	parent_child_any_zone: econMonthly.parent_child_any_zone,
	parent_child_same_zone: econMonthly.parent_child_same_zone,
	percent_in_zone: econMonthly.percent_in_zone,
	permit_date: econMonthly.permit_date,
	previous_operator: econMonthly.previous_operator,
	previous_operator_alias: econMonthly.previous_operator_alias,
	previous_operator_ticker: econMonthly.previous_operator_ticker,
	primary_product: econMonthly.primary_product,
	production_method: econMonthly.production_method,
	proppant_mesh_size: econMonthly.proppant_mesh_size,
	proppant_type: econMonthly.proppant_type,
	refrac_fluid_per_perforated_interval: econMonthly.refrac_fluid_per_perforated_interval,
	refrac_fluid_volume: econMonthly.refrac_fluid_volume,
	refrac_prop_weight: econMonthly.refrac_prop_weight,
	refrac_proppant_per_fluid: econMonthly.refrac_proppant_per_fluid,
	refrac_proppant_per_perforated_interval: econMonthly.refrac_proppant_per_perforated_interval,
	refrac_stage_count: econMonthly.refrac_stage_count,
	refrac_treatment_type: econMonthly.refrac_treatment_type,
	section: econMonthly.section,
	spud_date: econMonthly.spud_date,
	subplay: econMonthly.subplay,
	thickness: econMonthly.thickness,
	total_additive_volume: econMonthly.total_additive_volume,
	total_cluster_count: econMonthly.total_cluster_count,
	total_fluid_volume: econMonthly.total_fluid_volume,
	total_prop_weight: econMonthly.total_prop_weight,
	total_proppant_per_fluid: econMonthly.total_proppant_per_fluid,
	township: econMonthly.township,
	vertical_spacing: econMonthly.vertical_spacing,
	vt_well_spacing_any_zone: econMonthly.vt_well_spacing_any_zone,
	abstract: econMonthly.abstract,
	api12: econMonthly.api12,
	block: econMonthly.block,
	chosen_key_id: econMonthly.chosen_key_id,
	current_operator_code: econMonthly.current_operator_code,
	district: econMonthly.district,
	elevation_type: econMonthly.elevation_type,
	first_frac_vendor: econMonthly.first_frac_vendor,
	flow_path: econMonthly.flow_path,
	most_recent_import_type: econMonthly.most_recent_import_type,
	lease_number: econMonthly.lease_number,
	phdwin_id: econMonthly.phdwin_id,
	previous_operator_code: econMonthly.previous_operator_code,
	range: econMonthly.range,
	recovery_method: econMonthly.recovery_method,
	refrac_frac_vendor: econMonthly.refrac_frac_vendor,
	rig: econMonthly.rig,
	survey: econMonthly.survey,
	toe_in_landing_zone: econMonthly.toe_in_landing_zone,
	toe_up: econMonthly.toe_up,
	most_recent_import_desc: econMonthly.most_recent_import_desc,
	custom_string_0: econMonthly.custom_string_0,
	custom_string_1: econMonthly.custom_string_1,
	custom_string_2: econMonthly.custom_string_2,
	custom_string_3: econMonthly.custom_string_3,
	custom_string_4: econMonthly.custom_string_4,
	custom_string_5: econMonthly.custom_string_5,
	custom_string_6: econMonthly.custom_string_6,
	custom_string_7: econMonthly.custom_string_7,
	custom_string_8: econMonthly.custom_string_8,
	custom_string_9: econMonthly.custom_string_9,
	custom_string_10: econMonthly.custom_string_10,
	custom_string_11: econMonthly.custom_string_11,
	custom_string_12: econMonthly.custom_string_12,
	custom_string_13: econMonthly.custom_string_13,
	custom_string_14: econMonthly.custom_string_14,
	custom_string_15: econMonthly.custom_string_15,
	custom_string_16: econMonthly.custom_string_16,
	custom_string_17: econMonthly.custom_string_17,
	custom_string_18: econMonthly.custom_string_18,
	custom_string_19: econMonthly.custom_string_19,
});

const toMetadataTableSchema = (econMonthly) => ({
	run_id: econMonthly.run_id,
	run_date: econMonthly.run_date,
	project_id: econMonthly.project_id,
	project_name: econMonthly.project_name,
	scenario_id: econMonthly.scenario_id,
	scenario_name: econMonthly.scenario_name,
	user_id: econMonthly.user_id,
	user_name: econMonthly.user_name,
	general_options_name: econMonthly.general_options_name,
	schema_version: econMonthly.schema_version,
	created_at: econMonthly.created_at,
});

module.exports = {
	toApiEconMonthly,
	toEconMonthlyTableSchema,
	toMetadataTableSchema,
	toWellHeaderTableSchema,
};
