// https://docs.google.com/spreadsheets/d/1Px_1k9rMES7UMJwnXlWNUtYyz1u_YQYPV2GhPXN6g78/edit?pli=1#gid=201468329
// label, include in agg report?
const onelineMetricsLabelsFromDoc = [
	['Gross Well Count', true],
	['WI Well Count', true],
	['NRI Well Count', true],
	['Pre Yield Gas Volume Drip Condensate (gas)', true],
	['Pre Yield Gas Volume NGL (gas)', true],
	['Pre Risk Oil Volume (MBBL)', true],
	['Pre Risk Gas Volume (MMCF)', true],
	['Pre Risk Water Volume (MBBL)', true],
	['Pre Risk Drip Condensate Volume (MBBL)', true],
	['Pre Risk NGL Volume (MBBL)', true],
	['Unshrunk Oil Volume (MBBL)', true],
	['Unshrunk Gas Volume (MMCF)', true],
	['Pre Flare Gas Volume (MMCF)', true],
	['Gross Oil Well Head Volume (MBBL)', true],
	['Gross Gas Well Head Volume (MMCF)', true],
	['Gross BOE Well Head Volume (MBBL)', true],
	['Gross MCFE Well Head Volume (MMCF)', true],
	['Gross Water Well Head Volume (MBBL)', true],
	['Gross Oil Sales Volume (MBBL)', true],
	['Gross Gas Sales Volume (MMCF)', true],
	['Gross NGL Sales Volume (MBBL)', true],
	['Gross Drip Condensate Sales Volume (MBBL)', true],
	['Gross BOE Sales Volume (MBBL)', true],
	['Gross MCFE Sales Volume (MMCF)', true],
	['WI Oil (%)', true],
	['WI Gas (%)', true],
	['WI NGL (%)', true],
	['WI Drip Condensate (%)', true],
	['First Reversion WI Oil (%)', false],
	['First Reversion WI Gas (%)', false],
	['First Reversion WI NGL (%)', false],
	['First Reversion WI Drip Condensate (%)', false],
	['NRI Oil (%)', true],
	['NRI Gas (%)', true],
	['NRI NGL (%)', true],
	['NRI Drip Condensate (%)', true],
	['First Reversion NRI Oil (%)', false],
	['First Reversion NRI Gas (%)', false],
	['First Reversion NRI NGL (%)', false],
	['First Reversion NRI Drip Condensate (%)', false],
	['Lease NRI (%)', true],
	['Original Lease NRI (%)', false],
	['Gross CO2e Mass Emitted (MT)', true],
	['Gross CO2 Mass Emitted (MT)', true],
	['Gross CH4 Mass Emitted (MT)', true],
	['Gross N2O Mass Emitted (MT)', true],
	['WI CO2e Mass Emitted (MT)', true],
	['WI CO2 Mass Emitted (MT)', true],
	['WI CH4 Mass Emitted (MT)', true],
	['WI N2O Mass Emitted (MT)', true],
	['NRI CO2e Mass Emitted (MT)', true],
	['NRI CO2 Mass Emitted (MT)', true],
	['NRI CH4 Mass Emitted (MT)', true],
	['NRI N2O Mass Emitted (MT)', true],
	['WI Oil Sales Volume (MBBL)', true],
	['WI Gas Sales Volume (MMCF)', true],
	['WI NGL Sales Volume (MBBL)', true],
	['WI Drip Condensate Sales Volume (MBBL)', true],
	['WI BOE Sales Volume (MBBL)', true],
	['WI MCFE Sales Volume (MMCF)', true],
	['WI Water Sales Volume (MBBL)', true],
	['Net Oil Sales Volume (MBBL)', true],
	['Net Gas Sales Volume (MMCF)', true],
	['Net NGL Sales Volume (MBBL)', true],
	['Net Drip Condensate Sales Volume (MBBL)', true],
	['Net BOE Sales Volume (MBBL)', true],
	['Net MCFE Sales Volume (MMCF)', true],
	['Net Water Sales Volume (MBBL)', true],
	['Net Oil Well Head Volume (MBBL)', true],
	['Net Gas Well Head Volume (MMCF)', true],
	['Net Water Well Head Volume (MBBL)', true],
	['NGL Yield (BBL/MMCF)', true],
	['Drip Condensate Yield (BBL/MMCF)', true],
	['Oil Shrinkage (%)', true],
	['Gas Shrinkage (%)', true],
	['Oil Loss (%)', true],
	['Gas Loss (%)', true],
	['Gas Flare (%)', true],
	['Unshrunk Gas BTU (MBTU/MCF)', false],
	['Shrunk Gas BTU (MBTU/MCF)', false],
	['Input Oil Price ($/BBL)', false],
	['Input Gas Price ($/MCF)', false],
	['Input NGL Price ($/BBL)', false],
	['Input Drip Condensate Price ($/BBL)', false],
	['Oil Differential 1 ($/BBL)', false],
	['Gas Differential 1 ($/MCF)', false],
	['NGL Differential 1 ($/BBL)', false],
	['Drip Condensate Differential 1 ($/BBL)', false],
	['Oil Differential 2 ($/BBL)', false],
	['Gas Differential 2 ($/MCF)', false],
	['NGL Differential 2 ($/BBL)', false],
	['Drip Condensate Differential 2 ($/BBL)', false],
	['Oil Differential 3 ($/BBL)', false],
	['Gas Differential 3 ($/MCF)', false],
	['NGL Differential 3 ($/BBL)', false],
	['Drip Condensate Differential 3 ($/BBL)', false],
	['Realized Oil Price ($/BBL)', false],
	['Realized Gas Price ($/MCF)', false],
	['Realized NGL Price ($/BBL)', false],
	['Realized Drip Condensate Price ($/BBL)', false],
	['Oil Differentials Input ($/BBL)', false],
	['Gas Differentials Input ($/MMBTU)', false],
	['NGL Differentials Input ($/BBL)', false],
	['Drip Condensate Differentials Input ($/BBL)', false],
	['Net Oil Revenue (M$)', true],
	['Net Gas Revenue (M$)', true],
	['Net NGL Revenue (M$)', true],
	['Net Drip Condensate Revenue (M$)', true],
	['Total Net Revenue (M$)', true],
	['Oil G & P Expense (M$)', true],
	['Oil OPC Expense (M$)', true],
	['Oil TRN Expense (M$)', true],
	['Oil MKT Expense (M$)', true],
	['Oil Other Expense (M$)', true],
	['Total Oil Variable Expense (M$)', true],
	['Gas G & P Expense (M$)', true],
	['Gas OPC Expense (M$)', true],
	['Gas TRN Expense (M$)', true],
	['Gas MKT Expense (M$)', true],
	['Gas Other Expense (M$)', true],
	['Total Gas Variable Expense (M$)', true],
	['NGL G & P Expense (M$)', true],
	['NGL OPC Expense (M$)', true],
	['NGL TRN Expense (M$)', true],
	['NGL MKT Expense (M$)', true],
	['NGL Other Expense (M$)', true],
	['Total NGL Variable Expense (M$)', true],
	['Drip Condensate G & P Expense (M$)', true],
	['Drip Condensate OPC Expense (M$)', true],
	['Drip Condensate TRN Expense (M$)', true],
	['Drip Condensate MKT Expense (M$)', true],
	['Drip Condensate Other Expense (M$)', true],
	['Total Drip Condensate Variable Expense (M$)', true],
	['Water Disposal Expense (M$)', true],
	['CO2e Expense (M$)', true],
	['CO2 Expense (M$)', true],
	['CH4 Expense (M$)', true],
	['N2O Expense (M$)', true],
	['Total Carbon Expense (M$)', true],
	['Total Variable Expense (M$)', true],
	['Fixed Expense 1 (M$)', true],
	['Fixed Expense 2 (M$)', true],
	['Fixed Expense 3 (M$)', true],
	['Fixed Expense 4 (M$)', true],
	['Fixed Expense 5 (M$)', true],
	['Fixed Expense 6 (M$)', true],
	['Fixed Expense 7 (M$)', true],
	['Fixed Expense 8 (M$)', true],
	['Fixed Expense 9 (M$)', true],
	['Total Fixed Expense (M$)', true],
	['Total Expense (M$)', true],
	['Total Oil Variable Expense Input ($/BBL)', true],
	['Total Gas Variable Expense Input ($/MCF)', true],
	['Total Water Variable Expense Input ($/BBL)', true],
	['Total NGL Variable Expense Input ($/BBL)', true],
	['Total Drip Condensate Variable Expense Input ($/BBL)', true],
	['Oil Severance Tax (M$)', true],
	['Gas Severance Tax (M$)', true],
	['NGL Severance Tax (M$)', true],
	['Drip Condensate Severance Tax (M$)', true],
	['Total Severance Tax (M$)', true],
	['Ad Valorem Tax (M$)', true],
	['Total Production Tax (M$)', true],
	['Net Tangible Drilling (M$)', true],
	['Net Intangible Drilling (M$)', true],
	['Total Net Drilling (M$)', true],
	['Net Tangible Completion (M$)', true],
	['Net Intangible Completion (M$)', true],
	['Total Net Completion (M$)', true],
	['Net Tangible Legal (M$)', true],
	['Net Intangible Legal (M$)', true],
	['Total Net Legal (M$)', true],
	['Net Tangible Pad (M$)', true],
	['Net Intangible Pad (M$)', true],
	['Total Net Pad (M$)', true],
	['Net Tangible Facilities (M$)', true],
	['Net Intangible Facilities (M$)', true],
	['Total Net Facilities (M$)', true],
	['Net Tangible Artificial Lift (M$)', true],
	['Net Intangible Artificial Lift (M$)', true],
	['Total Net Artificial Lift (M$)', true],
	['Net Tangible Workover (M$)', true],
	['Net Intangible Workover (M$)', true],
	['Total Net Workover (M$)', true],
	['Net Tangible Leasehold (M$)', true],
	['Net Intangible Leasehold (M$)', true],
	['Total Net Leasehold (M$)', true],
	['Net Tangible Development (M$)', true],
	['Net Intangible Development (M$)', true],
	['Total Net Development (M$)', true],
	['Net Tangible Pipelines (M$)', true],
	['Net Intangible Pipelines (M$)', true],
	['Total Net Pipelines (M$)', true],
	['Net Tangible Exploration (M$)', true],
	['Net Intangible Exploration (M$)', true],
	['Total Net Exploration (M$)', true],
	['Net Tangible Waterline (M$)', true],
	['Net Intangible Waterline (M$)', true],
	['Total Net Waterline (M$)', true],
	['Net Tangible Appraisal (M$)', true],
	['Net Intangible Appraisal (M$)', true],
	['Total Net Appraisal (M$)', true],
	['Net Tangible Other Investment (M$)', true],
	['Net Intangible Other Investment (M$)', true],
	['Total Net Other Investment (M$)', true],
	['Net Tangible Abandonment (M$)', true],
	['Net Intangible Abandonment (M$)', true],
	['Total Net Abandonment (M$)', true],
	['Net Tangible Salvage (M$)', true],
	['Net Intangible Salvage (M$)', true],
	['Total Net Salvage (M$)', true],
	['Total Net Tangible Investment (M$)', true],
	['Total Net Intangible Investment (M$)', true],
	['Total Net Investment (M$)', true],
	['First Discount Total Net Investment', true], // '10% Discount Total Net CAPEX (M$)',
	['Second Discount Total Net Investment', true], // '20% Discount Total Net CAPEX (M$)',
	['Total Gross Investment (M$)', true],
	['NPI Cash Flow (M$)', true],
	['Net Operating Income (M$)', true],
	['First Discount Net Operating Income', true], // '10% Discount Net Operating Income (M$)',
	['Second Discount Net Operating Income', true], // '20% Discount Net Operating Income (M$)',
	['Before Income Tax Cash Flow (M$)', true],
	['Reversion Amount (M$)', false],
	['First Discount Cash Flow', true], // '10% Discount Cash Flow (M$)'
	['Second Discount Cash Flow', true], // '20% Discount Cash Flow (M$)'
	['Tax Credit (M$)', true],
	['Tangible Depreciation (M$)', true],
	['Intangible Depreciation (M$)', true],
	['Total Depreciation (M$)', true],
	['Total Depletion (M$)', true],
	['Tangible Cost Depletion (M$)', true],
	['Intangible Cost Depletion (M$)', true],
	['Percentage Depletion (M$)', true],
	['Total Deductions (M$)', true],
	['Taxable Income (M$)', true],
	['State Income Tax (M$)', true],
	['Federal Income Tax (M$)', true],
	['After Income Tax Cash Flow (M$)', true],
	['AFIT First Discount Cash Flow', true], // '10% After Income Tax Discount Cash Flow (M$)'
	['AFIT Second Discount Cash Flow', true], // '20% After Income Tax Discount Cash Flow (M$)'
	['After Tax Income Undiscounted ROI (ratio)', true],
	['After Tax Income First Discount ROI (Discounted CAPEX)', true], // '10% After Income Tax Discount ROI w/ Discounted CAPEX (ratio)'
	['After Tax Income Second Discount ROI (Discounted CAPEX)', true], // '20% After Income Tax Discount ROI w/ Discounted CAPEX (ratio)'
	['After Tax Income First Discount ROI (Undiscounted CAPEX)', true], // '10% After Income Tax Discount ROI w/ Undiscounted CAPEX (ratio)'
	['After Tax Income Second Discount ROI (Undiscounted CAPEX)', true], // '20% After Income Tax Discount ROI w/ Undiscounted CAPEX (ratio)'
	['After Tax Income IRR (%)', true],
	['After Income Tax Undiscounted Payout Date', true],
	['After Income Tax Payout Duration (months)', true],
	['After Income Tax First Discount Payout Date', true], // '10% After Income Tax Discount Payout Date'
	['After Income Tax First Discount Payout Duration', true], // '10% After Income Tax Discount Payout Duration (months)'
	['After Income Tax Second Discount Payout Date', true], // '20% After Income Tax Discount Payout Date'
	['After Income Tax Second Discount Payout Duration', true], // '20% After Income Tax Discount Payout Duration (months)'
	['Econ Well Life (years)', true],
	['Abandonment Date', false],
	['Interest Reversion Date', false],
	['Oil Scenario Risk Factor (%)', false],
	['Gas Scenario Risk Factor (%)', false],
	['NGL Scenario Risk Factor (%)', false],
	['Drip Condensate Scenario Risk Factor (%)', false],
	['Water Scenario Risk Factor (%)', false],
	['Oil Forecast Risk Factor (%)', false],
	['Gas Forecast Risk Factor (%)', false],
	['Water Forecast Risk Factor (%)', false],
	['Oil Production to As Of Date (MBBL)', false],
	['Gas Production to As Of Date (MMCF)', false],
	['Water Production to As Of Date (MBBL)', false],
	['Undiscounted ROI (ratio)', true],
	['First Discount ROI (Discounted CAPEX)', true], // '10% Discount ROI w/ Discounted CAPEX (ratio)'
	['Second Discount ROI (Discounted CAPEX)', true], // '20% Discount ROI w/ Discounted CAPEX (ratio)'
	['First Discount ROI (Undiscounted CAPEX)', true], // '10% Discount ROI w/ Undiscounted CAPEX (ratio)'
	['Second Discount ROI (Undiscounted CAPEX)', true], // '20% Discount ROI w/ Undiscounted CAPEX (ratio)'
	['IRR (%)', true],
	['Undiscounted Payout Date', true],
	['Payout Duration (months)', true],
	['First Discount Payout Date', true], // '10% Discount Payout Date'
	['First Discount Payout Duration', true], // '10% Discount Payout Duration (months)'
	['Second Discount Payout Date', true], // '20% Discount Payout Date'
	['Second Discount Payout Duration', true], // '20% Discount Payout Duration (months)'
	['GOR (CF/BBL)', true],
	['WOR (BBL/BBL)', true],
	['Water Cut (%)', true],
	['Oil Break Even ($/BBL)', false],
	['Gas Break Even ($/MCF)', false],
	['Original WI Oil (%)', false],
	['Original WI Gas (%)', false],
	['Original WI NGL (%)', false],
	['Original WI Drip Condensate (%)', false],
	['Original NRI Oil (%)', false],
	['Original NRI Gas (%)', false],
	['Original NRI NGL (%)', false],
	['Original NRI Drip Condensate (%)', false],
	['Consecutive Negative Cash Flow Months', false],
	['First Consecutive Negative Cash Flow Month', false],
	['Last Consecutive Negative Cash Flow Month', false],
	['Consecutive Negative Cash Flow Month Count', false],
	['Total Negative Cash Flow Month Count', false],
	['First Discount Rate (%)', false],
	['Second Discount Rate (%)', false],
	['Third Discount Rate (%)', false],
	['Fourth Discount Rate (%)', false],
	['1 Year Capital Efficiency Attribute', false],
	['3 Year Capital Efficiency Attribute', false],
	['Well Life Capital Efficiency Attribute', false],
	['1 Month Gross Oil Well Head Volume (MBBL)', false],
	['3 Month Gross Oil Well Head Volume (MBBL)', false],
	['6 Month Gross Oil Well Head Volume (MBBL)', false],
	['1 Year Gross Oil Well Head Volume (MBBL)', false],
	['2 Year Gross Oil Well Head Volume (MBBL)', false],
	['3 Year Gross Oil Well Head Volume (MBBL)', false],
	['5 Year Gross Oil Well Head Volume (MBBL)', false],
	['10 Year Gross Oil Well Head Volume (MBBL)', false],
	['1 Month Gross Oil Sales Volume (MBBL)', false],
	['3 Month Gross Oil Sales Volume (MBBL)', false],
	['6 Month Gross Oil Sales Volume (MBBL)', false],
	['1 Year Gross Oil Sales Volume (MBBL)', false],
	['2 Year Gross Oil Sales Volume (MBBL)', false],
	['3 Year Gross Oil Sales Volume (MBBL)', false],
	['5 Year Gross Oil Sales Volume (MBBL)', false],
	['10 Year Gross Oil Sales Volume (MBBL)', false],
	['1 Month WI Oil Sales Volume (MBBL)', false],
	['3 Month WI Oil Sales Volume (MBBL)', false],
	['6 Month WI Oil Sales Volume (MBBL)', false],
	['1 Year WI Oil Sales Volume (MBBL)', false],
	['2 Year WI Oil Sales Volume (MBBL)', false],
	['3 Year WI Oil Sales Volume (MBBL)', false],
	['5 Year WI Oil Sales Volume (MBBL)', false],
	['10 Year WI Oil Sales Volume (MBBL)', false],
	['1 Month Net Oil Sales Volume (MBBL)', false],
	['3 Month Net Oil Sales Volume (MBBL)', false],
	['6 Month Net Oil Sales Volume (MBBL)', false],
	['1 Year Net Oil Sales Volume (MBBL)', false],
	['2 Year Net Oil Sales Volume (MBBL)', false],
	['3 Year Net Oil Sales Volume (MBBL)', false],
	['5 Year Net Oil Sales Volume (MBBL)', false],
	['10 Year Net Oil Sales Volume (MBBL)', false],
	['1 Month Gross Gas Well Head Volume (MMCF)', false],
	['3 Month Gross Gas Well Head Volume (MMCF)', false],
	['6 Month Gross Gas Well Head Volume (MMCF)', false],
	['1 Year Gross Gas Well Head Volume (MMCF)', false],
	['2 Year Gross Gas Well Head Volume (MMCF)', false],
	['3 Year Gross Gas Well Head Volume (MMCF)', false],
	['5 Year Gross Gas Well Head Volume (MMCF)', false],
	['10 Year Gross Gas Well Head Volume (MMCF)', false],
	['1 Month Gross Gas Sales Volume (MMCF)', false],
	['3 Month Gross Gas Sales Volume (MMCF)', false],
	['6 Month Gross Gas Sales Volume (MMCF)', false],
	['1 Year Gross Gas Sales Volume (MMCF)', false],
	['2 Year Gross Gas Sales Volume (MMCF)', false],
	['3 Year Gross Gas Sales Volume (MMCF)', false],
	['5 Year Gross Gas Sales Volume (MMCF)', false],
	['10 Year Gross Gas Sales Volume (MMCF)', false],
	['1 Month WI Gas Sales Volume (MMCF)', false],
	['3 Month WI Gas Sales Volume (MMCF)', false],
	['6 Month WI Gas Sales Volume (MMCF)', false],
	['1 Year WI Gas Sales Volume (MMCF)', false],
	['2 Year WI Gas Sales Volume (MMCF)', false],
	['3 Year WI Gas Sales Volume (MMCF)', false],
	['5 Year WI Gas Sales Volume (MMCF)', false],
	['10 Year WI Gas Sales Volume (MMCF)', false],
	['1 Month Net Gas Sales Volume (MMCF)', false],
	['3 Month Net Gas Sales Volume (MMCF)', false],
	['6 Month Net Gas Sales Volume (MMCF)', false],
	['1 Year Net Gas Sales Volume (MMCF)', false],
	['2 Year Net Gas Sales Volume (MMCF)', false],
	['3 Year Net Gas Sales Volume (MMCF)', false],
	['5 Year Net Gas Sales Volume (MMCF)', false],
	['10 Year Net Gas Sales Volume (MMCF)', false],
	['1 Month Gross BOE Well Head Volume (MBBL)', false],
	['3 Month Gross BOE Well Head Volume (MBBL)', false],
	['6 Month Gross BOE Well Head Volume (MBBL)', false],
	['1 Year Gross BOE Well Head Volume (MBBL)', false],
	['2 Year Gross BOE Well Head Volume (MBBL)', false],
	['3 Year Gross BOE Well Head Volume (MBBL)', false],
	['5 Year Gross BOE Well Head Volume (MBBL)', false],
	['10 Year Gross BOE Well Head Volume (MBBL)', false],
	['1 Month Gross BOE Sales Volume (MBBL)', false],
	['3 Month Gross BOE Sales Volume (MBBL)', false],
	['6 Month Gross BOE Sales Volume (MBBL)', false],
	['1 Year Gross BOE Sales Volume (MBBL)', false],
	['2 Year Gross BOE Sales Volume (MBBL)', false],
	['3 Year Gross BOE Sales Volume (MBBL)', false],
	['5 Year Gross BOE Sales Volume (MBBL)', false],
	['10 Year Gross BOE Sales Volume (MBBL)', false],
	['1 Month WI BOE Sales Volume (MBBL)', false],
	['3 Month WI BOE Sales Volume (MBBL)', false],
	['6 Month WI BOE Sales Volume (MBBL)', false],
	['1 Year WI BOE Sales Volume (MBBL)', false],
	['2 Year WI BOE Sales Volume (MBBL)', false],
	['3 Year WI BOE Sales Volume (MBBL)', false],
	['5 Year WI BOE Sales Volume (MBBL)', false],
	['10 Year WI BOE Sales Volume (MBBL)', false],
	['1 Month Net BOE Sales Volume (MBBL)', false],
	['3 Month Net BOE Sales Volume (MBBL)', false],
	['6 Month Net BOE Sales Volume (MBBL)', false],
	['1 Year Net BOE Sales Volume (MBBL)', false],
	['2 Year Net BOE Sales Volume (MBBL)', false],
	['3 Year Net BOE Sales Volume (MBBL)', false],
	['5 Year Net BOE Sales Volume (MBBL)', false],
	['10 Year Net BOE Sales Volume (MBBL)', false],
	['1 Month Gross NGL Sales Volume (MBBL)', false],
	['3 Month Gross NGL Sales Volume (MBBL)', false],
	['6 Month Gross NGL Sales Volume (MBBL)', false],
	['1 Year Gross NGL Sales Volume (MBBL)', false],
	['2 Year Gross NGL Sales Volume (MBBL)', false],
	['3 Year Gross NGL Sales Volume (MBBL)', false],
	['5 Year Gross NGL Sales Volume (MBBL)', false],
	['10 Year Gross NGL Sales Volume (MBBL)', false],
	['1 Month WI NGL Sales Volume (MBBL)', false],
	['3 Month WI NGL Sales Volume (MBBL)', false],
	['6 Month WI NGL Sales Volume (MBBL)', false],
	['1 Year WI NGL Sales Volume (MBBL)', false],
	['2 Year WI NGL Sales Volume (MBBL)', false],
	['3 Year WI NGL Sales Volume (MBBL)', false],
	['5 Year WI NGL Sales Volume (MBBL)', false],
	['10 Year WI NGL Sales Volume (MBBL)', false],
	['1 Month Net NGL Sales Volume (MBBL)', false],
	['3 Month Net NGL Sales Volume (MBBL)', false],
	['6 Month Net NGL Sales Volume (MBBL)', false],
	['1 Year Net NGL Sales Volume (MBBL)', false],
	['2 Year Net NGL Sales Volume (MBBL)', false],
	['3 Year Net NGL Sales Volume (MBBL)', false],
	['5 Year Net NGL Sales Volume (MBBL)', false],
	['10 Year Net NGL Sales Volume (MBBL)', false],
	['1 Month Gross Water Well Head Volume (MBBL)', false],
	['3 Month Gross Water Well Head Volume (MBBL)', false],
	['6 Month Gross Water Well Head Volume (MBBL)', false],
	['1 Year Gross Water Well Head Volume (MBBL)', false],
	['2 Year Gross Water Well Head Volume (MBBL)', false],
	['3 Year Gross Water Well Head Volume (MBBL)', false],
	['5 Year Gross Water Well Head Volume (MBBL)', false],
	['10 Year Gross Water Well Head Volume (MBBL)', false],
	['1 Month Gross Drip Condensate Sales Volume (MBBL)', false],
	['3 Month Gross Drip Condensate Sales Volume (MBBL)', false],
	['6 Month Gross Drip Condensate Sales Volume (MBBL)', false],
	['1 Year Gross Drip Condensate Sales Volume (MBBL)', false],
	['2 Year Gross Drip Condensate Sales Volume (MBBL)', false],
	['3 Year Gross Drip Condensate Sales Volume (MBBL)', false],
	['5 Year Gross Drip Condensate Sales Volume (MBBL)', false],
	['10 Year Gross Drip Condensate Sales Volume (MBBL)', false],
	['1 Month WI Drip Condensate Sales Volume (MBBL)', false],
	['3 Month WI Drip Condensate Sales Volume (MBBL)', false],
	['6 Month WI Drip Condensate Sales Volume (MBBL)', false],
	['1 Year WI Drip Condensate Sales Volume (MBBL)', false],
	['2 Year WI Drip Condensate Sales Volume (MBBL)', false],
	['3 Year WI Drip Condensate Sales Volume (MBBL)', false],
	['5 Year WI Drip Condensate Sales Volume (MBBL)', false],
	['10 Year WI Drip Condensate Sales Volume (MBBL)', false],
	['1 Month Net Drip Condensate Sales Volume (MBBL)', false],
	['3 Month Net Drip Condensate Sales Volume (MBBL)', false],
	['6 Month Net Drip Condensate Sales Volume (MBBL)', false],
	['Oil Well Head EUR (MBBL)', true],
	['Gas Well Head EUR (MMCF)', true],
	['Water Well Head EUR (MBBL)', true],
	['Oil Shrunk EUR (MBBL)', true],
	['Gas Shrunk EUR (MMCF)', true],
	['NGL EUR (MBBL)', true],
	['Drip Condensate EUR (MBBL)', true],
] as const;

const [onelineMetricsLabelsByWell, onelineMetricsLabelsAgg] = onelineMetricsLabelsFromDoc.reduce(
	(acc, [label, includeInAgg]) => {
		acc[0].push(label);
		if (includeInAgg) acc[1].push(label);
		return acc;
	},
	[[] as string[], [] as string[]]
);

export { onelineMetricsLabelsByWell, onelineMetricsLabelsAgg };
