export const reportDetails = [
	'Project Name',
	'Scenario Name',
	'User Name',
	'Combo Name',
	'Reserves Category Qualifier',
	'Ownership and Reversion Qualifier',
	'Dates Qualifier',
	'Forecast Qualifier',
	'Forecast P Series Qualifier',
	'Schedule Qualifier',
	'CAPEX Qualifier',
	'Pricing Qualifier',
	'Differentials Qualifier',
	'Stream Properties Qualifier',
	'Expenses Qualifier',
	'Production Taxes Qualifier',
	'Actual or Forecast Qualifier',
	'Risking Qualifier',
	'Created At',
	'Ownership and Reversion Model Name',
	'Oil BOE Conversion (BBL/BOE)',
	'Wet Gas BOE Conversion (MCF/BOE)',
	'Dry Gas BOE Conversion (MCF/BOE)',
	'NGL BOE Conversion (BBL/BOE)',
	'Drip Condensate BOE Conversion (BBL/BOE)',
	'Stream Properties Model Name',
	'Differentials Model Name',
	'Pricing Model Name',
	'Expense Model Name',
	'Production Taxes Model Name',
	'CAPEX Model Name',
	'Forecast Name',
	'Dates Model Name',
	'Risking Model Name',
	'As Of Date',
	'Discount Date',
	'Date',
	'Time',
	'Aggregation Date',
];
