export const timeSeriesMetrics = [
	'Gross Well Count',
	'WI Well Count',
	'NRI Well Count',
	'Pre Yield Gas Volume Drip Condensate (gas)',
	'Pre Yield Gas Volume NGL (gas)',
	'Pre Risk Oil Volume (MBBL)',
	'Pre Risk Gas Volume (MMCF)',
	'Pre Risk Water Volume (MBBL)',
	'Pre Risk Drip Condensate Volume (MBBL)',
	'Pre Risk NGL Volume (MBBL)',
	'Unshrunk Oil Volume (MBBL)',
	'Unshrunk Gas Volume (MMCF)',
	'Pre Flare Gas Volume (MMCF)',
	'Gross Oil Well Head Volume (MBBL)',
	'Gross Gas Well Head Volume (MMCF)',
	'Gross BOE Well Head Volume (MBBL)',
	'Gross MCFE Well Head Volume (MMCF)',
	'Gross Water Well Head Volume (MBBL)',
	'Gross Oil Sales Volume (MBBL)',
	'Gross Gas Sales Volume (MMCF)',
	'Gross NGL Sales Volume (MBBL)',
	'Gross Drip Condensate Sales Volume (MBBL)',
	'Gross BOE Sales Volume (MBBL)',
	'Gross MCFE Sales Volume (MMCF)',
	'WI Oil (%)',
	'WI Gas (%)',
	'WI NGL (%)',
	'WI Drip Condensate (%)',
	'NRI Oil (%)',
	'NRI Gas (%)',
	'NRI NGL (%)',
	'NRI Drip Condensate (%)',
	'Lease NRI (%)',
	'Gross CO2e Mass Emitted (MT)',
	'Gross CO2 Mass Emitted (MT)',
	'Gross CH4 Mass Emitted (MT)',
	'Gross N2O Mass Emitted (MT)',
	'WI CO2e Mass Emitted (MT)',
	'WI CO2 Mass Emitted (MT)',
	'WI CH4 Mass Emitted (MT)',
	'WI N2O Mass Emitted (MT)',
	'NRI CO2e Mass Emitted (MT)',
	'NRI CO2 Mass Emitted (MT)',
	'NRI CH4 Mass Emitted (MT)',
	'NRI N2O Mass Emitted (MT)',
	'WI Oil Sales Volume (MBBL)',
	'WI Gas Sales Volume (MMCF)',
	'WI NGL Sales Volume (MBBL)',
	'WI Drip Condensate Sales Volume (MBBL)',
	'WI BOE Sales Volume (MBBL)',
	'WI MCFE Sales Volume (MMCF)',
	'WI Water Sales Volume (MBBL)',
	'Net Oil Sales Volume (MBBL)',
	'Net Gas Sales Volume (MMCF)',
	'Net NGL Sales Volume (MBBL)',
	'Net Drip Condensate Sales Volume (MBBL)',
	'Net BOE Sales Volume (MBBL)',
	'Net MCFE Sales Volume (MMCF)',
	'Net Water Sales Volume (MBBL)',
	'Net Oil Well Head Volume (MBBL)',
	'Net Gas Well Head Volume (MMCF)',
	'Net Water Well Head Volume (MBBL)',
	'NGL Yield (BBL/MMCF)',
	'Drip Condensate Yield (BBL/MMCF)',
	'Oil Shrinkage (%)',
	'Gas Shrinkage (%)',
	'Oil Loss (%)',
	'Gas Loss (%)',
	'Gas Flare (%)',
	'Input Oil Price ($/BBL)',
	'Input Gas Price ($/MCF)',
	'Input NGL Price ($/BBL)',
	'Input Drip Condensate Price ($/BBL)',
	'Oil Differential 1 ($/BBL)',
	'Gas Differential 1 ($/MCF)',
	'NGL Differential 1 ($/BBL)',
	'Drip Condensate Differential 1 ($/BBL)',
	'Oil Differential 2 ($/BBL)',
	'Gas Differential 2 ($/MCF)',
	'NGL Differential 2 ($/BBL)',
	'Drip Condensate Differential 2 ($/BBL)',
	'Oil Differential 3 ($/BBL)',
	'Gas Differential 3 ($/MCF)',
	'NGL Differential 3 ($/BBL)',
	'Drip Condensate Differential 3 ($/BBL)',
	'Realized Oil Price ($/BBL)',
	'Realized Gas Price ($/MCF)',
	'Realized NGL Price ($/BBL)',
	'Realized Drip Condensate Price ($/BBL)',
	'Net Oil Revenue (M$)',
	'Net Gas Revenue (M$)',
	'Net NGL Revenue (M$)',
	'Net Drip Condensate Revenue (M$)',
	'Total Net Revenue (M$)',
	'Oil G & P Expense (M$)',
	'Oil OPC Expense (M$)',
	'Oil TRN Expense (M$)',
	'Oil MKT Expense (M$)',
	'Oil Other Expense (M$)',
	'Total Oil Variable Expense (M$)',
	'Gas G & P Expense (M$)',
	'Gas OPC Expense (M$)',
	'Gas TRN Expense (M$)',
	'Gas MKT Expense (M$)',
	'Gas Other Expense (M$)',
	'Total Gas Variable Expense (M$)',
	'NGL G & P Expense (M$)',
	'NGL OPC Expense (M$)',
	'NGL TRN Expense (M$)',
	'NGL MKT Expense (M$)',
	'NGL Other Expense (M$)',
	'Total NGL Variable Expense (M$)',
	'Drip Condensate G & P Expense (M$)',
	'Drip Condensate OPC Expense (M$)',
	'Drip Condensate TRN Expense (M$)',
	'Drip Condensate MKT Expense (M$)',
	'Drip Condensate Other Expense (M$)',
	'Total Drip Condensate Variable Expense (M$)',
	'Water Disposal Expense (M$)',
	'CO2e Expense (M$)',
	'CO2 Expense (M$)',
	'CH4 Expense (M$)',
	'N2O Expense (M$)',
	'Total Carbon Expense (M$)',
	'Total Variable Expense (M$)',
	'Fixed Expense 1 (M$)',
	'Fixed Expense 2 (M$)',
	'Fixed Expense 3 (M$)',
	'Fixed Expense 4 (M$)',
	'Fixed Expense 5 (M$)',
	'Fixed Expense 6 (M$)',
	'Fixed Expense 7 (M$)',
	'Fixed Expense 8 (M$)',
	'Fixed Expense 9 (M$)',
	'Total Fixed Expense (M$)',
	'Total Expense (M$)',
	'Oil Severance Tax (M$)',
	'Gas Severance Tax (M$)',
	'NGL Severance Tax (M$)',
	'Drip Condensate Severance Tax (M$)',
	'Total Severance Tax (M$)',
	'Ad Valorem Tax (M$)',
	'Total Production Tax (M$)',
	'Net Tangible Drilling (M$)',
	'Net Intangible Drilling (M$)',
	'Total Net Drilling (M$)',
	'Net Tangible Completion (M$)',
	'Net Intangible Completion (M$)',
	'Total Net Completion (M$)',
	'Net Tangible Legal (M$)',
	'Net Intangible Legal (M$)',
	'Total Net Legal (M$)',
	'Net Tangible Pad (M$)',
	'Net Intangible Pad (M$)',
	'Total Net Pad (M$)',
	'Net Tangible Facilities (M$)',
	'Net Intangible Facilities (M$)',
	'Total Net Facilities (M$)',
	'Net Tangible Artificial Lift (M$)',
	'Net Intangible Artificial Lift (M$)',
	'Total Net Artificial Lift (M$)',
	'Net Tangible Workover (M$)',
	'Net Intangible Workover (M$)',
	'Total Net Workover (M$)',
	'Net Tangible Leasehold (M$)',
	'Net Intangible Leasehold (M$)',
	'Total Net Leasehold (M$)',
	'Net Tangible Development (M$)',
	'Net Intangible Development (M$)',
	'Total Net Development (M$)',
	'Net Tangible Pipelines (M$)',
	'Net Intangible Pipelines (M$)',
	'Total Net Pipelines (M$)',
	'Net Tangible Exploration (M$)',
	'Net Intangible Exploration (M$)',
	'Total Net Exploration (M$)',
	'Net Tangible Waterline (M$)',
	'Net Intangible Waterline (M$)',
	'Total Net Waterline (M$)',
	'Net Tangible Appraisal (M$)',
	'Net Intangible Appraisal (M$)',
	'Total Net Appraisal (M$)',
	'Net Tangible Other Investment (M$)',
	'Net Intangible Other Investment (M$)',
	'Total Net Other Investment (M$)',
	'Net Tangible Abandonment (M$)',
	'Net Intangible Abandonment (M$)',
	'Total Net Abandonment (M$)',
	'Net Tangible Salvage (M$)',
	'Net Intangible Salvage (M$)',
	'Total Net Salvage (M$)',
	'Total Net Tangible Investment (M$)',
	'Total Net Intangible Investment (M$)',
	'Total Net Investment (M$)',
	'First Discount Total Net Investment', // '10% Discount Total Net CAPEX (M$)',
	'Second Discount Total Net Investment', // '15% Discount Total Net CAPEX (M$)',
	'Total Gross Investment (M$)',
	'NPI Cash Flow (M$)',
	'Net Operating Income (M$)',
	'First Discount Net Operating Income', // '10% Discount Net Operating Income (M$)',
	'Second Discount Net Operating Income', // '15% Discount Net Operating Income (M$)',
	'Before Income Tax Cash Flow (M$)',
	'First Discount Cash Flow', // '10% Discount Cash Flow (M$)',
	'Second Discount Cash Flow', // '15% Discount Cash Flow (M$)',
	'Tax Credit (M$)',
	'Tangible Depreciation (M$)',
	'Intangible Depreciation (M$)',
	'Total Depreciation (M$)',
	'Total Depletion (M$)',
	'Tangible Cost Depletion (M$)',
	'Intangible Cost Depletion (M$)',
	'Percentage Depletion (M$)',
	'Total Deductions (M$)',
	'Taxable Income (M$)',
	'State Tax Rate (%)',
	'State Income Tax (M$)',
	'Federal Tax Rate (%)',
	'Federal Income Tax (M$)',
	'After Income Tax Cash Flow (M$)',
	'AFIT First Discount Cash Flow', // '10% After Income Tax Discount Cash Flow (M$)',
	'AFIT Second Discount Cash Flow', // '15% After Income Tax Discount Cash Flow (M$)',
	'Oil Scenario Risk Factor (%)',
	'Gas Scenario Risk Factor (%)',
	'NGL Scenario Risk Factor (%)',
	'Drip Condensate Scenario Risk Factor (%)',
	'Water Scenario Risk Factor (%)',
	'Cum Gross Oil Well Head Volume (MBBL)',
	'Cum Gross Gas Well Head Volume (MMCF)',
	'Cum Gross BOE Well Head Volume (MBBL)',
	'Cum Gross MCFE Well Head Volume (MMCF)',
	'Cum Gross Water Well Head Volume (MBBL)',
	'Cum Gross Oil Sales Volume (MBBL)',
	'Cum Gross Gas Sales Volume (MMCF)',
	'Cum Gross NGL Sales Volume (MBBL)',
	'Cum Gross Drip Condensate Sales Volume (MBBL)',
	'Cum Gross BOE Sales Volume (MBBL)',
	'Cum Gross MCFE Sales Volume (MMCF)',
	'Cum WI Oil Sales Volume (MBBL)',
	'Cum WI Gas Sales Volume (MMCF)',
	'Cum WI NGL Sales Volume (MBBL)',
	'Cum WI Drip Condensate Sales Volume (MBBL)',
	'Cum WI BOE Sales Volume (MBBL)',
	'Cum WI MCFE Sales Volume (MMCF)',
	'Cum WI Water Sales Volume (MBBL)',
	'Cum Net Oil Sales Volume (MBBL)',
	'Cum Net Gas Sales Volume (MMCF)',
	'Cum Net NGL Sales Volume (MBBL)',
	'Cum Net Drip Condensate Sales Volume (MBBL)',
	'Cum Net BOE Sales Volume (MBBL)',
	'Cum Net MCFE Sales Volume (MMCF)',
	'Cum Net Water Sales Volume (MBBL)',
	'Cum Net Oil Well Head Volume (MBBL)',
	'Cum Net Gas Well Head Volume (MMCF)',
	'Cum Net Water Well Head Volume (MBBL)',
	'Cum Net Oil Revenue (M$)',
	'Cum Net Gas Revenue (M$)',
	'Cum Net NGL Revenue (M$)',
	'Cum Net Drip Condensate Revenue (M$)',
	'Cum Total Net Revenue (M$)',
	'Cum Oil G & P Expense (M$)',
	'Cum Oil OPC Expense (M$)',
	'Cum Oil TRN Expense (M$)',
	'Cum Oil MKT Expense (M$)',
	'Cum Oil Other Expense (M$)',
	'Cum Total Oil Variable Expense (M$)',
	'Cum Gas G & P Expense (M$)',
	'Cum Gas OPC Expense (M$)',
	'Cum Gas TRN Expense (M$)',
	'Cum Gas MKT Expense (M$)',
	'Cum Gas Other Expense (M$)',
	'Cum Total Gas Variable Expense (M$)',
	'Cum NGL G & P Expense (M$)',
	'Cum NGL OPC Expense (M$)',
	'Cum NGL TRN Expense (M$)',
	'Cum NGL MKT Expense (M$)',
	'Cum NGL Other Expense (M$)',
	'Cum Total NGL Variable Expense (M$)',
	'Cum Drip Condensate G & P Expense (M$)',
	'Cum Drip Condensate OPC Expense (M$)',
	'Cum Drip Condensate TRN Expense (M$)',
	'Cum Drip Condensate MKT Expense (M$)',
	'Cum Drip Condensate Other Expense (M$)',
	'Cum Total Drip Condensate Variable Expense (M$)',
	'Cum Water Disposal Expense (M$)',
	'Cum CO2e Expense (M$)',
	'Cum CO2 Expense (M$)',
	'Cum CH4 Expense (M$)',
	'Cum N2O Expense (M$)',
	'Cum Total Carbon Expense (M$)',
	'Cum Total Variable Expense (M$)',
	'Cum Fixed Expense 1 (M$)',
	'Cum Fixed Expense 2 (M$)',
	'Cum Fixed Expense 3 (M$)',
	'Cum Fixed Expense 4 (M$)',
	'Cum Fixed Expense 5 (M$)',
	'Cum Fixed Expense 6 (M$)',
	'Cum Fixed Expense 7 (M$)',
	'Cum Fixed Expense 8 (M$)',
	'Cum Fixed Expense 9 (M$)',
	'Cum Total Fixed Expense (M$)',
	'Cum Total Expense (M$)',
	'Cum Oil Severance Tax (M$)',
	'Cum Gas Severance Tax (M$)',
	'Cum NGL Severance Tax (M$)',
	'Cum Drip Condensate Severance Tax (M$)',
	'Cum Total Severance Tax (M$)',
	'Cum Ad Valorem Tax (M$)',
	'Cum Total Production Tax (M$)',
	'Cum Net Tangible Drilling (M$)',
	'Cum Net Intangible Drilling (M$)',
	'Cum Total Net Drilling (M$)',
	'Cum Net Tangible Completion (M$)',
	'Cum Net Intangible Completion (M$)',
	'Cum Total Net Completion (M$)',
	'Cum Net Tangible Legal (M$)',
	'Cum Net Intangible Legal (M$)',
	'Cum Total Net Legal (M$)',
	'Cum Net Tangible Pad (M$)',
	'Cum Net Intangible Pad (M$)',
	'Cum Total Net Pad (M$)',
	'Cum Net Tangible Facilities (M$)',
	'Cum Net Intangible Facilities (M$)',
	'Cum Total Net Facilities (M$)',
	'Cum Net Tangible Artificial Lift (M$)',
	'Cum Net Intangible Artificial Lift (M$)',
	'Cum Total Net Artificial Lift (M$)',
	'Cum Net Tangible Workover (M$)',
	'Cum Net Intangible Workover (M$)',
	'Cum Total Net Workover (M$)',
	'Cum Net Tangible Leasehold (M$)',
	'Cum Net Intangible Leasehold (M$)',
	'Cum Total Net Leasehold (M$)',
	'Cum Net Tangible Development (M$)',
	'Cum Net Intangible Development (M$)',
	'Cum Total Net Development (M$)',
	'Cum Net Tangible Pipelines (M$)',
	'Cum Net Intangible Pipelines (M$)',
	'Cum Total Net Pipelines (M$)',
	'Cum Net Tangible Exploration (M$)',
	'Cum Net Intangible Exploration (M$)',
	'Cum Total Net Exploration (M$)',
	'Cum Net Tangible Waterline (M$)',
	'Cum Net Intangible Waterline (M$)',
	'Cum Total Net Waterline (M$)',
	'Cum Net Tangible Appraisal (M$)',
	'Cum Net Intangible Appraisal (M$)',
	'Cum Total Net Appraisal (M$)',
	'Cum Net Tangible Other Investment (M$)',
	'Cum Net Intangible Other Investment (M$)',
	'Cum Total Net Other Investment (M$)',
	'Cum Net Tangible Abandonment (M$)',
	'Cum Net Intangible Abandonment (M$)',
	'Cum Total Net Abandonment (M$)',
	'Cum Net Tangible Salvage (M$)',
	'Cum Net Intangible Salvage (M$)',
	'Cum Total Net Salvage (M$)',
	'Cum Total Net Tangible Investment (M$)',
	'Cum Total Net Intangible Investment (M$)',
	'Cum Total Net Investment (M$)',
	'Cum First Discount Total Net Investment', // 'Cum 10% Discount Total Net CAPEX (M$)',
	'Cum Second Discount Total Net Investment', // 'Cum 15% Discount Total Net CAPEX (M$)',
	'Cum Total Gross Investment (M$)',
	'Cum NPI Cash Flow (M$)',
	'Cum Net Operating Income (M$)',
	'Cum First Discount Net Operating Income', // 'Cum 10% Discount Net Operating Income (M$)',
	'Cum Second Discount Net Operating Income', // 'Cum 15% Discount Net Operating Income (M$)',
	'Cum Before Income Tax Cash Flow (M$)',
	'Cum First Discount Cash Flow', // 'Cum 10% Discount Cash Flow (M$)',
	'Cum Second Discount Cash Flow', // 'Cum 15% Discount Cash Flow (M$)',
	'Cum Tax Credit (M$)',
	'Cum Tangible Depreciation (M$)',
	'Cum Intangible Depreciation (M$)',
	'Cum Total Depreciation (M$)',
	'Cum Total Depletion (M$)',
	'Cum Tangible Cost Depletion (M$)',
	'Cum Intangible Cost Depletion (M$)',
	'Cum Percentage Depletion (M$)',
	'Cum Total Deductions (M$)',
	'Cum Taxable Income (M$)',
	'Cum State Income Tax (M$)',
	'Cum Federal Income Tax (M$)',
	'Cum After Income Tax Cash Flow (M$)',
	'Cum AFIT First Discount Cash Flow', // 'Cum 10% After Income Tax Discount Cash Flow (M$)',
	'Cum AFIT Second Discount Cash Flow', // 'Cum 15% After Income Tax Discount Cash Flow (M$)',
	'Cum Gross CO2e Mass Emitted (MT)',
	'Cum Gross CO2 Mass Emitted (MT)',
	'Cum Gross CH4 Mass Emitted (MT)',
	'Cum Gross N2O Mass Emitted (MT)',
	'Cum WI CO2e Mass Emitted (MT)',
	'Cum WI CO2 Mass Emitted (MT)',
	'Cum WI CH4 Mass Emitted (MT)',
	'Cum WI N2O Mass Emitted (MT)',
	'Cum NRI CO2e Mass Emitted (MT)',
	'Cum NRI CO2 Mass Emitted (MT)',
	'Cum NRI CH4 Mass Emitted (MT)',
	'Cum NRI N2O Mass Emitted (MT)',
];
